### DISCUSSION TITLE
Refresh Environment Variables in Pods

### DISCUSSION THREAD

**Discussion by Kamalesh-Seervi** [kyverno/policies#1125] [Q&A] [answered]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: refresh-env-var-in-pods     
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
  - name: refresh-from-secret-env
    match:
      any:
      - resources:
          kinds:
          - Secret
          selector:
            matchLabels:
              kyverno.io/watch: "true"
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: "{{request.namespace}}"
      patchStrategicMerge:
        spec:
          template:
            metadata:
              annotations:
                corp.org/random: "{{ random('[0-9a-z]{8}') }}"
            spec:
              containers:
              - env:
                - valueFrom:
                    secretKeyRef:
                      <(name): "{{ request.object.metadata.name }}"
```

```
I0812 18:11:24.371383       1 resource.go:53] background "msg"="fetched trigger resource"  "resourceSpec"={"apiVersion":"v1","kind":"Secret","namespace":"ns1","name":"test-secret-ns1"}
E0812 18:11:24.385963       1 update_request_controller.go:322] background "msg"="" "error"="failed to mutate existing resource, rule response3: variable substitution failed: failed to resolve random('[0-9a-z]{8}') at path /mutate/patchStrategicMerge/spec/template/metadata/annotations/corp.org/random: JMESPath query failed: unknown function: random" "apiVersion"="v1" "kind"="Secret" "name"="test-secret-ns1" "namespace"="ns1" "policy"="refresh-env-var-in-pods" 
```

I am using api v1 i get this is there any alternate

**Comment by chipzoller** [comment]
Please fix the formatting of your policy so we can read it.

**Comment by Kamalesh-Seervi** [comment]
My usecase is i want to restart my pod whenever a secret is updated.

**Comment by Kamalesh-Seervi** [comment]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: refresh-env-var-in-pods     
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
  - name: refresh-from-secret-env
    match:
      any:
      - resources:
          kinds:
          - Secret
          selector:
            matchLabels:
              kyverno.io/watch: "true"
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: "{{request.namespace}}"
      patchStrategicMerge:
        spec:
          template:
            metadata:
              annotations:
                corp.org/random: "{{ random('[0-9a-z]{8}') }}"
            spec:
              containers:
              - env:
                - valueFrom:
                    secretKeyRef:
                      <(name): "{{ request.object.metadata.name }}"
```
When i use this i get the below error

```
I0812 18:11:24.371383       1 resource.go:53] background "msg"="fetched trigger resource"  "resourceSpec"={"apiVersion":"v1","kind":"Secret","namespace":"ns1","name":"test-secret-ns1"}
E0812 18:11:24.385963       1 update_request_controller.go:322] background "msg"="" "error"="failed to mutate existing resource, rule response3: variable substitution failed: failed to resolve random('[0-9a-z]{8}') at path /mutate/patchStrategicMerge/spec/template/metadata/annotations/corp.org/random: JMESPath query failed: unknown function: random" "apiVersion"="v1" "kind"="Secret" "name"="test-secret-ns1" "namespace"="ns1" "policy"="refresh-env-var-in-pods"
```
