### DISCUSSION TITLE
Policies being enforced despite being in `Audit` mode

### DISCUSSION THREAD

**Discussion by kirkpabk** [kyverno/policies#716] [Q&A]
### Kyverno Version

1.9.x

### Kubernetes Version

1.22.x

### Kubernetes Platform

K3d

### Description

Understanding that 1.9.2 is not fully "supported", would there be any reason to cause a basic Audit only policy from your default kyverno/policies samples to be Enforced?   In other words, it seems that policies set to Audit are Enforced regardless.  Example: disallow-privilege-escalation

### Steps to reproduce

1. Enabled disallow-privilege-escalation policy as is.
2. Helm install containing a busybox for inits (e.g., sonarqube)
3. Postgres DB failed to init due to securityContext.allowPrivilegeEscallation must be set to 'false'
4. But it shows a Warning PolicyViolation, but is still blocking as an validationFailureAction: Audit??

### Expected behavior

Allowed action, but showing the warning.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
The policy must be in enforce mode as it's not possible for an audit-mode policy to produce this result. You could have multiple policies in play here. Check across the entire cluster with the command `kubectl get cpol,pol -A -o wide`

**Comment by kirkpabk** [comment]
@chipzoller -- absolutely agree.    I saw that they were audits but had to re-apply via source control since I had removed them temporarily to get through the current install.  

clusterpolicy.kyverno.io/disallow-privilege-escalation              true         Audit                              true    16s   1          0        0          0
clusterpolicy.kyverno.io/disallow-privileged-containers             true         Audit                              true    18s   1          0        0          0

But had the same result on the install.   Was being blocked on privileged-containers, check-for-labels, require-drop-all, check-seccomp-strict, run-as-non-root, and require-ro-rootfs.     We don't have all of the policies enabled, but everything is in audit for now.   I verified in source control.  I verified by the command you provided.   Strange, I know, but SonarQube certainly will not run the init pods with those policies applied in Audit.

 Here's the default one "described" but includes the excludes for kube-system and kyverno which we secure differently:

The policy:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Status - for review 
            
      Privilege escalation...
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: privilege-escalation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation,
          and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to false.
        pattern:
          spec:
            =(ephemeralContainers):
            - securityContext:
                allowPrivilegeEscalation: "false"
            =(initContainers):
            - securityContext:
                allowPrivilegeEscalation: "false"
            containers:
            - securityContext:
                allowPrivilegeEscalation: "false"
      # Adding an explicit exclude for certain namespaces 
      # until we have the desired outcomes and expectations with new policies.
      exclude: 
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
```


The described result:
```
kubectl describe cpol disallow-privilege-escalation
Name:         disallow-privilege-escalation
Namespace:
Labels:       <none>
Annotations:  kyverno.io/kubernetes-version: 1.22-1.23
              kyverno.io/kyverno-version: 1.6.0
              policies.kyverno.io/category: Pod Security Standards (Restricted)
              policies.kyverno.io/description:
                Status - for review

                Privilege escalation....
              policies.kyverno.io/severity: medium
              policies.kyverno.io/subject: Pod
              policies.kyverno.io/title: Disallow Privilege Escalation
API Version:  kyverno.io/v1
Kind:         ClusterPolicy
Metadata:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    API Version:  kyverno.io/v1
    Fields Type:  FieldsV1
    Manager:         kyverno
    Operation:       Update
    Subresource:     status
Spec:
  Background:  true
  Rules:
    Exclude:
      Any:
        Resources:
          Namespaces:
            kube-system
            kyverno
    Match:
      Any:
        Resources:
          Kinds:
            Pod
    Name:  privilege-escalation
    Validate:
      Message:  Privilege escalation is disallowed. The fields spec.containers[*].securityContext.allowPrivilegeEscalation, spec.initContainers[*].securityContext.allowPrivilegeEscalation, and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation must be set to 'false'.
      Pattern:
        Spec:
          =(ephemeralContainers):
            Security Context:
              Allow Privilege Escalation:  false
          =(initContainers):
            Security Context:
              Allow Privilege Escalation:  false
          Containers:
            Security Context:
              Allow Privilege Escalation:  false
  Validation Failure Action:               Audit
Status:
  Autogen:
    Rules:
      Exclude:
        Any:
          Resources:
            Namespaces:
              kube-system
              kyverno
        Resources:
      Generate:
        Clone:
        Clone List:
      Match:
        Any:
          Resources:
            Kinds:
              DaemonSet
              Deployment
              Job
              StatefulSet
              ReplicaSet
              ReplicationController
        Resources:
      Mutate:
      Name:  autogen-privilege-escalation
      Validate:
        Message:  Privilege escalation is disallowed. The fields spec.containers[*].securityContext.allowPrivilegeEscalation, spec.initContainers[*].securityContext.allowPrivilegeEscalation, and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation must be set to 'false'.
        Pattern:
          Spec:
            Template:
              Spec:
                =(ephemeralContainers):
                  Security Context:
                    Allow Privilege Escalation:  false
                =(initContainers):
                  Security Context:
                    Allow Privilege Escalation:  false
                Containers:
                  Security Context:
                    Allow Privilege Escalation:  false
      Exclude:
        Any:
          Resources:
            Namespaces:
              kube-system
              kyverno
        Resources:
      Generate:
        Clone:
        Clone List:
      Match:
        Any:
          Resources:
            Kinds:
              CronJob
        Resources:
      Mutate:
      Name:  autogen-cronjob-privilege-escalation
      Validate:
        Message:  Privilege escalation is disallowed. The fields spec.containers[*].securityContext.allowPrivilegeEscalation, spec.initContainers[*].securityContext.allowPrivilegeEscalation, and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation must be set to `false`.
        Pattern:
          Spec:
            Job Template:
              Spec:
                Template:
                  Spec:
                    =(ephemeralContainers):
                      Security Context:
                        Allow Privilege Escalation:  false
                    =(initContainers):
                      Security Context:
                        Allow Privilege Escalation:  false
                    Containers:
                      Security Context:
                        Allow Privilege Escalation:  false
  Conditions:
    Message:
    Reason:                Succeeded
    Status:                True
    Type:                  Ready
  Ready:                   true
  Rulecount:
    Generate:      0
    Mutate:        0
    Validate:      1
    Verifyimages:  0
Events:
  Type     Reason           Age                     From          Message
  ----     ------           ----                    ----          -------
  .
  .
  Warning  PolicyViolation  7m59s                   kyverno-scan  Pod a1/busybox: [privilege-escalation] fail
  Warning  PolicyViolation  7m55s                   kyverno-scan  Pod sonarqube/sonarqube-postgresql-0: [privilege-escalation] fail
  .
  .
````

So, even though it only shows Warning.  The failed actions could not continue until the policy was removed.   Which I thought was strange.

**Comment by chipzoller** [comment]
How do I reproduce this on my end?

**Comment by kirkpabk** [comment]
1.  Applied the policy

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Status - for review 
            
      Privilege escalation...
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: privilege-escalation
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation,
          and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to false.
        pattern:
          spec:
            =(ephemeralContainers):
            - securityContext:
                allowPrivilegeEscalation: "false"
            =(initContainers):
            - securityContext:
                allowPrivilegeEscalation: "false"
            containers:
            - securityContext:
                allowPrivilegeEscalation: "false"
      # Adding an explicit exclude for certain namespaces 
      # until we have the desired outcomes and expectations with new policies.
      exclude: 
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
```
2.  Follow sonarqube install instructions, [here](https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/deploy-on-kubernetes/deploy-sonarqube-on-kubernetes/#:~:text=Currently%2C%20only%20Helm%203%20is%20supported.%20To%20install,sonarqube%20helm%20upgrade%20--install%20-n%20sonarqube%20sonarqube%20sonarqube%2Fsonarqube)
3. Instructions are explicit regarding Pod Security Levels for Basic and Restricted.   Even though they're marked as Audit, it seems to still be blocked.
4. Check with 

`kubectl describe cpol disallow-privilege-escalation`

Strange if I'm the only one seeing this--perhaps I'll rebuild on another machine to duplicate...
