### ISSUE TITLE
[Bug] PolicyException for a pod with multiple violations

### ISSUE THREAD

**Issue by erkerb4** [kyverno/policies#1017]
### Kyverno Version

1.12

### Kubernetes Version

1.28

### Kubernetes Platform

Bare metal

### Description

Hello everyone!

I am running Kyverno v1.12.1, and trying to create PolicyException object for a given deployment by following [PolicyExceptions documentation](https://kyverno.io/docs/writing-policies/exceptions/) page.

I am using Kyverno policy to apply Pod Security Standard profile. I am attempting to create a PolicyException for a deployment that has many (five) violations, but I am not getting far. After creating the PolicyException object, the PolicyReport continues to show failures for Pod.

Details in the reproduce section. 

### Steps to reproduce

Here are the object I've created:

<details>
  <summary>ClusterPolicy for PSS </summary>
  
```yaml
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-security-standards
spec:
  background: true
  validationFailureAction: Audit
  rules:
  - name: restricted
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      podSecurity:
        level: restricted
        version: latest
```
</details>

This is straight out of the documentation, with the only change being `validationFailureAction: Audit`. 

Here is a an example of a Pod that has policy violations:

<details>
  <summary>Pod</summary>
  
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: promtail-djwbc
  namespace: promtail
spec:
  containers:
  - args:
    - -config.file=/etc/promtail/promtail.yaml
    - -config.expand-env=true
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: LOKI_GATEWAY_USERNAME
      valueFrom:
        secretKeyRef:
          key: gateway_user
          name: loki-gateway-auth
    - name: LOKI_GATEWAY_PASSWORD
      valueFrom:
        secretKeyRef:
          key: gateway_password
          name: loki-gateway-auth
    image: grafana/promtail:2.9.3
    imagePullPolicy: IfNotPresent
    name: promtail
    ports:
    - containerPort: 3101
      name: http-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /ready
        port: http-metrics
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 250m
        memory: 450Mi
      requests:
        cpu: 100m
        memory: 250Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/promtail
      name: config
    - mountPath: /run/promtail
      name: run
    - mountPath: /var/lib/docker/containers
      name: containers
      readOnly: true
    - mountPath: /var/log/pods
      name: pods
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2v4bw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsGroup: 0
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: promtail
  serviceAccountName: promtail
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - name: config
    secret:
      defaultMode: 420
      secretName: promtail
  - hostPath:
      path: /run/promtail
      type: ""
    name: run
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: containers
  - hostPath:
      path: /var/log/pods
      type: ""
    name: pods
  - name: kube-api-access-2v4bw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
</details>

This pod violates about five policies. Here is a [playground link](https://playground.kyverno.io/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFSPwI44ovDAkIAtAVEAjPKKg5reHJItwp/beTQkDKoSxCQEWiQ6OpCwcDAejNR0eAzMECwhEi4UAEoeEl4%2B5LL85ADKpuaWCOWqAmh4xn7RcnEJSfRMrHAaOADmEHgIFCXllRZWADTkAKIA0mXkAEL5xXho3vAezeQx8PEEibSdaSwmydUUyvwwooo7HSld6Y8M1slEpBTsjAAcjAAGHZ7NqHV7PFiKPgfULfP6Ah7HJ6nSgOegqDzvfCfMjkTggH4AJgALPjga0DkdkqlWHZ7AArUwSEYQXyRKIgyng078DxwCxgEJfcgAPmsOx0ABUABY4cjuTzwIpgPAQABmMBc5HV5AksuKrLGZgmNTKdXUjQI0wA7tL4NLyDACI6SHAxEQ6Nq1RLdfr7GgTLASHKVerNThpk7/OQ4NAXJtSF7/FAoL65YoIJIYxBFBnIrGSBq%2BuYNKECD69RoYwFyPY5apKDhIhIIOQTMa5SVDst%2BnwSHw%2BuRrZYHXMkQxyD9ftMa02Qu5dqqNS4fYo0DU6/4CEQ%2BsHSi20zH3VI8L7VaI%2Bg60G2B1qnC5GOQZVGQTUC0XzB40z6FQUlThSlDZd62lc9L0PKBeizGFEx1PVO0NCpjWqWoAgtYwj3EE8hxgXlGG4AgwFMCIdH9OBKD6c8BAoApRBwPwaDQWB1CFEgADE0E1T8AEEE1xNBRBuCQ/HvDwSPIaxdH0HAKF/QoAJ2NcJDgaVxKifwSGGH1JIVCBzDgMSfXU3gBHCIyokkkodkY5jejUjlWSQqorHs9SXDoKBZPyeS2XU9SYNxSCpEkEBJhAXT9JwFAQGsWLuAwbBsVhcgOG4EzBANNllFUFi0HEvQDEXHNVE1ax%2BHpa17DgPwCo8MANhkorFBKqACKIuBxILErg0IcTJIaPozPZHRJOsd8YD6RhgIAXhYFQ4BYUNms4qBFtVZbNUYBB9Fa4aJIk8bJpwAAPeqBGsJsaGm2j6L2y77Mk2qKAACQAeTKSUADluIAWRmH0bLotj1tcqINRwKB%2BDyNVQfUhLcEIZLUr2vzyHByHpA0VS23axgGF5T7pJ2R7pIoAAZV65gASQAfQAcW4yUZgAdW4gBNGmAFUyhmHJvr%2BgGmKBkHzPbdwJDmHAEGh2GokbYZyD6XprXXGnxHwcydCe8goAgXhrCVqQVZsAS9WJqTCop6n6cZln2Zp6RuLKMpmdenIABFBbEHBgZzWWxZUSXpZwGHNaoKWKENnBjZp%2Brt2tQZfNRqJtd1/Wo%2BN6xTelHYYDXPpGsotA1QCNA1uKlbkEJRgAE5GAAZlz/OcGkZwoFkWIFaptVPogCRpAVOcdm1paWvJPAJCG9TJK6zietkCeKHr9gAS4FGLca6UJAkMBrGyrxy3X0MW1jTynyEaQdncNQ%2BA8AgB4gOtQZLrj3BlBVpWgDKAFYfS3ne6YqFlvVPUFAWDX34AodeLRF7kH/rvfe8BD7JzbCpHAhVnqSklJfdefBLAwCYu7CG64kKkGMN8IER98DEH4KQ0yFCfR2DgAZbc78PCf0ht8CseccB6QkHQ8hk4r4eD0ngFhoNYBQknrLOAYBRAUEJN/AE9xoHkGUBmIYFBiRKJ%2BjAH8OAACOdFJBT2TrI%2BRk4ATKPMuowYCtFEAl0TsdszkEBCFIFIY6zIfRMV1taAeMAaDhgLjMAgPQgrJRLlAEwPoej1XsJqfBhlVH8FVGAWWkluJkzJvotQr0SBQGlhAPubFwwEAQJIdBNEnC3XUieKEehWI/TvmgAumNQHkBYLyGgGR8ANNLKQawus%2Bg7HqXwAZJBmnblaS3VoCtSkrj2jQaAdwcA/T0iQaR5sMyiE2e07Gc1lLlw2rtVG2tDrbI2f3LGYCnAkGOWPde2s7mXN2dcjpbAGgsFgPYLpEByL4BYLPW%2BhAfTnI8XPbEuT%2BD5MKdUuiry9k3M6YxPA3yIB9EWqyZBfkR7YuhbChWN1EXvIOai8BuyzimHFgQFgqI6wpAxIcWk%2BAgkGQ2LGN5YLSZUDRFnTAWdmF32sISGgxJ7DWgJQUolNS/D8DCB3eQwhjz4FKYQYS7ImxoHsC4CoeA2U4DJnwSg4RdSyvZCqHA6DBShEVYgEY7hrUSDJhAa0MgLCDGqH4FUxATQUEoToX8DR%2B5zIoNxKAxscVhNlPwZw%2BBCaFV5CXZwEhbBoNjS4PAfgXEmncZsk63i9p3O4gQOm550nkADVEYtBBOYmDwP65xphYyKDAA/YCoMrBEVyG8nhRDk1QA1ToetBreKcs2YYdajzh2sq2GOq5CbGqjxWn4MZjTQhloatIahjlTBkNNfXKtLZM0TNMZJEOaomQUF7mUdNcaHgR10KyVwqoHz0vRMFU4a5KlZr2hAIi6wWwNtmMdJ0k8/DnrVJe7w16IC3pjfeva8sKD4xfdAHAiQ0SMs/d0Dxr7rBgEgsGHY/78AaEGBQGYoGTEQfIBeq95Be5UcqFIB9CtUOYYZcGHD6QghuBwGoKB6lSOAYoyBsDOLIPQeZIxiAzGzCsaQ4%2Bjj77sMJFYLs6%2BKltWLOEwB8jwGqMSdo/RmDsn4MAUQ8ZZTz7OMfvU%2BkG4BBKAEYVHYdwJH9NAco9R8D7IpMMZvXe3TcsbN4VU9xhzkJ0F2Nc3fT8nmyPefEzR/zdGoOBbg8F2poX2O2Yi0y04mB%2BBxe3Alv9XmxNGdSyNdL0nYMWYzTlnQyGn3haw5F5l6RdnRss5BHVzXtSVcM75nFyyxDKDPRvCgFy9oB0LajJNAlB3rN5FowkVb1LzcXZOiumpaOf0kPs0GICDl3IeSu9eXbGpkhAMPHlLy0uHdJSd5Fny0U/L%2BQCtFwKeo4rqQgbteI7t3b2uCzZkLQVPczC9n0p2wHkuGVipoV3Ac3ZB/dwqRhJPTd5XWflMBBUsIICKsVErgSqkZN4ACoMlsptW41YkG3GGiPEdpNss6DLzreZKPWTZZY6BOpgQDoQBEHoAGwAgAOxh3h7qPnJB2eHR%2BhgAXjopCKFMSgySrWeiMH5EOlBHJkV64N2HbW763DFNTabie7P%2BCupICrRo3FpBUzV5YdBWvk6SXRlDEOau4aYARjiCgyMjd%2BT98dtRKg1AaDQHjaShEGph2iMi2qyeDKhRAF/PIBBWdRVQNnswkgcx54L/2vBrECDRWLyqvA5fIo16L2FE6BkbWkGbyAEAABfIAA==). I realized that Playground is running Kyverno 1.11, and I was unable to test out the PolicyException object due to older version of API spec.

I created the following `PolicyExceptions` object for the violations:

<details>
  <summary>Policy Exception</summary>
  
```yaml
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: promtail-exceptions
  namespace: kyverno
spec:
  exceptions:
  - policyName: pod-security-standards
    ruleNames:
    - restricted
  match:
    any:
    - resources:
        namespaces:
        - promtail
  podSecurity:
  - controlName: "Volume Types"
    restrictedField: spec.volumes[*]
    values:
      - "spec.volumes[*].hostPath"
  - controlName: "HostPath Volumes"
    restrictedField: spec.volumes[*].hostPath
    values:
      - "/run/promtail"
      - "/var/log/pods"
      - "/var/lib/docker/containers"
  - controlName: "Running as Non-root"
    restrictedField: spec.securityContext.runAsNonRoot
    values:
      - "true"
  - controlName: "Running as Non-root"
    restrictedField: spec.containers[*].securityContext.runAsNonRoot
    values:
      - "true"
  - controlName: "Running as Non-root user"
    restrictedField: spec.securityContext.runAsUser
    values:
      - "0"
```
</details>

Even after creating the PolicyException object, the next time the Pod is restarted, it is reporting violations:

<details>
  <summary>Policy Exception</summary>
  
```yaml
apiVersion: wgpolicyk8s.io/v1alpha2
kind: PolicyReport
metadata:
  name: 58a7af12-5ad9-4e72-ba26-6065b3f82503
  namespace: promtail
results:
- message: 'Validation rule ''restricted'' failed. It violates PodSecurity "restricted:latest":
    (Forbidden reason: runAsUser=0, field error list: [spec.securityContext.runAsUser
    is forbidden, forbidden values found: 0])(Forbidden reason: hostPath volumes,
    field error list: [spec.volumes[1].hostPath is forbidden, forbidden values found:
    /run/promtail, spec.volumes[2].hostPath is forbidden, forbidden values found:
    /var/lib/docker/containers, spec.volumes[3].hostPath is forbidden, forbidden values
    found: /var/log/pods])(Forbidden reason: restricted volume types, field error
    list: [spec.volumes[1].hostPath: Forbidden, spec.volumes[2].hostPath: Forbidden,
    spec.volumes[3].hostPath: Forbidden])'
  policy: pod-security-standards
  properties:
    controls: hostPathVolumes,restrictedVolumes,runAsNonRoot,runAsUser
    standard: restricted
    version: latest
  result: fail
  rule: restricted
  scored: true
  source: kyverno
  timestamp:
    nanos: 0
    seconds: 1715965276
scope:
  apiVersion: v1
  kind: Pod
  name: promtail-djwbc
  namespace: promtail
summary:
  error: 0
  fail: 1
  pass: 0
  skip: 0
  warn: 0
  ```
</details>

### Expected behavior

I expect that after creating the necessary PolicyExceptions, the PolicyReport would not show a failure. 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by erkerb4** [comment]
I've also attempted to use the following variations of the PolicyException objects:

<details>
  <summary>Policy Exception variation 2</summary>
  
```yaml
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: promtail-exceptions
  namespace: kyverno
spec:
  exceptions:
  - policyName: pod-security-standards
    ruleNames:
    - restricted
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - promtail
  podSecurity:
  - controlName: "Volume Types"
    restrictedField: spec.volumes[*]
    values:
      - "spec.volumes[*].hostPath"
  - controlName: "HostPath Volumes"
    restrictedField: spec.volumes[*].hostPath
    values:
      - "/run/promtail"
      - "/var/log/pods"
      - "/var/lib/docker/containers"
  - controlName: "Running as Non-root"
    restrictedField: spec.securityContext.runAsNonRoot
    values:
      - "true"
  - controlName: "Running as Non-root"
    restrictedField: spec.containers[*].securityContext.runAsNonRoot
    values:
      - "true"
  - controlName: "Running as Non-root user"
    restrictedField: spec.securityContext.runAsUser
    values:
      - "0"
```
</details>

<details>
  <summary>Policy Exception variation 3</summary>
  
```yaml
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: promtail-exceptions
  namespace: promtail
spec:
  exceptions:
  - policyName: pod-security-standards
    ruleNames:
    - restricted
  match:
    any:
    - resources:
        kinds:
        - Pod
  podSecurity:
  - controlName: "Volume Types"
    restrictedField: spec.volumes[*]
    values:
      - "spec.volumes[*].hostPath"
  - controlName: "HostPath Volumes"
    restrictedField: spec.volumes[*].hostPath
    values:
      - "/run/promtail"
      - "/var/log/pods"
      - "/var/lib/docker/containers"
  - controlName: "Running as Non-root"
    restrictedField: spec.securityContext.runAsNonRoot
    values:
      - "true"
  - controlName: "Running as Non-root"
    restrictedField: spec.containers[*].securityContext.runAsNonRoot
    values:
      - "true"
  - controlName: "Running as Non-root user"
    restrictedField: spec.securityContext.runAsUser
    values:
      - "0"
```
</details>

**Comment by chipzoller** [comment]
You only need to specify the control names:

```yaml
  podSecurity:
  - controlName: "Volume Types"
  - controlName: "HostPath Volumes"
  - controlName: "Running as Non-root"
  - controlName: "Running as Non-root"
  - controlName: "Running as Non-root user"
```

Here is the Policy Report result of your Pod (I used the `default` Namespace) after creating the PolicyException:

```yaml
apiVersion: wgpolicyk8s.io/v1alpha2
kind: PolicyReport
metadata:
  creationTimestamp: "2024-05-17T19:19:21Z"
  generation: 3
  labels:
    app.kubernetes.io/managed-by: kyverno
  name: 5a3afc40-f471-4bb2-b1b1-187ce31ce056
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: promtail-djwbc
    uid: 5a3afc40-f471-4bb2-b1b1-187ce31ce056
  resourceVersion: "921422"
  uid: 6b2c1d8a-233b-4933-945f-d0a255b85bdd
results:
- message: rule skipped due to policy exception kyverno/promtail-exceptions
  policy: pod-security-standards
  properties:
    exception: promtail-exceptions
  result: skip
  rule: restricted
  scored: true
  source: kyverno
  timestamp:
    nanos: 0
    seconds: 1715973915
scope:
  apiVersion: v1
  kind: Pod
  name: promtail-djwbc
  namespace: default
  uid: 5a3afc40-f471-4bb2-b1b1-187ce31ce056
summary:
  error: 0
  fail: 0
  pass: 0
  skip: 1
  warn: 0
```

**Comment by erkerb4** [comment]
@chipzoller  - Thank you for your response. I guess I am a bit confused. When I was following the [linkerd](https://kyverno.io/blog/2024/02/04/securing-services-meshes-easier-with-kyverno/), the example encourages using more filtering (which i agree with). Here is the example for linkerd:

```yaml
      validate:
        podSecurity:
          level: baseline
          version: latest
          exclude:
            - controlName: Capabilities
              images:
                - "*/istio/proxyv2*"
                - "*/linkerd/proxy-init*"
              restrictedField: spec.initContainers[*].securityContext.capabilities.add
              values:
                - NET_ADMIN
                - NET_RAW
```
I understand that rules does not require further filterin. But I am now curious as to.. why?
