### ISSUE TITLE
restrict-seccomp policy does not comply with Pod Security Standards (Restricted)

### ISSUE THREAD

**Issue by sotoiwa** [kyverno/policies#102]
The Restricted profile in the Pod Security Standards requires that the Seccomp profile be specified, and does not allow it to be unspecified, but the kyverno's [restrict-seccomp](https://github.com/kyverno/policies/blob/main/pod-security/restricted/restrict-seccomp/restrict-seccomp.yaml) policy allows it to be unspecified.

**Comment by realshuting** [comment]
Hi @sotoiwa - can you point me to where PSS requires Seccomp profile?

**Comment by JimBugwadia** [comment]
@realshuting - please check here: https://kubernetes.io/docs/concepts/security/pod-security-standards/ (search for Seccomp)

Looks like there is Kubernetes version specific information now, which we will need to update to:

```
Seccomp profile must not be explicitly set to Unconfined.

Restricted Fields

spec.securityContext.seccompProfile.type
spec.containers[*].securityContext.seccompProfile.type
spec.initContainers[*].securityContext.seccompProfile.type
spec.ephemeralContainers[*].securityContext.seccompProfile.type
Allowed Values

Undefined/nil
RuntimeDefault
Localhost
```


```
Seccomp profile must be explicitly set to one of the allowed values. Both the Unconfined profile and the absence of a profile are prohibited.

Restricted Fields

spec.securityContext.seccompProfile.type
spec.containers[*].securityContext.seccompProfile.type
spec.initContainers[*].securityContext.seccompProfile.type
spec.ephemeralContainers[*].securityContext.seccompProfile.type
Allowed Values

RuntimeDefault
Localhost
The container fields may be undefined/nil if the pod-level spec.securityContext.seccompProfile.type field is set appropriately. Conversely, the pod-level field may be undefined/nil if _all_ container- level fields are set.
```

**Comment by chipzoller** [comment]
Thanks for bringing this to our attention @sotoiwa. I have built an updated version of this policy to conform to the latest standards. Please try it out and ensure it works correctly. A couple things:

* It is set to `enforce` right now
* ephemeralContainers is not being checked because this is still an alpha feature in v1.22
* The test resources in kyverno/policies for this sample have a couple bugs. They will be updated with many more alongside this new policy.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-seccomp
  annotations:
    policies.kyverno.io/title: Restrict Seccomp
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The runtime default seccomp profile must be required, or only specific
      additional profiles should be allowed. This policy, requiring Kubernetes
      v1.19 or later, ensures that only the `RuntimeDefault` or `Localhost` is
      used as a `type` and that it is not unset.
spec:
  background: true
  validationFailureAction: enforce
  rules:
  - name: restrict-seccomp
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: >-
        Use of custom Seccomp profiles is disallowed. The fields
        spec.securityContext.seccompProfile.type,
        spec.containers[*].securityContext.seccompProfile.type, and
        spec.initContainers[*].securityContext.seccompProfile.type
        must be set to `RuntimeDefault` or `Localhost`.
      anyPattern:
      - spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault | Localhost"
      - spec:
          containers:
          - securityContext:
              seccompProfile:
                type: "RuntimeDefault | Localhost"
  - name: restrict-seccomp-initcontainers
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: >-
        Use of custom Seccomp profiles is disallowed. The fields
        spec.securityContext.seccompProfile.type,
        spec.containers[*].securityContext.seccompProfile.type, and
        spec.initContainers[*].securityContext.seccompProfile.type
        must be set to `RuntimeDefault` or `Localhost`.
      anyPattern:
      - spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault | Localhost"
      - spec:
          =(initContainers):
          - securityContext:
              seccompProfile:
                type: "RuntimeDefault | Localhost"
```

**Comment by chipzoller** [comment]
All of these Pod resources should fail validation:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-spec-undefined
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: seccomp
    image: busybox
    command: ["sleep", "9999"]
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-spec-unconfined
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: Unconfined
  containers:
  - name: seccomp
    image: busybox
    command: ["sleep", "9999"]
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-cont-undefined
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: seccomp
    image: busybox
    command: ["sleep", "9999"]
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-cont1-unconfined
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: seccomp
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: Unconfined
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-cont2-inconsistent
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: seccomp00
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  - name: seccomp01
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: Unconfined
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-cont2-inconsistent1
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: seccomp00
    image: busybox
    command: ["sleep", "9999"]
  - name: seccomp01
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-initcont-undefined
spec:
  securityContext:
    runAsNonRoot: true
  initContainers:
  - name: initseccomp
    image: busybox
    command: ["sleep", "9999"]
  containers:
  - name: seccomp
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod-initcont-unconfined
spec:
  securityContext:
    runAsNonRoot: true
  initContainers:
  - name: initseccomp
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: Unconfined
  containers:
  - name: seccomp
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      seccompProfile:
        type: RuntimeDefault
```
