### ISSUE TITLE
[Bug] ClusterCleanupPolicy works only the first time ?

### ISSUE THREAD

**Issue by amoscatellialmaviva** [kyverno/policies#1053]
### Kyverno Version

1.12

### Kubernetes Version

1.28

### Kubernetes Platform

VMware Tanzu (specify in description)

### Description

For some strange reason my ClusterCleanupPolicy seems to be applied only once ...

Here are my yamls :

```
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: mutate-pod-binding
spec:
  background: false
  rules:
    - name: mutate-pod-binding
      match:
        any:
        - resources:
            kinds:
            - Pod/binding
            namespaces:
            - shm
            - device-manager
            - p3p
      context:
      - name: node
        variable:
          jmesPath: request.object.target.name
          default: ''
      - name: assetCode
        apiCall:
          urlPath: "/api/v1/nodes/{{node}}"
          jmesPath: "metadata.labels.\"asset-code\" || 'empty'"
      - name: assetName
        apiCall:
          urlPath: "/api/v1/nodes/{{node}}"
          jmesPath: "metadata.labels.\"asset-name\" || 'empty'"
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              asset-code: "{{ assetCode }}"
              asset-name: "{{ assetName }}"
              asset: "initialized"
---
apiVersion: kyverno.io/v2beta1
kind: ClusterCleanupPolicy
metadata:
  name: cleandeploy
spec:
  match:
    any:
    - resources:
        kinds:
          - Pod
        namespaces:
        - shm
        - device-manager
        - p3p
  exclude:
    any:
    - resources:
        annotations:
          asset: "initialized"
  schedule: "*/1 * * * *"
```

I can see it has been started the first time : 

```
Normal  PolicyApplied  12m   kyverno-cleanup  successfully cleaned up the target resource Pod/shm/dfm-5b5578b5d4-wl9tr
```

Yet now I see this :

```
NAME                   READY   STATUS             RESTARTS        AGE
dfm-5b5578b5d4-5247b   0/1     CrashLoopBackOff   7 (97s ago)     14m
```

```
Name:             dfm-5b5578b5d4-5247b
Namespace:        shm
Priority:         0
Service Account:  default
Node:             ec-worker/10.238.3.249
Start Time:       Wed, 19 Jun 2024 11:50:39 +0000
Labels:           app=am
                  pod-template-hash=6c9c85bdd8
Annotations:      data-ingest.dynatrace.com/injected: true
                  dynakube.dynatrace.com/injected: true
                  oneagent.dynatrace.com/injected: true
```

But I can't understand why the ClusterCleanupPolicy is not triggered anymore, and the describe proove it since there are not new events.

If I REDEPLOY the policy it's started an additional times ...

Why ?

### Steps to reproduce

I provided everything in the description

### Expected behavior

I provided everything in the description

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
