### ISSUE TITLE
[Enhancement]  Update CEL policies to make use of optionals and variables to remove redundant expressions

### ISSUE THREAD

**Issue by Chandan-DK** [kyverno/policies#1058]
### Problem Statement

There are redundant expressions in CEL policies that are present in the library. For example, here `container.securityContext` has been repeated multiple times:
``` 
object.spec.containers.all(container, has(container.securityContext) &&
has(container.securityContext.allowPrivilegeEscalation) &&
container.securityContext.allowPrivilegeEscalation == false)
```
Here, we can remove redundant expressions by using optionals:
```
object.spec.containers.all(container, container.?securityContext.?allowPrivilegeEscalation.orValue(true) == false)
```
[CEL Playground](https://playcel.undistro.io/?content=H4sIAAAAAAAAA5VSwWoCMRD9lbAHccHGbouXgEiRHnop0oOnvcxmpzZtdrIkWauU%2FnsTVrIi1dq5zWPeezN5%2Bcok6kxk0ykz1TtKz12LkktDHhShdRy0Hqd2wt7ADS13KDur%2FH4ZENz5nI1GJQWti1NR0nyurNoqjRt8dBI0eGUo0f9PZfM5ewXtMC%2BppOtOGVwWpzaLcz7c2DXoDsfedpgPrtkkq8HDE7WdD8%2FZLyBKYqGgVetgH9iCbYse%2B1BUC7Yydd826CHyDwzGCBoUrIK6NXUx69F4ThpQpPwynZbgUDcHcpxIJ94WRxOB3cAm6nduX5mdKPj97E%2BFu2sV5K9rJdVzO12SPMnnSNd29OCeDb0Y40UfRsiiMTWGGOLf%2Fv4B3UDwNeMCAAA%3D) for the above expressions.

Also, we can optimize some CEL policies by using `variables`. [Example](https://github.com/kyverno/policies/blob/a1b8992d44d5704c445a483758a9a091cee110a6/other-cel/restrict-escalation-verbs-roles/restrict-escalation-verbs-roles.yaml#L30-L36) 

### Solution Description

Update the following CEL policies to make use of optionals and variables to remove redundant expressions.

**Note:**
The below checklist is not exhaustive and more policies will be added here.

#### pod-security-cel
- **baseline:**
  - [ ] #1090
  - [ ] #1091
  - [ ] #1092
  - [ ] #1093
  - [ ] #1094
  - [ ] #1095
  - [ ] #1096
  - [ ] #1097
  - [ ] #1098
  - [ ] #1099
  - [ ] #1100
- **restricted:**
  - [ ] disallow-capabilities-strict: simplify CEL expressions
  - [ ] disallow-privilege-escalation: simplify CEL expressions
  - [ ] require-run-as-nonroot: simplify CEL expressions
  - [ ] require-run-as-non-root-user: simplify CEL expressions
  - [ ] restrict-seccomp-strict: simplify CEL expressions
  - [ ] restrict-volume-types: simplify CEL expressions

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by Chandan-DK** [comment]
cc @JimBugwadia @MariamFahmy98

**Comment by JimBugwadia** [comment]
So, using these techniques we can simply a policy like this:

https://kyverno.io/policies/pod-security-cel/restricted/require-run-as-nonroot/require-run-as-nonroot/

```yaml
      validate:
        cel:
          expressions:
            - expression: >-
                (
                    (
                      has(object.spec.securityContext) &&
                      has(object.spec.securityContext.runAsNonRoot) &&
                      object.spec.securityContext.runAsNonRoot == true
                    ) && (
                      (
                          object.spec.containers +
                          (has(object.spec.initContainers) ? object.spec.initContainers : []) +
                          (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : [])
                      ).all(container,
                          !has(container.securityContext) ||
                          !has(container.securityContext.runAsNonRoot) ||
                          container.securityContext.runAsNonRoot == true)
                    )
                ) || (
                    (
                        object.spec.containers +
                        (has(object.spec.initContainers) ? object.spec.initContainers : []) +
                        (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : [])
                    ).all(container,
                        has(container.securityContext) &&
                        has(container.securityContext.runAsNonRoot) &&
                        container.securityContext.runAsNonRoot == true)
                )  

```

to:

```yaml
      validate:
        cel:
          variables:
          - name: ctnrs
            expression: >-
              object.spec.containers +
              (has(object.spec.initContainers) ? object.spec.initContainers : []) +
              (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : [])
          expressions:
            - expression: >-
                (object.spec.?securityContext.?runAsNonRoot.orValue(false) == true
                  && variables.ctnrs.all(c, c.?securityContext.?runAsNonRoot.orValue(true) == true))
                  || variables.ctnrs.all(c, c.?securityContext.?runAsNonRoot.orValue(false) == true)
```
