### ISSUE TITLE
Block Large Images

### ISSUE THREAD

**Issue by davvyin** [kyverno/policies#1083]
```yaml
...
deny:
          conditions:
            all:
            - key: {{.Values.comp.comp_require_image_size.size}}
            operator: LessThan
            value: "{{`{{imageSize}}`}}"
```

Here would the operator be `greaterThan`?
