### ISSUE TITLE
[Bug] Generating network policy for existing namespace fails. As well as data template synchronization.

### ISSUE THREAD

**Issue by antonvigo** [kyverno/policies#1123]
### Kyverno Version

1.11

### Kubernetes Version

1.25

### Kubernetes Platform

Other (specify in description)

### Description

Hey colleagues!
There is HuaweiCloud CCE cluster, Kyverno 1.11.5 is on board. Helm chart version is 3.1.5. 

I defined generate-policy with data-template to add networkPolicy
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno-policies
    meta.helm.sh/release-namespace: kyverno-policies
  name: network-policy-isolated-ns
spec:
  background: false
  generateExisting: true
  rules:
    - name: pod-from-isolated-ns
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Namespace
              operations:
                - CREATE
                - UPDATE
              selector:
                matchLabels:
                  network-policy: isolated-ns
      generate:
        synchronize: true
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: isolated-ns
        namespace: '{{ request.namespace }}'
        data:
          metadata:
            labels:
              created-by: kyverno
          spec:
            egress:
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: '{{ request.namespace }}'
                  - ipBlock:
                      cidr: 10.247.0.0/16
              - ports:
                  - port: 53
                    protocol: UDP
                to:
                  - namespaceSelector: {}
                  - ipBlock:
                      cidr: 192.168.22.1/32
                  - ipBlock:
                      cidr: 192.168.22.2/32
              - ports:
                  - port: 80
                    protocol: TCP
                  - port: 443
                    protocol: TCP
                to:
                  - ipBlock:
                      cidr: 192.168.22.15/32
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: nginx-ingress-system
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: prometheus-system
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: '{{ request.namespace }}'
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
```

for every namespace (NS) marked with a specific label:
```
apiVersion: v1
kind: Namespace
metadata:
  name: check-np
  labels:
    network-policy: isolated-ns
```

1. For some reason the network policy doesn't appear for existing NS. It means those NS which have been there right before Kyverno's policy.
2. Also I tried to update network policy's template within data section of kyverno-policy expecting the changes to appear in downstream NP resources. With no success.

As far as I've got `spec.generateExisting=true` should solve the first part. And `spec.rules[].generate.synchronize=true` is responsible for the second one. Looks like these actions should be enough in case of out-of-box (default) Kyverno config.

In both cases I got same error from background controller (are specified further).

I would like know if there is some misconfiguration. Is there any workaround in other case?

### Steps to reproduce

1. Deploy Kyverno with corresponding helm-chart
2. Define network policy with proper label
3. Add Kyverno cluster policy
4. Try to change network policy's template

### Expected behavior

Network policy is added and changed in accordance with the template.

### Kyverno logs

```shell
E0812 10:09:41.222970       1 generate.go:378] "failed to apply generate rule" err="the server does not allow this method on the requested resource" logger="background" name="ur-vsrfx" policy="network-policy-isolated-ns" rule="pod-from-isolated-ns" resource="check-np"

I0812 10:09:41.223143       1 event_broadcaster.go:338] "Event occurred" object="network-policy-isolated-ns" kind="ClusterPolicy" apiVersion="kyverno.io/v1" type="Warning" reason="PolicyError" action="None" note="policy network-policy-isolated-ns/pod-from-isolated-ns error: <nil>"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
When you use `operations[]` you shouldn't also use `generateExisting`. My recommendation would be to drop `operation[]` and also not match on Pods here. You're creating a potential conflict with both Pods and Namespaces whereas you really only need Namespace.

**Comment by antonvigo** [comment]
> When you use `operations[]` you shouldn't also use `generateExisting`.

But why? Is it some documented feature? I'm asking because in [docs](https://kyverno.io/docs/writing-policies/match-exclude/) I saw this: _The operations[] list is optional but recommended. When operations[] is absent, the default behavior is to match on CREATE and UPDATE requests._ Anyway, this block was added recently. The problem had been there before that.

> potential conflict with both Pods and Namespaces

Even if I specified 'any'? Actually I tried to remove pods from matching condition. Nothing changed. :(

**Comment by chipzoller** [comment]
Problem is like the `namespace: '{{ request.namespace }}'` line. A Namespace is a cluster-scoped resource. `request.namespace` will only be populated for Namespaced resources.

**Comment by chipzoller** [comment]
Yes, I see that is the case, but `request.namespace` is not populated for CREATE requests and doesn't exist for existing resources either.

**Comment by antonvigo** [comment]
So I left only pods as resources to be matched and replaced '{{ request.namespace }}' with particular namespace name. And it also didn't help.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno-policies
    meta.helm.sh/release-namespace: kyverno-policies
  name: network-policy-isolated-ns
spec:
  background: false
  generateExisting: true
  rules:
    - name: pod-from-isolated-ns
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
              selector:
                matchLabels:
                  network-policy: isolated-ns
      generate:
        synchronize: true
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: isolated-ns
        namespace: check-np
        data:
          metadata:
            labels:
              created-by: kyverno
          spec:
            egress:
              - to:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: check-np
                  - ipBlock:
                      cidr: 10.247.0.0/16
              - ports:
                  - port: 53
                    protocol: UDP
                to:
                  - namespaceSelector: {}
                  - ipBlock:
                      cidr: 192.168.22.1/32
                  - ipBlock:
                      cidr: 192.168.22.2/32
              - ports:
                  - port: 80
                    protocol: TCP
                  - port: 443
                    protocol: TCP
                to:
                  - ipBlock:
                      cidr: 192.168.22.15/32
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: nginx-ingress-system
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: prometheus-system
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: check-np
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
```

Any other thoughts?..
