### ISSUE TITLE
Require Pod Probes

### ISSUE THREAD

**Issue by rubroboletus** [kyverno/policies#113]
After upgrading from 1.3.6 to 1.4.2, this policy starts again firing alert for CronJobs / Jobs (pods created by them). Applied last CRDs, undeployed Kyverno, cleaned up all crds and policies, installed cleanly, still same issue.
Kubernetes EKS 1.21.

**Comment by chipzoller** [comment]
@rubroboletus Can you please test with Kyverno 1.4.3 and see if you have the same issue? If so, please respond here with a test manifest for a CronJob or Job that can be used to verify.

**Comment by rubroboletus** [comment]
@chipzoller tested, still in trouble. Pasting also my Pod Probes Policy, added some exclude logic. But fails even with plain policy from here (also tested).
 ```apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-pod-probes
  namespace: rh-test
  annotations:
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,StatefulSet
    policies.kyverno.io/title: Require Pod Probes
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Liveness and readiness probes need to be configured to correctly manage a Pod's
      lifecycle during deployments, restarts, and upgrades. For each Pod, a periodic
      `livenessProbe` is performed by the kubelet to determine if the Pod's containers
      are running or need to be restarted. A `readinessProbe` is used by Services
      and Deployments to determine if the Pod is ready to receive network traffic.
      This policy validates that all containers have liveness and readiness probes by
      ensuring the `periodSeconds` field is greater than zero.
spec:
  validationFailureAction: audit
  rules:
  - name: validate-livenessProbe-readinessProbe
    exclude:
      any:
      - resources:
             kinds:
             - Pod
             namespaces:
             - tigera-operator
             - calico-system
      - resources:
             kinds:
             - Pod
        clusterRoles:
        - cluster-admin
        subjects:
        - kind: Group
          name: system:masters
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Liveness and readiness probes are required."
      pattern:
        spec:
          containers:
          - livenessProbe:
              periodSeconds: ">0"
            readinessProbe:
              periodSeconds: ">0"
```

```apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: rh-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

job was created from CronJob using simple `kubectl create job --from=cronjob/hello hello-2 -n rh-test --token $RH_TOKEN` command.
That token has RoleBinding "admin" in mentioned namespace, so it will not match the excludes.
Attaching also log from Kyverno pod:
![image](https://user-images.githubusercontent.com/19551186/133962087-2b571116-2579-4557-ad54-17551dbdaeb1.png)

**Comment by chipzoller** [comment]
@rubroboletus A few things I'm seeing

1. This is a `Policy` and not a `ClusterPolicy` which means it's namespaced. The exclude clauses which name other Namespaces aren't valid.
2. You've set `pod-policies.kyverno.io/autogen-controllers` and haven't named `Job` or `CronJob` so the auto-gen controller will not generate a complimentary policy to block Pods emanating from those controllers.
3. `validationFailureAction` is set to `audit` which means it will not block anything even if it were valid, merely report on it.

**Comment by rubroboletus** [comment]
@chipzoller hello, a few things I'm seeing in Kyverno 1.4.3 log, when I try to apply this policy, just changed to ClusterPolicy and action to enforce:

![image](https://user-images.githubusercontent.com/19551186/135209398-45426187-12bd-474e-b091-786692ffad56.png)

you are right, that I was trying to test it fast for you, so used just Policy, to not break all the Kubernetes, used also by other people. I have not full access to fresh, unused EKS all the day. For testing purpose is "audit" better, so it will not break anything. But we need to enforce it on our production environments and currently it's impossible with 1.4.3 because of the parsing problem, already known, with autogen, (spec.rules[1].match ....). and with 1.4.2 mainly because of autogen is generating nothing when used with any/all rules.
But ok, lets test it without any additional controls ...

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-probes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,StatefulSet
    policies.kyverno.io/title: Require Pod Probes
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Liveness and readiness probes need to be configured to correctly manage a Pod's
      lifecycle during deployments, restarts, and upgrades. For each Pod, a periodic
      `livenessProbe` is performed by the kubelet to determine if the Pod's containers
      are running or need to be restarted. A `readinessProbe` is used by Services
      and Deployments to determine if the Pod is ready to receive network traffic.
      This policy validates that all containers have liveness and readiness probes by
      ensuring the `periodSeconds` field is greater than zero.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: validate-livenessProbe-readinessProbe
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Liveness and readiness probes are required."
      pattern:
        spec:
          containers:
          - livenessProbe:
              periodSeconds: ">0"
            readinessProbe:
              periodSeconds: ">0"
              
```
![image](https://user-images.githubusercontent.com/19551186/135212283-0c961bd6-fd38-407c-ba4e-63f76ffbf9d8.png)

so as you can see, pod for this cronjob / job, definition in earlier comment, is not going to be created. CronJob / Job are created without problem. The ClusterPolicy I have used is from sample policies - [https://kyverno.io/policies/best-practices/require_probes/require_probes/](url). The test above was done on 1.4.2. Lets test it also on 1.4.3.
And nothing changed so far, CronJob is created, Job is created, Pod for CronJob / Job is blocked:

![image](https://user-images.githubusercontent.com/19551186/135212930-3304feaf-0540-4726-b874-de9281a3d238.png)
