### ISSUE TITLE
[Question] How to match PATCH requests?

### ISSUE THREAD

**Issue by Da-Juan** [kyverno/policies#1138]
Hi,

I'm looking to create a validate policy to allow users to use `kubectl rollout restart`.
Rollout restart creates a PATCH request that sets the annotation `kubectl.kubernetes.io/restartedAt` on the resources.

I tried with a match on `UPDATE` operations but it doesn't seem to catch PATCH requests.

Do you have any idea if it is possible to create such policy?

Thanks

**Comment by realshuting** [comment]
What resource are you selecting in the policy? Can you share the policy please?

**Comment by Da-Juan** [comment]
I tried to select deployments, statefulsets and daemonsets as we allow patch only on these resources with the RBAC.

Here is the policy I tried:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-patch-to-rollout-restart
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: restrict-patch
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
              operations:
                - UPDATE
            clusterRoles:
              - namespace-owner
      validate:
        message: "PATCH is allowed only for rollout-restarts"
        pattern:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "?*"
```

**Comment by realshuting** [comment]
Does the policy work if you remove this?
```
            clusterRoles:
              - namespace-owner
```

**Comment by Da-Juan** [comment]
I just tried this I can perform a rollout restart on my test deployment but I can also do a `kubectl edit` on the deployment and change the requests/limits for example.

Here is my test deployment manifest:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "32Mi"
            cpu: "500m"
```
