### ISSUE TITLE
Unique Ingress Host sample policy will always validate/deny

### ISSUE THREAD

**Issue by thorstenhuhn** [kyverno/policies#116]
The precondition requires any of two opposite checks which will always be true:

```
any:
  - key: "{{ request.object.spec.rules[].host }}"
    operator: In
    value: "{{ hosts }}"
  - key: "{{ request.object.spec.rules[].host }}"
    operator: NotIn
    value: "{{ hosts }}"
```

As we have a deny rule here, the second condition is the one to be removed.

**Comment by chipzoller** [comment]
@thorstenhuhn apologies for letting this drop off. Have been covered up at work.

The problem that I was attempting to solve with the latter `any` statement was when a single Ingress manifest was submitted that contained at least one colliding host. For example, if you started with the following hosts defined as Ingress resources

```sh
$ k get --raw /apis/networking.k8s.io/v1/ingresses | jp "items[].spec.rules[].host"
[
  "foo.bar.com",
  "www.foo.com"
]
```

and a user submitted the following manifest

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-bad
spec:
  rules:
  - host: "www.github.com"
    http:
      paths:
      - pathType: Prefix
        path: "/git"
        backend:
          service:
            name: service11
            port:
              number: 80
  - host: "www.foo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/asdf"
        backend:
          service:
            name: service22
            port:
              number: 80
```

without that second `any` statement the request would be allowed and it shouldn't be because `www.foo.com` is already present in the cluster. The error I made was in NOT testing a good resource defining a single host. Removing the defective second `any` statement will again re-open up the case where a multi-host Ingress containing a colliding entry is allowed.

I think the best way to fix this policy is to probably use a JMESPath expression with `contains()` but we need the fix in https://github.com/kyverno/kyverno/pull/2346 which should land in 1.4.3. I will try and model a fix using the latest upstream code in hopes of updating the policy for 1.4.3.
