### ISSUE TITLE
[Bug] Unique host and path ingress policy is blocking updates

### ISSUE THREAD

**Issue by Fauli** [kyverno/policies#1163]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

AKS

### Description

I'm refering to https://github.com/kyverno/policies/issues/833

I'm using v1.12.3, and am still facing this issue. Not sure if it was ever resolved?
My policy is the stadard one from the documentation:
https://kyverno.io/policies/other/unique-ingress-host-and-path/unique-ingress-host-and-path/

Upon editing an existing ingress, I face:

unique-ingress-host-and-path:
  check-host-path-combo: 'validation failure: The Ingress host and path combination
    must be unique across the cluster.'
Do you know if this has ever been fixed and tested?

### Steps to reproduce

1.  Create ingress with any host & path combination
2. Update the same ingress
3. Save

### Expected behavior

Save works, ingress is only colloding with itself, so should be fine.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by realshuting** [comment]
Hi @Fauli - we have Chainsaw tests covering this policy https://github.com/kyverno/policies/tree/main/other/unique-ingress-host-and-path/.chainsaw-test.

I tried locally using 1.12.5 and was not able to replicate the issue, I installed the policy, and created the following ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goodingress01
spec:
  rules:
  - host: bar
    http:
      paths:
      - backend:
          service:
            name: demo-svc
            port:
              number: 8080
        path: /foo
        pathType: Prefix
```

And updated the path /foo to /bar, and it went through:
```
$ k edit ingress goodingress01
ingress.networking.k8s.io/goodingress01 edited
```

Please share detailed resource manifests so we can reproduce the issue.
