### ISSUE TITLE
[Bug] Kyverno fails to mutate rules when **match** is set to **and** on  more than one resource

### ISSUE THREAD

**Issue by fallmor** [kyverno/policies#1182]
### Kyverno Version

1.12

### Kubernetes Version

1.28

### Kubernetes Platform

Other (specify in description)

### Description

Kyverno does not trigger change when rules match multiple resources  in the same namespace .

### Steps to reproduce

1. Create a Configmap and a Secret
```
kubectl create cm my-cm --from-literal=enable=true --from-literal=test=ok
kubectl create secret generic my-secret --from-literal=key1=supersecret --from-literal=key2=topsecret
```
2.  Create a Pod
```
kubectl create deployment my-dep --image=busybox
```
3. Create a Kyverno policy
```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: test
spec:
  mutateExistingOnPolicyUpdate: true
  validationFailureAction: Enforce
  rules:
    - name: test-deployment
      match:
        all:
          - resources:
              kinds: ["ConfigMap"]
              names: ["my-cm"]
          - resources:
              kinds: ["Secret"]
              names: ["my-secret"]
      mutate:
        targets:
          - apiVersion: "apps/v1"
            kind: "Deployment"
            name: "my-dep"
        patchesJson6902: |-
          - op: add
            path: "/metadata/labels/changed-by"
            value: "kyverno"
```

### Expected behavior

A new label **changed-by: kyverno** should appear in the deployment metadata

### Kyverno logs

```shell
There are no error/warning logs
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
