### ISSUE TITLE
"Require runAsNonRoot" policy with "initContainers: null"

### ISSUE THREAD

**Issue by jplitza** [kyverno/policies#1197]
The [sample policy Require runAsNonRoot](https://kyverno.io/policies/pod-security/restricted/require-run-as-nonroot/require-run-as-nonroot/) fails with the following Pod spec:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: null-initcontainers
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: alpine:latest
  initContainers:
```

Without the last line (which is equivalent to `initContainers: null`), the policy succeeds.

This situation is common with Helm charts, where list keys are always templated, followed by a loop for the items. It is valid according to the Kubernetes schemas, too.
