### ISSUE TITLE
Policy to prevent `Azurescape`

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#122]
See: https://threatpost.com/azurescape-kubernetes-attack-container-cloud-compromise/169319/

Some ideas to explore:

1. Require BoundServiceAccountTokenVolume

2. Deploy policy enforcers to monitor and prevent suspicious activity within clusters, especially service accounts or nodes that query the SelfSubjectAccessReview or SelfSubjectRulesReview APIs for their permissions.

**Comment by chipzoller** [comment]
Only thing I can extract from this is a policy to require a projected volume for the service account token. Does that align with what you were thinking too?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: build-robot 
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token 
          expirationSeconds: 7200 
          audience: vault 
```

**Comment by chipzoller** [comment]
Any comment?

**Comment by JimBugwadia** [comment]
What about requiring `BoundServiceAccountTokenVolume`?

Another option to explore would be to `bind` a pod with a service account (on create) and not allow the same service account to be used in any other pod i.e. TOFU (https://en.wikipedia.org/wiki/Trust_on_first_use). This would prevent other pods from using privileged service accounts.

**Comment by chipzoller** [comment]
I like both of those ideas. Maybe we can create two separate samples based upon them. Your second idea is also interesting, but would have to figure out a way to still allow multiple replicas access to the same SA.

**Comment by JimBugwadia** [comment]
Yes, that is correct. I think the right binding would be to the pod `image` (in the namespace.) I am wondering if this would also require a feature to mutate existing resources e.g. adding an entry to an existing configmap.

**Comment by chipzoller** [comment]
`image` may be problematic though for Pods with multiple containers and initContainers. Not quite sure what the right approach is for that one. BoundServiceAccountTokenVolume one seems fairly known.

**Comment by chipzoller** [comment]
Still reading up on the Bound SA tokens, but here is a prototype which seems to work for the use case.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ensure-bound-serviceaccount-token-vols
  annotations:
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Bound ServiceAccount tokens limit the scope of permissions for a given ServiceAccount.
      This policy requires that two projected volumes for a ServiceAccount token are found, one
      by created by the ServiceAccount admission controller and the second when a Pod is
      configured to use a bound volume projection.     
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: ensure-bound-serviceaccount-token-vols
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: You must use a projected volume for this ServiceAccount.
      deny:
        conditions:
          all:
          - key: "{{request.object.spec.volumes[*].projected.sources[*].serviceAccountToken[] | length(@)}}"
            operator: LessThan
            value: 2
```

`goodpod.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: dfasfsdfasda
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: build-robot 
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
```

`badpod.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: badpod
spec:
  containers:
  - name: busybox
    image: asdfasfasfasa:1.28
  restartPolicy: Never
```

```sh
$ k apply -f badpod.yaml 
Error from server: error when creating "badpod.yaml": admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Pod/default/badpod was blocked due to the following policies

restrict:
  restricted: You must use a projected volume for this ServiceAccount.
```

@JimBugwadia can you provide feedback on this, please?
