### ISSUE TITLE
[Sample] Mutating Configmaps

### ISSUE THREAD

**Issue by priyanshur-curefit** [kyverno/policies#1230]
### Problem Statement

i want to create a config map mutating policy which replaces any occurance of ap-south-1 to ap-south-2 in the data field of config map. Please help me create a valid policy which does this task

### Solution Description

Using the following policy, which is not working

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-ap-south-1-with-ap-south-2
spec:
  rules:
    - name: replace-region-in-configmap
      match:
        resources:
          kinds:
            - ConfigMap
      mutate:
        foreach:
          - list: "request.object.data | keys(@)"
            patchStrategicMerge:
              data:
                "{{ element }}": "{{ request.object.data[element] | replace('ap-south-1', 'ap-south-2') }}"
```

### Example "Good" Resource

```yaml

```

### Example "Bad" Resource

```yaml

```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
