### ISSUE TITLE
[Bug] How to escape the following policy so it works in helm charts

### ISSUE THREAD

**Issue by cooervo** [kyverno/policies#1238]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

GKE

### Description

Trying to use the following [kyverno policy][1], but haven't been able to escape it properly so it works with helm.

Seems helm escaping `{{}}` conflicts with kyverno escaping

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-probes
  #... 
    preconditions:
      all:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      foreach:
      - list: request.object.spec.containers[]
        deny:
          conditions:
            all:
            - key: livenessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
            - key: startupProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
            - key: readinessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
```

I tried  this which didn't work:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
 #...
      preconditions:
        all:
          - key: '{{ "{{request.operation || 'BACKGROUND'}}" }}'
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      validate:
        message: 'Liveness or readiness probes are required for all containers.'
        foreach:
          - list: '{{ "{{request.object.spec.containers[]}}" }}'
            deny:
              conditions:
                all:
                  - key: livenessProbe
                    operator: AllNotIn
                    value: '{{ "{{ element.keys(@)[] }}" }}'
                  - key: readinessProbe
                    operator: AllNotIn
                    value: '{{ "{{ element.keys(@)[] }}" }}'
```

Tried following [kyvernos documentation for working with helm][2] to no success at all.

  [1]: https://kyverno.io/policies/best-practices/require-probes/require-probes/
  [2]: https://kyverno.io/docs/writing-policies/variables/

### Steps to reproduce

1. Install the kyverno policy above inside a helm chart

### Expected behavior

kyverno variables are escaped so it can be compatible with helm/templates

### Screenshots

<img width="974" alt="Image" src="https://github.com/user-attachments/assets/934fa4f5-deee-445c-99b0-a5cd2f8e32d6" />

### Kyverno logs

```shell

```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.

**Comment by cooervo** [comment]
This was the only way to get it working:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-probes
   #...
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-probes
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - grafana-k8s-monitoring
      preconditions:
        all:
        - key: |-
              {{`{{ request.operation || 'BACKGROUND' }}`}}
          operator: AnyIn
          value:
          - CREATE
          - UPDATE
      validate:
        message: "Liveness, readiness, or startup probes are required for all containers."
        foreach:
        - list: request.object.spec.containers[]
          deny:
            conditions:
              all:
              - key: livenessProbe
                operator: AllNotIn
                value: |-
                  {{`{{"element.keys(@)[]"}}`}}
              - key: readinessProbe
                operator: AllNotIn
                value: |-
                  {{`{{"element.keys(@)[]"}}`}}
```
