### ISSUE TITLE
[Bug] Two mutate policies overrides each other

### ISSUE THREAD

**Issue by liwang0513** [kyverno/policies#1242]
### Kyverno Version

1.12

### Kubernetes Version

1.27

### Kubernetes Platform

Bare metal

### Description

We have two mutation policies trying to append extra fields under `envFrom` using `patchStrategicMerge`. If any of them gets triggered standalone, it works as expected. However, if both of them get triggered, there is only one field gets appended. Looks like one will override the other one.

### Steps to reproduce

1. The first mutation policy -
```
    mutate:
      patchStrategicMerge:
        spec:
          podTemplate:
            spec:
              containers:
              - envFrom:
                - configMapRef:
                    name: '{{ EnvConfigMapName }}'
                name: flink-main-container
```
2. The second mutation policy - 
```
    mutate:
      patchStrategicMerge:
        spec:
          podTemplate:
            spec:
              containers:
              - envFrom:
                - prefix: '{{ identitySpec.type | to_upper(@) }}_'
                  secretRef:
                    name: '{{ identitySpec.secret }}'
                name: flink-main-container
```
3. Each of them works as expected separately, however if triggers at the same time, we will only see one of them get applied.
```
        envFrom:
        - configMapRef:
            name: dice-usage
```
or
```
        envFrom:
        - prefix: "IAM"
           secretRef:
             name: dice-usage-secret
```

### Expected behavior

We would like to see something like this
```
        envFrom:
        - configMapRef:
            name: dice-usage
        - prefix: "IAM"
           secretRef:
             name: dice-usage-secret
```

### Kyverno logs

```shell

```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.
