### ISSUE TITLE
[Bug]  Kyverno Incorrectly Targets Knative Service (serving.knative.dev/v1/Service) Instead of Kubernetes Service (v1/Service)

### ISSUE THREAD

**Issue by macro-dadt** [kyverno/policies#1263]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

I'm trying to use a Kyverno mutate.targets rule to update a Kubernetes Service (v1/Service) based on changes in an Endpoints resource. 
```yaml

mutate:
      targets:
        - apiVersion: v1
          kind: Service
          name: "demo-frontend"
          namespace: "default"
```
However, Kyverno appears to target a Knative Service (services.serving.knative.dev) instead of the correct v1/Service, resulting in an error:
```
response error: services.serving.knative.dev "demo-frontend" not found
```

I'm convinced that the `targets` block is the issue because everything works as expected if I try to target a configmap but not v1/service 

### Steps to reproduce

1.  Create a dummy deployment + service

```yaml

apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-frontend
    zone-dedicated-service-name: demo-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
        zone-dedicated-service-name: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: nginx:latest
          ports:
            - containerPort: 80

```
2. Create a policy
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-zone-label-when-no-endpoints
spec:
  background: false
  rules:
  - name: remove-zone-selector-on-empty-endpoints
    match:
      any:
      - resources:
          kinds: ["Endpoints"]
          namespaces: ["default"]
          names: ["demo-frontend"]
          operations: ["CREATE", "UPDATE", "DELETE"]
    preconditions:
      all:
      - key: "{{ request.object.subsets || `[]` | length(@) }}"
        operator: Equals
        value: 0
    mutate:
      targets:
        - apiVersion: v1
          kind: Service
          name: "demo-frontend"
          namespace: "default"
      patchStrategicMerge:
        spec:
          selector:
            zone-dedicated-service-name: null

```

### Expected behavior

- when the Endpoints object for demo-frontend has no subsets (no pods exist behind it), the Kyverno policy should mutate the corresponding Kubernetes Service (v1/Service) to remove a specific selector (zone-dedicated-service-name).

- Kyverno should only target v1/Service, not services.serving.knative.dev.

### Kyverno logs

```shell

```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.
