### ISSUE TITLE
[Bug] access a label containing dots in a precondition block

### ISSUE THREAD

**Issue by angelbarrera92** [kyverno/policies#1274]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

Other (specify in description)

### Description

I am getting mad trying to access a label containing dots in a precondition block. Any idea if it is possible in 1.12?

### Steps to reproduce

1. Create the following deployment and ConfigMap:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
data:
  hello: world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    example-configmap.configmap.reloader.kyverno.io: ""
  name: example-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: example-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-app
    spec:
      containers:
      - env:
        - name: CONFIGMAP_HELLO
          valueFrom:
            configMapKeyRef:
              key: hello
              name: example-configmap
        envFrom:
        - configMapRef:
            name: example-configmap
        image: nginxinc/nginx-unprivileged:alpine3.20
        imagePullPolicy: IfNotPresent
        name: example-container
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: hello-world-empty-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 64Mi
        name: hello-world-empty-dir
```

The important bits here is the Deployment label: `example-configmap.configmap.reloader.kyverno.io: ""`
It starts with the name of the configmap.

2. Then create the ClusterPolicy:

```yaml
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: rollout-dependent-workloads
spec:
  background: false
  rules:
    - name: rollout-on-configmap-change
      match:
        any:
        - resources:
            kinds:
              - ConfigMap
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
            namespace: "{{request.namespace}}"
            name: "*"
            context:
              - name: labelFilter
                variable: 
                  value: "{{ request.object.metadata.name }}.configmap.reloader.kyverno.io"
            preconditions:
              any:
              - key: '{{ target.metadata.labels."{{ labelFilter }}" }}'
                operator: Exists
        patchStrategicMerge:
          metadata:
            annotations:
              reloader.kyverno.io/last-reload: "{{ time_now_utc() }}"
```

3. Trigger and update in the configmap by: `kubectl annotate configmap example-configmap modified="$(date)" --overwrite`

### Expected behavior

I expect the precondition block to filter the deployments to match the expected and dynamically generated label, then, the deployment will get the new annotation and eventually, it rolls the pods from that deployment.

### Kyverno logs

```shell
ERROR	background	mutate/mutate.go:165		{"name": "ur-7trwr", "policy": "rollout-dependent-workloads", "resource": "v1/ConfigMap/co/example-configmap", "error": "failed to mutate existing resource, rule rollout-on-configmap-change, response error: failed to evaluate preconditions: failed to substitute variables in condition key: failed to resolve target.metadata.labels.\"example-configmap.configmap.reloader.kyverno.io\" at path : JMESPath query failed: Unknown key \"example-configmap.configmap.reloader.kyverno.io\" in path"}
```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.
