### ISSUE TITLE
[Bug] Cluster Policy CPU/Memory Mutation Based on ownerReferences

### ISSUE THREAD

**Issue by zalseryani** [kyverno/policies#1291]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

GKE

### Description

I am applying a mutation cluster policy that add default cpu and memory request for all pods (that are not owned by jobs) 

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-memory-requests-mutation-clusterpolicy
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: add-default-resources
    preconditions:
      all:
      - key: "{{ request.object.metadata.ownerReferences[0].kind || '' }}"
        operator: NotEquals
        value: "Job"
    exclude: 
      all:
      - resources:
          namespaceSelector: 
            matchLabels: 
              system-ns: "true"
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      foreach:
      - list: "request.object.spec.containers[]"
        patchStrategicMerge:
          spec:
            containers:
            - (name): "{{element.name}}"
              resources:
                requests:
                  +(memory): "50Mi"
                  +(cpu): "50m"
```

- when creating a job, it will produce a pod that is owned by this job, the mutate rule should not be applied on the pod as it is owned by a job, and that is mentioned in the clusterpolicy. 

### Steps to reproduce

- Notes: 
> - ```GKE version is v1.30.10-gke.1070000``` but the version is not available in the template. 
> - ```Kyverno Version: v1.12.5```
1. apply the following cluster policy. 
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-memory-requests-mutation-clusterpolicy
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: add-default-resources
    preconditions:
      all:
      - key: "{{ request.object.metadata.ownerReferences[0].kind || '' }}"
        operator: NotEquals
        value: "Job"
    exclude: 
      all:
      - resources:
          namespaceSelector: 
            matchLabels: 
              system-ns: "true"
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      foreach:
      - list: "request.object.spec.containers[]"
        patchStrategicMerge:
          spec:
            containers:
            - (name): "{{element.name}}"
              resources:
                requests:
                  +(memory): "50Mi"
                  +(cpu): "50m"
```

2. Create the following job.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ubuntu
  namespace: zeid-test
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/bash",  "-c", "sleep infinity"]
      restartPolicy: Never
  backoffLimit: 1
```
3. check the pod that is generated by the job, you will see that CPU and memory are added, while based on the configured policy, the policy should not add CPU and memory since the precondition states that this rule should only apply on the pods that are not owned by Job. 

### Expected behavior

Not to add cpu and memory for the pods owned by a job.

### Screenshots

![Image](https://github.com/user-attachments/assets/f413ebb6-e1a9-4d87-9ab2-943b2311f5e0)

### Kyverno logs

```shell

```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.
