### ISSUE TITLE
[Bug] Image sign verify policy trouble

### ISSUE THREAD

**Issue by F-Fx** [kyverno/policies#1301]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

Other (specify in description)

### Description

Hello,team
need help with image sign verify policy

- k8s v1.31.4+rke2r1
- kyverno v1.13.4

I have installed my test app helm chart with one deployment. The image which is used in this chart is signerd by cosign
My policy look like

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image.enforce
  annotations:
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/category: Sample, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.7.0
    policies.kyverno.io/description: >-
      Using the Cosign project, OCI images may be signed to ensure supply chain
      security is maintained. Those signatures can be verified before pulling into
      a cluster. This policy checks the signature of an image repo called
      ghcr.io/kyverno/test-verify-image to ensure it has been signed by verifying
      its signature against the provided public key. This policy serves as an illustration for
      how to configure a similar rule and will require replacing with your image(s) and keys.      
spec:
  validationFailureAction: Enforce
  background: false
  webhookConfiguration:
    failurePolicy: Fail
    timeoutSeconds: 30
  rules:
    - name: verify-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "harbor.test.local/*"
        mutateDigest: true
        attestors:
        - entries:
          - keys:
              publicKeys: |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOb5QMNG7TBPHhTMoVTS+Jsd+dxST
                Rf6aonBl7VlGkkJ7wFu/vzFaB1yVm5ZXDtf9gNlr+qrdP7UTVaYyGkUmvA==
                -----END PUBLIC KEY-----
              rekor:
                ignoreTlog: true
                url: https://rekor.sigstore.dev/
              ctlog:
                ignoreSCT: true
      exclude:
        any:
        - resources:
            namespaces:
              - "calico-system"
              - "cattle-*"
              - "default"
              - "sec-*"
              - "tigera-operator"
              - "kube-*"
              - "external-secrets"
              - "local"
              - "csi-driver-nfs"
```

If i upgrade my test helm APP i see error (change some a annotations ). Image not changed.

```
verify-image.enforce:
  autogen-verify-image: missing digest for {my image}
```

but if i fully uninstall my helm chart and install it again the policy passed and i see that signature was successfullychecked
Pls help)))

### Steps to reproduce

1. Upgrade helm-chart (no change in image)

### Expected behavior

I want image sign be verified, if i update my chart without image tag update

### Kyverno logs

```shell
verify-image.enforce:
  autogen-verify-image: missing digest for {my image}
```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.
