### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by caspar-ds** [kyverno/policies#1305]
### Kyverno Version

1.12

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

["Add Node Affinity"](https://main.kyverno.io/policies/other/add-node-affinity/add-node-affinity/) policy example results in an infinite loop of adding node affinity expressions to a deployment:

```yaml
     spec:
       affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: zone_weight
                  operator: Lt
                  values:
                  - "400"
               # ...
               - key: zone_weight
                  operator: Lt
                  values:
                  - "400"
```

### Steps to reproduce

1. Add the policy in the example
2. Add a deployment
3. The node affinity expressions will contain the expected expression
4. Update the annotations on the deployment to contain `test: "1"`
5. The node affinity expressions will contain the expected expression twice
6. Update the annotations on the deployment to contain `test: "2"`
7. The node affinity expressions will contain the expected expression three times

### Expected behavior

The expressions should only be updated when one does not already exist

### Kyverno logs

```shell

```

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [x] I have searched other issues in this repository and mine is not recorded.
