### ISSUE TITLE
[BUG] CLI test failed for validate policy

### ISSUE THREAD

**Issue by realshuting** [kyverno/policies#136]
**Software version numbers**
State the version numbers of applications involved in the bug.

* Kubernetes version:
* Kubernetes platform (if applicable; ex., EKS, GKE, OpenShift):
* Kyverno version: 1.4.3

**Describe the bug**
CLI test for the new validate policy failed in kyverno/kyverno CI, test set https://github.com/kyverno/policies/tree/main/other/restrict_ingress_host.

Failure log https://github.com/kyverno/kyverno/runs/3733154812.

The issue is the rule names in the `test.yaml` and `value.yaml` do not match the names in the policy. I fixed the rule names locally but struggled with defining the value for var `{{ request.object.spec.rules[].host | length(@)}}`. 

@NoSkillGirl @viveksahu26 @vyankyGH How should I specify the variable in value.yaml?

**Comment by realshuting** [comment]
And if I don't define that var in value.yaml, the rule would fail because the variable is not defined:
```
✗ go run ./cmd/cli/kubectl-kyverno/main.go test ../../kyverno/policies/other/restrict_ingress_host

Executing unique-ingress-host...
applying 1 policy to 2 resources... 
test skipped for policy  unique-ingress-host  (as required variables are not provided by the users) 
 
│───│─────────────────────│─────────────────────│──────────────────────│────────│
│ # │ POLICY              │ RULE                │ RESOURCE             │ RESULT │
│───│─────────────────────│─────────────────────│──────────────────────│────────│
│ 1 │ unique-ingress-host │ check-single-host   │ ingress-kyverno-host │ Pass   │
│ 2 │ unique-ingress-host │ deny-multiple-hosts │ ingress-foo-host     │ Fail   │
│───│─────────────────────│─────────────────────│──────────────────────│────────│
```

**Comment by viveksahu26** [comment]
hey @realshuting , For variable I raised an [issue ](https://github.com/kyverno/kyverno/issues/2445)and it is resolved now. There was mistake in `test.yaml` and `values.yaml` file. I have fixed it locally and also asked @NoSkillGirl  to cross check it.

**Comment by realshuting** [comment]
Are these two tests passed in your local test? Can you please submit your local fix? We need it for all tests in kyverno/kyverno.

**Comment by viveksahu26** [comment]
Can you check with this, and policy will be same.

`resource.yaml`
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kyverno-host
spec:
  rules:
  - host: www.kyverno.com
    http:
      paths:
      - pathType: Prefix
        path: "/kyverno"
        backend:
          service:
            name: service1
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-foo-host
spec:
  rules:
  - host: www.foo.com
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
```

`test.yaml`
```
name: unique-ingress-host
policies:
  - restrict_ingress_host.yaml
resources:
  - resource.yaml
variables: values.yaml
results:
  - policy: unique-ingress-host
    rule: check-single-host
    resource: ingress-kyverno-host
    kind: Ingress
    result: fail
  - policy: unique-ingress-host
    rule: check-single-host
    resource: ingress-foo-host
    kind: Ingress
    result: skip
  - policy: unique-ingress-host
    rule: deny-multiple-hosts
    resource: ingress-kyverno-host
    kind: Ingress
    result: skip
  - policy: unique-ingress-host
    rule: deny-multiple-hosts
    resource: ingress-foo-host
    kind: Ingress
    result: skip
```

`values.yaml`

```policies:
- name: unique-ingress-host
  rules:
  - name: check-single-host
    values:
      hosts: "[\"www.github.com\", \"www.kyverno.com\", \"www.nirmata.com\"]"
  resources:
  - name: ingress-kyverno-host
    values:
      request.operation: CREATE
  - name: ingress-foo-host
    values:
      request.operation: UPDATE
````
