### ISSUE TITLE
Add env vars from ConfigMap per Namespace

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#159]
From Slack: Have one CM per NS with all env vars defined. Mutate pods with per-NS CM to get those env vars.

**Comment by chipzoller** [comment]
Something like:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-env-vars-from-cm
  annotations:
    policies.kyverno.io/title: Add Environment Variables from ConfigMap
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/category: Other
    policies.kyverno.io/description: >-
      Instead of defining a common set of environment variables multiple
      times either in manifests or separate policies, Pods can reference
      entire collections stored in a ConfigMap. This policy mutates all
      initContainers (if present) and containers in a Pod with environment
      variables defined in a ConfigMap named `nsenvvars` that must exist
      in the destination Namespace.     
spec:
  rules:
  - name: add-env-vars-from-cm
    match:
      resources:
        kinds:
        - Pod
    mutate:
      patchStrategicMerge:
        spec:
          initContainers:
            - (name): "*"
              envFrom:
              - configMapRef:
                  name: nsenvvars
          containers:
            - (name): "*"
              envFrom:
              - configMapRef:
                  name: nsenvvars
```
