### ISSUE TITLE
Policy to block node taint alterations

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#168]
Write a policy which blocks the alterations to node taints.

**Comment by chipzoller** [comment]
Working:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-node-taints
  annotations:
    policies.kyverno.io/title: Protect Node Taints
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Node
    policies.kyverno.io/description: >-
      WIP. Use of this policy requires removal of the Node resource filter
      in the Kyverno ConfigMap ([Node,*,*]). Due to Kubernetes CVE-2021-25735, this policy
      requires, at minimum, one of the following versions of Kubernetes:
      v1.18.18, v1.19.10, v1.20.6, or v1.21.0.      
spec:
  validationFailureAction: enforce
  background: false
  rules:
  # this works in preventing adds, removes, or changes
  - name: prevent-taint-changes
    match:
      resources:
        kinds:
        - Node
    # exclude:
    #   clusterRoles:
    #   - cluster-admin
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
    validate:
      message: "Taints may not be altered."
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.taints}}"
            operator: NotEquals
            value: ""
          - key: "{{request.oldObject.spec.taints}}"
            operator: NotEquals
            value: "{{request.object.spec.taints}}"
```
