### ISSUE TITLE
for emptyDir volumes, enforce ephemeral-storage definition

### ISSUE THREAD

**Issue by rubroboletus** [kyverno/policies#171]
**Checklist**

- [x] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Is your policy request related to a problem? Please describe.**

We are trying to enforce, that if any volume with emptyDir exists in POD (Deployment, ...) definition, each container using it must define requests.ephemeral-storage and limits.ephemeral-storage.

**Describe the ideal solution you'd like**

When any cronjob, daemonset, deployment, job, pod or statefulset defines volume of type emptyDir, containers using this volume must have in resources definition requests.ephemeral-storage and limits.ephemeral-storage present.

**Additional context**

 Example pod with 3 containers, 2 using the emptyDir volume and defined ephemeral-storage requests and limits:
 ```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: jaeger-agent
    image: images.my-company.example/jaeger:v2
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir: {}
```

**Comment by chipzoller** [comment]
We're discussing how to tackle this policy in [this discussion](https://github.com/kyverno/kyverno/discussions/2697). Currently it seems like we may be blocked until there is an enhancement to the `foreach` logic.

**Comment by chipzoller** [comment]
Ok @rubroboletus after more time on this, I think I've solved it. Although, as mentioned in the above comment, we do have a limitation with `foreach` logic, I am able to work around it by combining `containers[]` and `initContainers[]` into the same array. Here is a policy which finally works (I am tested on latest-ish code but this should work for any of the 1.5 releases).

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: emptydir-requests-and-limits
  annotations:
    policies.kyverno.io/title: emptyDir has requests and limits
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.5.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      WIP     
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: emptydir
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{ request.object.spec.volumes[?contains(keys(@), 'emptyDir')] | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: Containers mounting emptyDir volumes must specify requests and limits for ephemeral-storage.
      foreach:
      - list: "request.object.spec.volumes[?contains(keys(@), 'emptyDir')]"
        deny:
          conditions:
            any:
              # get the number of containers (based on name) which mount this emptyDir (by name)
            - key: "{{request.object.spec.[initContainers, containers][].volumeMounts[?name == '{{ element.name }}' ][].name | length(@) }}"
              operator: NotEquals
              # compare it to the number of containers (also mounting this same emptyDir vol by name) which have ephemeral-storage requests.
              # block if the two numbers aren't equal. If limits are specified but not requests, requests are automatically
              # set equal to the value of the limit. Therefore, this condition only works effectively if both requests and limits are not set.
              value: "{{request.object.spec.[initContainers, containers[?volumeMounts[?name == '{{element.name}}' ]]][].resources.requests.\"ephemeral-storage\" | length(@) }}"
            - key: "{{request.object.spec.[initContainers, containers][].volumeMounts[?name == '{{ element.name }}' ][].name | length(@) }}"
              operator: NotEquals
              # same as above but with limits
              value: "{{request.object.spec.[initContainers, containers[?volumeMounts[?name == '{{element.name}}' ]]][].resources.limits.\"ephemeral-storage\" | length(@) }}"
```

Test with this Pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  initContainers:
  - name: initapp
    image: images.my-company.example/app:v4
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  volumes:
    - name: ephemeral
      emptyDir: {}
```

Comment out, for example, one of the limits for any container and see the Pod is blocked. Comment out both requests and limits and see the same thing. Note that in Kubernetes is you supply a limit but not a request, the request is automatically set to the same value as the limit.

```
$ k apply -f pod.yaml 
Error from server: error when creating "pod.yaml": admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Pod/default/frontend was blocked due to the following policies

emptydir-requests-and-limits:
  emptydir: validation failed in foreach rule for Containers mounting emptyDir volumes
    must specify requests and limits for ephemeral-storage.
```

Try it out and let me know, please.
