### ISSUE TITLE
Limits fraction of request

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#175]
Pull the policy from a Kyverno PR to use as a sample. Use the divide function to validate a pod's limits are no more than 2.5x its requests for CPU and memory.

**Comment by chipzoller** [comment]
Will be enabled by https://github.com/kyverno/kyverno/pull/2753

**Comment by chipzoller** [comment]
This should work but currently isn't

```yaml
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: requests-limits
spec:
  # schemaValidation: false
  rules:
  - name: check-requests-limits
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: Limits may not exceed 2.5x the requests.
      foreach:
      - list: "request.object.spec.containers"
        deny:
          conditions:
            any:
            - key: "divide({{ element.resources.limits.cpu }}, {{ element.resources.requests.cpu }})"
              operator: GreaterThan
              value: 2.5
```

Relevant PRs [here ](https://github.com/kyverno/kyverno/pull/2753) and [here](https://github.com/kyverno/kyverno/pull/2416).

**Comment by chipzoller** [comment]
Have to go with this for now:

```yaml
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-limits-fraction
spec:
  validationFailureAction: enforce
  rules:
  - name: check-memory-requests-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "{{ request.operation }}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: Limits may not exceed 2.5x the requests.
      foreach:
      - list: "request.object.spec.containers"
        deny:
          conditions:
            any:
              # Set resources.limits.memory equal to zero if not present and resources.requests.memory equal to 1m rather than zero
              # to avoid undefined division error. No memory request in this case is basically the same as 1m. Kubernetes API server
              # will automatically set requests=limits if only limits is defined.
            - key: "{{ divide('{{ element.resources.limits.memory || '0' }}', '{{ element.resources.requests.memory || '1m' }}') }}"
              operator: GreaterThan
              value: 2.5
```
