### ISSUE TITLE
Kubernetes external-dns policy enforcing unique hostnames

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#177]
From [this comment](https://github.com/kyverno/kyverno/issues/2567#issue-1032275803), add the policy.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-external-dns
  annotations:
    policies.kyverno.io/title: Unique External DNS record
    policies.kyverno.io/category: External DNS
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/minversion: 1.3.6
    policies.kyverno.io/description: >-
      Avoid having duplicated DNS entries in DNS provider though External DNS annotations. Workaround for
      https://github.com/kubernetes-sigs/external-dns/issues/2346.
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: ensure-valid-externaldns-annotation
      match:
        resources:
          kinds:
            - Service
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "*"
      context:
        # Looks up external DNS entries.
        - name: alldns
          apiCall:
            urlPath: "/api/v1/services"
            jmesPath: "items[].metadata.annotations.\"external-dns.alpha.kubernetes.io/hostname\""
      preconditions:
      - key: "{{ request.operation }}"
        operator: In
        value:
          - "CREATE"
          - "UPDATE"
      validate:
        message: >-
          External DNS entry "{{request.object.metadata.annotations."external-dns.alpha.kubernetes.io/hostname"}}" is already
          taken by other service.
        deny:
          conditions:
            all:
              # Deny if "external-dns.alpha.kubernetes.io/hostname" annotation value is already taken
              - key: "{{request.object.metadata.annotations.\"external-dns.alpha.kubernetes.io/hostname\"}}"
                operator: In
                value: "{{alldns}}"
```
