### ISSUE TITLE
Update existing test.yaml to the new format

### ISSUE THREAD

**Issue by anushkamittal20** [kyverno/policies#180]
In[ this PR](https://github.com/kyverno/kyverno/pull/2733) we have introduced a new format for test.yaml which should be updated in kyverno/policies as well. The old format will be removed in 1.8.0
New YAML are more in line with kustomize (with k8s style apiVersion and kind)
```
apiVersion: cli.kyverno.io/v1alpha1
kind: PolicyTests
metadata:
  name: test-simple
spec: 
  policies:
    - policy.yaml
  resources:
    - resources.yaml
  results:
    - policy: disallow-latest-tag
      rule: missing
      resource: test
      kind: Pod
      status: pass
```
Reference : [kyverno/issues/2323](https://github.com/kyverno/kyverno/issues/2323)
