### ISSUE TITLE
psp migration docs help request/beg :)

### ISSUE THREAD

**Issue by chrisns** [kyverno/policies#184]
Hey
*Thanks for looking at #182 , #181 and #183*

I'm working on https://github.com/appvia/psp-migration wondered if I could beg for some help on the kyverno policy areas.
As per the readme you'll see theres a few (currently 7) policies that I'm a bit stuck on figuring out the syntax for things like ranges, checking something is in a list and more complex boolean logic in the policy for things like securityContext (i.e. if its defined at the pod or container level) etc.

Hoping to make this a useful resource for folk getting a head start on moving away from PSP, any help would be massively appreciated.

I'm on Kubernetes.slack.com if its easier to chat there

Thanks
~c

**Comment by chipzoller** [comment]
Have you not seen these which are covered by the Kubernetes Pod Security Standards?

https://kyverno.io/policies/?policytypes=Pod%2520Security%2520Standards%2520%28Baseline%29%2BPod%2520Security%2520Standards%2520%28Restricted%29

**Comment by chrisns** [comment]
Heya, thanks for the quick reply

Yes, as you can see I've copy+pasted with pride (and minor tweaks) a lot of the existing work from that (and this repo)

However I'm trying to recreate PSP not PSS which is a bit more nuanced so means being able to do things like say _"you can have host ports, within a given range"_ for example where as PSS is more _"no host ports for you"_

It is however entirely possible (more likely than not if I'm honest) I've missed something in the examples that does address my current failing test cases

**Comment by chipzoller** [comment]
I'm glad to help cover these gaps, but what I'd request is you providing here a concise list of what the *specific* gaps are with existing Kyverno policies and what a successful policy should do that the closest one doesn't. These can then be checked off a list as they get built and tested.

For example, in your hostPorts instance, the current gap when compared with what we currently have is non-support for ranges. This will be coming in Kyverno 1.6.0 out of [this PR](https://github.com/appvia/psp-migration/blob/main/tests/hostPorts/kyverno.yaml), but for the time being there is a workaround. But in order to write that workaround, we should see a task list that plainly states what the needed behavior is. If you can work on adding that to this issue, we can go from there.

**Comment by JimBugwadia** [comment]
Hi @chrisns - thanks! I agree this would be a very valuable resource for folks migrating from PSPs.

For ranges, have you tried specifying as `">=80 & <=9000"`? 

See: https://kyverno.io/docs/writing-policies/validate/#operators. 

For checking across pod and container level security contexts, the sample pod security policies have handing for this using an `anyPattern`. Here is an example:

https://kyverno.io/policies/pod-security/restricted/require-run-as-nonroot/require-run-as-nonroot/

What are the other policies that are not working or easy to convert from PSPs?

Perhaps we can add comments or other help in the pod security related samples to highlight some of this?

There was a related prior discussion for a custom PSP where the user wanted to allow two hostpath values, but with one as readyOnly: https://twitter.com/uesyn/status/1451374871204687875.

**Comment by chrisns** [comment]
@JimBugwadia thanks for the pointers! Think that'll get me most the way there! awesome thanks!

the only other ones I think are:
https://github.com/appvia/psp-migration/blob/main/tests/supplementalGroups/kyverno.yaml
https://github.com/appvia/psp-migration/blob/main/tests/allowedCapabilities/kyverno.yaml
which I'm guessing is a foreach loop, but it feels really copy+pasty, especially if I need to use the `anyPattern` too

any thoughts on how to make that less ugly?

**Comment by chrisns** [comment]
down to three remaining test cases: https://github.com/appvia/psp-migration/runs/4373293733 🥳 🎉 

---

for `volumes` I need to check the type of volume in a list of volumes e.g.

```yaml
volumes
  - name: foo
    hostPath: 
      path: /foo
  - name: bar
    emptyDir: {}
```
against a list of like:
```yaml
  - hostPath
  - emptyDir
  - secret
```
---
for the other two its a bit simpler, I want to be able to check that the things in a list are in the check list:
```yaml
supplementalGroups:
  - 123
  - 456
```
against a list of like:
```yaml
  - 123
  - 456
  - 789
```

**Comment by JimBugwadia** [comment]
`preConditions` and `deny` rules can match scalar values in lists. That may be useful for `supplementalGroups` and `capabilities`:

https://kyverno.io/docs/writing-policies/validate/#deny-rules

https://kyverno.io/docs/writing-policies/preconditions/

**Comment by chrisns** [comment]
Hey @JimBugwadia I'm having total brain farts trying to write the syntax for that, could I beg you to point me at the full example I can reuse?
also I was wrong on the `supplementalGroups` I want to be able to provide a collection bunch of ranges
so its:
```yaml
supplementalGroups:
  - 123
  - 456
```
against:
```yaml
supplementalGroups:
  - min: 100
    max: 200
  - min: 1000
    max: 2000
```

The capabilities however are as I described, also any thoughts on the syntax required for the volumes?

**Comment by chipzoller** [comment]
> down to three remaining test cases: https://github.com/appvia/psp-migration/runs/4373293733 🥳 🎉
> 
> for `volumes` I need to check the type of volume in a list of volumes e.g.
> 
> ```yaml
> volumes
>   - name: foo
>     hostPath: 
>       path: /foo
>   - name: bar
>     emptyDir: {}
> ```
> 
> against a list of like:
> 
> ```yaml
>   - hostPath
>   - emptyDir
>   - secret
> ```
> 
> for the other two its a bit simpler, I want to be able to check that the things in a list are in the check list:
> 
> ```yaml
> supplementalGroups:
>   - 123
>   - 456
> ```
> 
> against a list of like:
> 
> ```yaml
>   - 123
>   - 456
>   - 789
> ```

Look at [this policy](https://kyverno.io/policies/other/ensure_readonly_hostpath/ensure_readonly_hostpath/) as a starter for doing that.

**Comment by chrisns** [comment]
@chipzoller I'm probably being thick and slow (Sorry!)
but that policy doesn't really get me close enough
I want to iterate through each object in the array and assert that the object contains a key in a list
maybe this is along the lines?
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: psp-volumes
spec:
  validationFailureAction: enforce
  rules:
  - name: psp-volumes
    match:
      resources:
        kinds:
          - Pod
    validate:
      message: Volume types are limited
      foreach:
      - list: "request.object.spec.volumes[][]"
        deny:
          conditions:
          - key: "{{element.configMap | element.emptyDir | element.projected | element.secret | element.downwardAPI | element.persistentVolumeClaim | element.flexVolume }}"
            operator: NotEquals
            value: ??
```

**Comment by chrisns** [comment]
hey, sorry for not being clear
the overall goal is mapping from the psp spec to kynervo: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems

so I want to be able to have a list of volumes in a kynervo policy that are allowed to be used.

PSP that does this: https://github.com/appvia/psp-migration/blob/main/tests/volumes/psp.yaml

allowed resource: https://github.com/appvia/psp-migration/blob/main/tests/volumes/allowed.yaml
not allowed resource: https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/volumes/samples/psp-volume-types/example_disallowed.yaml

can make a pr against this repo with the failing tests if that'd make it easier to collaborate and for you to help?

**Comment by chipzoller** [comment]
And why won't an adaptation of [this policy](https://kyverno.io/policies/pod-security/restricted/restrict-volume-types/restrict-volume-types/) work?

**Comment by chrisns** [comment]
I want to say what is allowed as opposed to defining what is not

**Comment by chipzoller** [comment]
Ok, so you want that policy to be inverted then. That's a little bit tricker and would need to be a JMEPath expression that checks if `spec.volumes[]` contains keys OTHER THAN `projected` and `emptyDir` and that still allows `spec.volumes[]` to be optional.

**Comment by chrisns** [comment]
Err. Yeah! One of them! :) ¯\_(ツ)_/¯

**Comment by chipzoller** [comment]
Well, not just one of them though. It has to ensure that there are no other types aside from `projected` and `emptyDir`. If it was just one of those two, this would be much easier, but then this Pod (below) would work when it shouldn't:

```yaml
# This is bad because even though there is one volume here
# which is allowable (the emptyDir), it still contains one
# disallowed volume type (the secret).
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: busybox
    image: something:tag
  volumes:
  - name: foo
    secret:
      secretName: mysecret
  - name: fooyou
    emptyDir: {}
```

**Comment by chrisns** [comment]
A foreach loop that checks each volume?
Other wise if it's not possible to articulate, I could invert the logic in my mapping given there's a well known small list of volumes baked into core k8s

**Comment by chipzoller** [comment]
I think this will work with the new `AnyNotIn` operator, but I need to test it:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-vols
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: allowed-vols
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value: 
        - CREATE
        - UPDATE
      - key: "{{ request.object.spec.volumes[].keys(@)[] | length(@) }}"
        operator: GreaterThan
        value: 0
    validate:
      message: "Only emptyDir and projected volumes are allowed."
      deny:
        conditions:
          all:
          - key: "{{ request.object.spec.volumes[].keys(@)[] }}"
            operator: AnyNotIn
            value:
            - name
            - projected
            - emptyDir
```

**Comment by chipzoller** [comment]
Yep, it works as expected. Because we've got a current issue with the `latest` tag, I'm using the following image tags for testing:

`kyverno`: `latest@sha256:a78a24b758a2e4fd88edd02ccc242dad503fb083a46839dd5c6d14b77a1ad218`
`kyvernopre`: `latest@sha256:1124d52b6363bdbe6a9a8c910786ce7f3b1c90ca400f4f65f88d44df6947e41c`

All Pod tests pass.


## Bad Pods

```yaml
# This is bad because volume types secret and cephfs are not
# in the "good" types which can be emptyDir or projected.
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: busybox
    image: something:tag
  volumes:
  - name: foo
    secret:
      secretName: mysecret
  - name: fooyou
    cephfs:
      monitors:
        - "foo"
```

```yaml
# This is bad because even though there is one volume here
# which is allowable (the emptyDir), it still contains one
# disallowed volume type (the secret).
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: busybox
    image: something:tag
  volumes:
  - name: foo
    secret:
      secretName: mysecret
  - name: fooyou
    emptyDir: {}
```

## Good Pods

```yaml
# This is good because it only contains an emptyDir volume.
apiVersion: v1
kind: Pod
metadata:
  name: goodpod01
spec:
  containers:
  - name: busybox
    image: something:tag
  volumes:
  - name: fooyou
    emptyDir: {}
```

```yaml
# This is good because it contains no volumes at all.
apiVersion: v1
kind: Pod
metadata:
  name: goodpod02
spec:
  containers:
  - name: busybox
    image: something:tag
```

```yaml
# This is good because it contains volumes of the allowed types
# both emptyDir and projected.
apiVersion: v1
kind: Pod
metadata:
  name: goodpod03
spec:
  containers:
  - name: busybox
    image: something:tag
  volumes:
  - name: fooyou
    emptyDir: {}
  - name: foo
    projected:
      sources:
      - configMap:
          name: foomap
```

**Comment by chipzoller** [comment]
cc @anushkamittal20 as these new operators are her work in PR https://github.com/kyverno/kyverno/pull/2543

**Comment by chrisns** [comment]
@chipzoller Incredible! Looking forward to trying this out Monday! Thanks so much!

**Comment by chipzoller** [comment]
> Hey @JimBugwadia I'm having total brain farts trying to write the syntax for that, could I beg you to point me at the full example I can reuse? also I was wrong on the `supplementalGroups` I want to be able to provide a collection bunch of ranges so its:
> 
> ```yaml
> supplementalGroups:
>   - 123
>   - 456
> ```
> 
> against:
> 
> ```yaml
> supplementalGroups:
>   - min: 100
>     max: 200
>   - min: 1000
>     max: 2000
> ```
> 
> The capabilities however are as I described, also any thoughts on the syntax required for the volumes?

@JimBugwadia I think this one is going to be more of a problem for Kyverno currently. You remember a while back when we had a discussion in an issue about `foreach` and the ability for it to be pointed directly to an array. Currently, it has to be pointed to an array of objects and a key selected within that. We actually need to resolve a variable here directly to `spec.securityContext.supplementalGroups` so we can iterate over each one and see if it's in a predefined list including a range of values (PR https://github.com/kyverno/kyverno/pull/2788 will help make this simpler when it's merged) because there can be multiple of both supplementalGroups and destination sets/patterns.

If supplementalGroups contains one or more scalars and the destination set is one or more scalars, we can do that today with the `AnyIn` | `AnyNotIn` operators. But if the destination set contains anything more than a single range, I don't think Kyverno can do that today.

**Comment by chipzoller** [comment]
And this policy will close the "Add Capabilities" PSP analog (also pending Kyverno 1.6.0) which was adapted from [this](https://kyverno.io/policies/best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw/).

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-cap-add
spec:
  validationFailureAction: enforce
  background: false
  rules:
  # Checks initContainers to ensure they don't add anything other than what is permitted.
  - name: check-cap-add-initcontainers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      # Check if initContainers even exist in the Pod
      - key: "{{ request.object.spec.initContainers[] | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
    validate:
      message: The only capabilities that may be explicitly added are `something` or `somethingelse`.
      foreach:
      - list: "request.object.spec.initContainers[].securityContext.capabilities"
        deny:
          conditions:
            any:
            # Loop over the `add[]` array in each container and deny if anything other than the "something" or "somethingelse" capability has been added.
            - key: "{{ element.add }}"
              operator: AnyNotIn
              value:
              - something
              - somethingelse
  # Checks containers to ensure they don't add anything other than what is permitted.
  - name: check-cap-add-containers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: The only capability that may be explicitly added is `something`.
      foreach:
      - list: "request.object.spec.containers[].securityContext.capabilities"
        deny:
          conditions:
            any:
            # Loop over the `add[]` array in each container and deny if anything other than the "something" or "somethingelse" capability has been added.
            - key: "{{ element.add }}"
              operator: AnyNotIn
              value:
              - something
              - somethingelse
```

## Good Pods

```yaml
# This is good because it adds only the "something" capability.
apiVersion: v1
kind: Pod
metadata:
  name: goodpod01
spec:
  containers:
  - name: busybox
    image: something:tag
    securityContext:
      capabilities:
        add:
        - something
```

```yaml
# This is good because it adds nothing.
apiVersion: v1
kind: Pod
metadata:
  name: goodpod02
spec:
  containers:
  - name: busybox
    image: something:tag
```

## Bad Pods

```yaml
# This is bad because it adds the "badthing" capability which is disallowed.
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: busybox
    image: something:tag
    securityContext:
      capabilities:
        add:
        - badthing
```

```yaml
# This is bad because in addition to "something", which is allowed, it
# adds the "badthing" capability, which is disallowed. The whole Pod
# therefore must be blocked.
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: busybox
    image: something:tag
    securityContext:
      capabilities:
        add:
        - badthing
        - something
```

**Comment by chipzoller** [comment]
@chrisns were you able to test and validate any of these in the above responses?

**Comment by chrisns** [comment]
hey! sorry busy day with other stuff. top of my list for tomorrow morning! thanks again 😄

**Comment by chrisns** [comment]
- [x] volumes
- [ ] supplementalGroup
- [x] capabilities

supplementalGroup doesn't appear to like referring to `{{ element }}` I get: 
```
Error from server: error when creating "tests/supplementalGroups/kyverno.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: policy contains invalid variables: variable substitution failed for rule supplementalgroup-pseudo: variable element must match regex "request\.|serviceAccountName|serviceAccountNamespace|element\.|@|images\.|([a-z_0-9]+\()[^{}]" or patterns []
```
https://github.com/appvia/psp-migration/runs/4443212367?check_suite_focus=true#step:9:22

https://github.com/appvia/psp-migration/blob/kyverno_updates/tests/supplementalGroups/kyverno.yaml

**Comment by chipzoller** [comment]
Supplemental groups is a pseudo policy. It won't work as written.

**Comment by chrisns** [comment]
> Supplemental groups is a pseudo policy. It won't work as written.

oh I see, sorry misunderstood. is that not currently possible to do in kyverno at the minute then? (sorry if I'm being thick and slow!)

**Comment by chipzoller** [comment]
For *some* cases it should be possible but for something like what I put together which combines individual numbers and ranges, most likely not.

**Comment by chrisns** [comment]
For now I've done this, which 'works', and means I can tick the last box in the matrix 🥳 
It's not as elegant, but so long as no one has gigantic ranges it'd probably be ok?

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: psp-supplementalgroups
spec:
  validationFailureAction: enforce
  rules:
  - name: psp-supplementalgroups
    match:
      resources:
        kinds:
          - Pod
    validate:
      message: Any supplementalGroup ID must be within the collection [100-200].
      foreach:
      - list: "request.object.spec.securityContext"
        deny:
          conditions:
            any:
            - key: "{{ element.supplementalGroups }}"
              operator: AnyNotIn
              value:
                - 100
                - 101
                - 102
....etc
                - 200
```

Closing this ticket now that I've ticked everything on the matrix.

May have more questions as I begin to write the code to translate psp policy > kyverno policy

Thanks so much for your help so far, couldn't have done it without you @JimBugwadia & @chipzoller ! 👍

**Comment by chrisns** [comment]
https://github.com/appvia/psp-migration/runs/4449431512?check_suite_focus=true 🥳

**Comment by chipzoller** [comment]
> For now I've done this, which 'works', and means I can tick the last box in the matrix 🥳 It's not as elegant, but so long as no one has gigantic ranges it'd probably be ok?

Yes, that'd be better than nothing and is an example of a simpler rule, but it works. Hopefully by 1.6.0 this will be much simpler.

I'll also take these three policies and creating corresponding issues for them here on kyverno/policies so that when 1.6.0 does become available-assuming it solves for these as intended-we can add these as samples and make available on the [policies page](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
@chrisns this is a much better alternative for supplementalGroups:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: psp-check-supplemental-groups
  annotations:
    policies.kyverno.io/title: Disallow Capabilities
    policies.kyverno.io/category: PSP Migration
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      WIP
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: supplementalgroup-ranges
    match:
      any:
      - resources:
          kinds:
            - Pod
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: Any supplementalGroup ID must be within the range 100-200 or 500-600.
      pattern:
        spec:
          =(securityContext):
            =(supplementalGroups): 100-200 | 500-600
```

I'm putting this in our policy library along with others for your use case under a new category called "PSP Migration". Hope this helps.
