### ISSUE TITLE
Traefik TLSOption policy

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#187]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-default-tlsoptions
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: disallow-default-tlsoptions
    match:
      resources:
        name: "default"
        kinds:
        - TLSOption
    exclude:
      clusterRoles:
      - cluster-admin
    validate:
      message: "Only cluster administrators are allowed to set default TLSOptions"
      deny: {}
```
