### ISSUE TITLE
Add Disallow All Secrets policy

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#188]
From https://github.com/kyverno/kyverno/issues/1070

```yaml
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: no-secrets
  annotations:
    policies.kyverno.io/title: Disallow all Secrets
    policies.kyverno.io/category: Other
    policies.kyverno.io/description: >-
      Disables the use of all Secrets in a Pod definition. In order to work effectively,
      this Policy needs a separate Policy or rule to require `automountServiceAccountToken=false`
      since this would otherwise result in a Secret being mounted.
spec:
  validationFailureAction: enforce
  rules:
  - name: secrets-not-from-env
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "No Secrets from env."
      pattern:
        spec:
          containers:
          - name: "*"
            =(env):
            - =(valueFrom):
                X(secretKeyRef): "null"
  - name: secrets-not-from-envfrom
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "No Secrets from envFrom."
      pattern:
        spec:
          containers:
          - name: "*"
            =(envFrom):
            - X(secretRef): "null"
  - name: secrets-not-from-volumes
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "No Secrets from volumes."
      pattern:
        spec:
          =(volumes):
          - X(secret): "null"
```
