### ISSUE TITLE
Add policy to block Secrets based upon label protection

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#189]
From https://github.com/kyverno/kyverno/issues/1070

(WIP only)

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: secret-lookup
  annotations:
    policies.kyverno.io/title: WIP check secrets
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.5.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      WIP     
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: secrets-lookup-from-env
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      # check if any secrets are in env statements
      - key: "{{ request.object.spec.[containers, initContainers, ephemeralContainers][].env[].valueFrom.secretKeyRef | length(@)}}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: These Secrets are restricted.
      foreach:
      # get every secret, then do an API lookup on each one checking for the `status` labels.
      # deny the request if any of those secrets have `status=protected`.
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][].env[].valueFrom.secretKeyRef"
        context:
        - name: status
          apiCall:
            jmesPath: "metadata.labels.status"
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{element.name}}"
        deny:
          conditions:
            all:
            - key: "{{ status }}"
              operator: Equals
              value: protected
  - name: secrets-lookup-from-envfrom
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      # check if any secrets are in envfrom statements
      - key: "{{ request.object.spec.[containers, initContainers, ephemeralContainers][].envFrom[].secretRef | length(@)}}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: These Secrets are restricted.
      foreach:
      # get every secret, then do an API lookup on each one checking for the `status` labels.
      # deny the request if any of those secrets have `status=protected`.
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][].envFrom[].secretRef"
        context:
        - name: status
          apiCall:
            jmesPath: "metadata.labels.status"
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{element.name}}"
        deny:
          conditions:
            all:
            - key: "{{ status }}"
              operator: Equals
              value: protected
  - name: secrets-lookup-from-volumes
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      # check if any secrets are in volume statements
      - key: "{{ request.object.spec.volumes[].secret | length(@)}}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: These Secrets are restricted.
      foreach:
      # get every secret, then do an API lookup on each one checking for the `status` labels.
      # deny the request if any of those secrets have `status=protected`.
      - list: "request.object.spec.volumes[].secret"
        context:
        - name: status
          apiCall:
            jmesPath: "metadata.labels.status"
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{element.secretName}}"
        deny:
          conditions:
            all:
            - key: "{{ status }}"
              operator: Equals
              value: protected
```

**Comment by chipzoller** [comment]
Because of the issue in https://github.com/kyverno/kyverno/issues/2665, specifically [this comment](https://github.com/kyverno/kyverno/issues/2665#issuecomment-986149486), this sample policy is currently blocked.

**Comment by chipzoller** [comment]
Unblocked, working:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secrets-by-label
  annotations:
    policies.kyverno.io/title: Restrict Secrets by Label
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    # Need autogen for deny rules
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/subject: Pod, Secret
    policies.kyverno.io/description: >-
      Secrets often contain sensitive information and their access should be carefully controlled.
      Although Kubernetes RBAC can be effective at restricting them in several ways,
      it lacks the ability to use labels on referenced entities. This policy ensures
      that only Secrets not labeled with `status=protected` can be consumed by Pods.
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: secrets-lookup-from-env
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      # check if any secrets are in env statements
      - key: "{{ request.object.spec.[containers, initContainers, ephemeralContainers][].env[].valueFrom.secretKeyRef || '' | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: NotEquals
        value: DELETE
    validate:
      message: These Secrets are restricted.
      foreach:
      # get every secret, then do an API lookup on each one checking for the `status` label.
      # deny the request if any of those secrets have `status=protected`.
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][].env[].valueFrom.secretKeyRef"
        context:
        - name: status
          apiCall:
            jmesPath: "metadata.labels.status || ''"
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{element.name}}"
        deny:
          conditions:
          - key: "{{ status }}"
            operator: Equals
            value: protected
  - name: secrets-lookup-from-envfrom
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      # check if any secrets are in envfrom statements
      - key: "{{ request.object.spec.[containers, initContainers, ephemeralContainers][].envFrom[].secretRef || '' | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: NotEquals
        value: DELETE
    validate:
      message: These Secrets are restricted.
      foreach:
      # get every secret, then do an API lookup on each one checking for the `status` label.
      # deny the request if any of those secrets have `status=protected`.
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][].envFrom[].secretRef"
        context:
        - name: status
          apiCall:
            jmesPath: "metadata.labels.status || ''"
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{element.name}}"
        deny:
          conditions:
          - key: "{{ status }}"
            operator: AnyIn
            value: protected
  - name: secrets-lookup-from-volumes
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      # check if any secrets are in volume statements
      - key: "{{ request.object.spec.volumes[].secret || '' | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: NotEquals
        value: DELETE
    validate:
      message: These Secrets are restricted.
      foreach:
      # get every secret, then do an API lookup on each one checking for the `status` label.
      # deny the request if any of those secrets have `status=protected`.
      - list: "request.object.spec.volumes[].secret"
        context:
        - name: status
          apiCall:
            jmesPath: "metadata.labels.status || ''"
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{element.secretName}}"
        deny:
          conditions:
          - key: "{{ status }}"
            operator: Equals
            value: protected
```
