### ISSUE TITLE
Disable ServiceAccount token automount

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#190]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-automountserviceaccounttoken
spec:
  rules:
  - name: disable-automountserviceaccounttoken
    match:
      resources:
        kinds:
        - ServiceAccount
        names:
        - default
    mutate:
      patchStrategicMerge:
        automountServiceAccountToken: false
```
