### ISSUE TITLE
PSP migration policy - Supplemental Groups

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#191]
From comment [here](https://github.com/kyverno/policies/issues/184#issuecomment-986036183), when 1.6.0 is available with PR https://github.com/kyverno/kyverno/pull/2788 and https://github.com/kyverno/kyverno/pull/2543 merged in, this policy becomes possible.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: psp-supplementalgroup
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: supplementalgroup-pseudo
    match:
      resources:
        kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: Any supplementalGroup ID must be within the collection [100-200, 456, 789, 1000-2000].
      foreach:
      # Get all the supplementalGroup IDs
      - list: "request.object.spec.securityContext"
        deny:
          conditions:
            any:
            - key: "{{ element.supplementalGroups }}"
              operator: AnyNotIn
              value: 100-200
            - key: "{{ element.supplementalGroups }}"
              operator: AnyNotIn
              value: 1000-2000
            - key: "{{ element.supplementalGroups }}"
              operator: AnyNotIn
              value:
              - 456
              - 789
```
