### ISSUE TITLE
PSP migration policy - Allowed Volume Types

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#193]
From comment [here](https://github.com/kyverno/policies/issues/184#issuecomment-985777557), when 1.6.0 is released assuming support for https://github.com/kyverno/kyverno/pull/2543 is available, this policy becomes possible:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-vols
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: allowed-vols
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value: 
        - CREATE
        - UPDATE
      - key: "{{ request.object.spec.volumes[].keys(@)[] | length(@) }}"
        operator: GreaterThan
        value: 0
    validate:
      message: "Only emptyDir and projected volumes are allowed."
      deny:
        conditions:
          all:
          - key: "{{ request.object.spec.volumes[].keys(@)[] }}"
            operator: AnyNotIn
            value:
            - name
            - projected
            - emptyDir
```
