### ISSUE TITLE
Add annotation allow list policy

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#196]
More policies that use the new operators. Would be good to demonstrate how an allow list is constructed against a dictionary as opposed to a deny list for which many examples exist.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: fluxcd-annotations
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: enforce-fluxcd-annotations
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: The only approved FluxCD annotations are `fluxcd.io/cow` and `fluxcd.io/dog`.
      deny:
        conditions:
          all:
          - key: "{{ request.object.metadata.annotations.keys(@)[?contains(@, 'fluxcd.io/')] }}"
            operator: AnyNotIn
            value:
            - fluxcd.io/cow
            - fluxcd.io/dog
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  annotations:
    fluxcd.io/bat: notmoodontknow
    corp.com/bar: baz
    somethingsimple: else
spec:
  automountServiceAccountToken: false
  containers:
  - name: busybox
    image: registry.corp/sdf3vhadfa:1.28
```

Slack thread [here](https://kubernetes.slack.com/archives/CLGR9BJU9/p1639138921250100).
