### ISSUE TITLE
Add advanced registry allow list sample policy

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#197]
Although we've got a very use sample for [restricting image registries](https://kyverno.io/policies/best-practices/restrict_image_registries/restrict_image_registries/), it's fairly simple and there are some more advanced needs out there. One Slack issue came up whereby one or more cluster-wide registries are approved but in addition each Namespace can have one or more approved registries. This sample policy can be added to demonstrate more advanced image registry allow lists.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-registries
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: validate-corp-registries
      match:
        resources:
          kinds:
          - Pod
      context:
        # Get the value of the Namespace annotation called `corp.com/allowed-registries` and store. The value
        # must end with a wildcard. Currently assumes there is only a single registry name in the value.
        - name: nsregistries
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.namespace}}"
            jmesPath: "metadata.annotations.\"corp.com/allowed-registries\""
        # Get the ConfigMap in the `default` Namespace called `clusterregistries` and store. The value of the key
        # must end with a wildcard. Currently assumes there is only a single registry name in the value.
        - name: clusterregistries
          configMap:
            name: clusterregistries
            namespace: default
      preconditions:
        - key: "{{request.operation}}"
          operator: In
          value:
          - CREATE
          - UPDATE
      validate:
        message: This Pod names an image that is not from an approved registry.
        foreach:
        # Create a flattened array of all containers in the Pod wherever they may be.
        - list: "request.object.spec.[initContainers, ephemeralContainers, containers][]"
          deny:
            conditions:
              all:
                # Loop over every image and deny the Pod if any image doesn't match either the allowed registry in the
                # cluster ConfigMap or the annotation on the Namespace where the Pod is destined.
                - key: "{{element.image}}"
                  operator: NotEquals
                  value: "{{nsregistries}}"
                - key: "{{element.image}}"
                  operator: NotIn
                  value: "{{clusterregistries.data.registries}}"
```

Slack convo [here](https://kubernetes.slack.com/archives/CLGR9BJU9/p1639081463233700).
