### ISSUE TITLE
Create CLI test policy for wildcard support in match label selector

### ISSUE THREAD

**Issue by vyankyGH** [kyverno/policies#203]
Related Issue : https://github.com/kyverno/kyverno/issues/2460
PR : https://github.com/kyverno/kyverno/pull/2832

## Supported Patterns

- "*"
- "*pattern"
- "pattern*"
- "pat*tern"
- "* pattern*"

Policy example 
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-image-pull-secret
spec:
  rules:
    - name: add-imagepullsecrets
      exclude:
        resources:
          selector:
            matchLabels:
              strimzi.io/kind: "*"
      match:
        resources:
          kinds:
          - Pod
      mutate:
        patchStrategicMerge:
          spec:
            imagePullSecrets:
            - name: harbor
```
