### ISSUE TITLE
Sample policy to restrict ServiceAccounts to create Pods with only the same SA

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#211]
A ServiceAccount with privileges to create Pods has the ability to create a Pod and set the `serviceAccountName` field to a ServiceAccount other than the one being used to create said Pod. Create a Kyverno policy that prevents this.

**Comment by chipzoller** [comment]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-sa
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: checksa
      match:
        resources:
          kinds:
          - Pod
      preconditions:
        all:
        - key: "{{serviceAccountName}}"
          operator: Equals
          value: "*?"
      validate:
        message: "The ServiceAccount used to create this Pod is confined to using the same account when running the Pod."
        pattern:
          spec:
            serviceAccountName: "{{serviceAccountName}}"
```
