### ISSUE TITLE
Sample policy to add Velero restore policy

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#220]
From Slack thread here, add this Velero policy to block restores to the `kube-system` Namespace.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-restore
spec:
  validationFailureAction: enforce
  rules:
  - name: check-restores
    match:
      resources:
        kinds:
        - Restore
    validate:
      message: "Restore to protected namespace is not allowed!"
      deny:
        conditions:
          all:
          - key: kube-system
            operator: In
            value: "{{ request.object.spec.namespaceMapping | values(@) }}"
```
