### ISSUE TITLE
Don't mutate image registry if it's specified

### ISSUE THREAD

**Issue by shy-Xu** [kyverno/policies#227]
I used this policy: https://kyverno.io/policies/other/prepend_image_registry/prepend_image_registry/

However, I don't want to mutate image registry if I specified a registry, e.g: if image name is library/mysql:latest, I expect to use image "registry.io/library/mysql:latest", if image name is my-registry/library/mysql:latest, I expect to use image "my-registry/library/mysql:latest"

what should I edit the policy? thanks~

**Comment by realshuting** [comment]
Hi @shy-Xu - you can add the [preconditions](https://kyverno.io/docs/writing-policies/preconditions/) to check if the [image registry ](https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images)is empty (Kyverno sets default to `docker.io`) for the above policy.

**Comment by shy-Xu** [comment]
> Hi @shy-Xu - you can add the [preconditions](https://kyverno.io/docs/writing-policies/preconditions/) to check if the [image registry ](https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images)is empty (Kyverno sets default to `docker.io`) for the above policy.

Thank you, but it seems that the [image registry ](https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images) cann't be used in  [preconditions](https://kyverno.io/docs/writing-policies/preconditions/) .

the policy is:
```
preconditions:
      all:
      - key: "{{images.containers.nginx.registry}}"
        operator: Equals
        value: ""
```

the error message :
```
Error from server: error when creating "redirect-registry.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: policy contains invalid variables: Rule "prepend-registry-containers" has forbidden variables. Allowed variables are: {{request.*}}, {{serviceAccountName}}, {{serviceAccountNamespace}}, {{@}} and ones defined by the context
```

**Comment by realshuting** [comment]
I'm testing against the latest kyverno and am able to create the policy.

@shy-Xu - which version of kyverno are you running?

**Comment by shy-Xu** [comment]
Thanks you very much. I change my kyverno version from 1.5.1 to 1.5.4 and am also able to create the policy @realshuting

**Comment by realshuting** [comment]
Great! Can we close this issue?

**Comment by shy-Xu** [comment]
I'm still stuck with this problem. After I add preconditions, I meet a policyviolation warnning and my policy failes to apply on pods. 
```
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: redirect-registry
spec:
  background: false
  rules:
  - name: prepend-registry-containers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      - key: "{{images.containers.*.registry}}"
        operator: Equals
        value: ""
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              image: "sea.hub:5000/{{ images.containers.{{element.name}}.path}}:{{images.containers.{{element.name}}.tag}}"
  - name: prepend-registry-initcontainers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      - key: "{{images.initContainers.*.registry}}"
        operator: Equals
        value: ""
    mutate:
      foreach:
      - list: "request.object.spec.initContainers"
        patchStrategicMerge:
          spec:
            initContainers:
            - name: "{{ element.name }}"
              image: "sea.hub:5000/{{ images.initContainers.{{element.name}}.path}}:{{images.initContainers.{{element.name}}.tag}}"
```

I'm debugging this.

**Comment by shy-Xu** [comment]
Thank you for your answer @chipzoller, then what should I do? I cann't find a suitable policy in [policies page](https://kyverno.io/policies/)

Will you support this and provide a sample?

**Comment by chipzoller** [comment]
I think it's easiest to start over:

* What behavior do you want?
* Provide an example of a resource that should be mutated. Show what it should look like after successful mutation.
* Provide an example of a resource that _should not_ be mutated.
* Explain why in each case.

**Comment by shy-Xu** [comment]
- I want to mutate the image registry if it is not provided, and not mutate the image registry if it is provide.
- An image with name `mysql:latest` should be mutated to `<my-registry-url>/mysql:latest`
- An image with name `docker.io/mysql:latest` should not be mutated
- `mysql:latest` doesn't provide registry url, so we mutate it. However `docker.io/mysql:latest` provides registry url, which means it want a image from `docker.io`, so we should not mutate it

**Comment by chipzoller** [comment]
Try this. It assumes that you will be OK in mutating any images that explicitly begin with `docker.io` as well as those without it (because Kyverno internally translates no registry to `docker.io`). See if it works well. You may need the `1.6-dev-latest` tag for some of the fixes in `foreach`.

```yaml
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prepend-registry
spec:
  background: false
  rules:
  - name: prepend-registry-containers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        preconditions:
          all:
          - key: "{{ element.image | contains(@, 'docker.io/') }}"
            operator: Equals
            value: true
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              image: sea.hub:5000/{{ images.containers."{{element.name}}".name}}:{{images.containers."{{element.name}}".tag}}
  - name: prepend-registry-initcontainers
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      - key: "{{ request.object.spec.initContainers[] || '' | length(@) }}"
        operator: GreaterThan
        value: 0
    mutate:
      foreach:
      - list: "request.object.spec.initContainers"
        preconditions:
          all:
          - key: "{{ element.image | contains(@, 'docker.io/') }}"
            operator: Equals
            value: true
        patchStrategicMerge:
          spec:
            initContainers:
            - name: "{{ element.name }}"           
              image: sea.hub:5000/{{ images.initContainers."{{element.name}}".name}}:{{images.initContainers."{{element.name}}".tag}}
```
