### ISSUE TITLE
Linux Kernel version check policy for CVE-2022-0185

### ISSUE THREAD

**Issue by anubhav888** [kyverno/policies#228]
NIST recently announced a CVE with Linux Kernel where privilege can be escalated and compromise the node. The Kyverno policy should validate for exposed kernel version and generate audit alerts.

- [x] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
- [ Yes, I have verified this policy does not exist] 

**Is your policy request related to a problem? Please describe.**

[(https://security-tracker.debian.org/tracker/CVE-2022-0185).](https://security-tracker.debian.org/tracker/CVE-2022-0185)

The Kyverno policy should validate for exposed kernel version and generate audit alerts.

Validate if the following versions are running on the node where the pod is being deployed

parameters:
  kernelVersions:
    - 5.10.84-1
    - 5.15.5-2
targets:
  - apiGroups:
      - ''
    kinds:
      - Node

kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.nodeInfo.kernelVersion}{"\n"}{end}'

**Comment by chipzoller** [comment]
Seeing an issue in trying to implement this policy.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-kernel
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: kernel-validate
    match:
      resources:
        kinds:
          - Node
    validate:
      message: "Kernel is vulnerable to CVE-2022-0185."
      pattern:
        status:
          nodeInfo:
            # architecture: "!amd644"
            kernelVersion: "!5.10.84-1"
```

Filed https://github.com/kyverno/kyverno/issues/3053

**Comment by chipzoller** [comment]
Even though the above problem needs to be investigated, this policy does work in background mode as tested on Kyverno 1.6.0 (main):

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-kernel
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: kernel-validate
    match:
      resources:
        kinds:
          - Node
    validate:
      message: "Kernel is vulnerable to CVE-2022-0185."
      deny:
        conditions:
          any:
          - key: "{{request.object.status.nodeInfo.kernelVersion}}"
            operator: Equals
            value: "5.10.84-1"
          - key: "{{request.object.status.nodeInfo.kernelVersion}}"
            operator: Equals
            value: "5.15.5-2"
```
