### ISSUE TITLE
[Sample] Validate unique Ingress host plus path combo

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#244]
Awaiting validation on Slack but if not:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress-check
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: check-host-path-combo
      match:
        resources:
          kinds:
            - Ingress
      preconditions:
        all:
        - key: "{{ request.operation }}"
          operator: Equals
          value: CREATE
      context:
        - name: rules
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[].spec.rules[]"
      validate:
        message: "The Ingress host and path combination must be unique across the cluster."
        foreach:
        - list: "request.object.spec.rules[]"
          deny:
            conditions:
              all:
              - key: "{{ element.http.paths[].path }}"
                operator: AnyIn
                value: "{{ rules[?host=='{{element.host}}'][].http.paths[].path }}"
```

Convo: https://kubernetes.slack.com/archives/CLGR9BJU9/p1642539475076300
