### ISSUE TITLE
[Sample] Allow "safe" labels to be added/changed/removed

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#247]
### Problem Statement

In some cases, users are not permitted to change objects but, for operational emergencies, may be allowed to change one or more labels on those objects.

### Solution Description

Write a policy that permits users to add/change/remove a label with only a specific key to different types of resources.

This sample works:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-label-changes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: safe-label
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
          - Job
          - CronJob
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: UPDATE
    validate:
      message: "The only label that may be removed or changed is `breakglass`."
      deny:
        conditions:
          any:
            - key: "{{ request.object.metadata.labels || `{}` |  merge(@, {breakglass:null}) }}"
              operator: NotEquals
              value: "{{ request.oldObject.metadata.labels || `{}` |  merge(@, {breakglass:null}) }}"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
