### ISSUE TITLE
The "subjects" field cannot be used

### ISSUE THREAD

**Issue by oceanweave** [kyverno/policies#290]
### Problem Statement

error: error validating "sa-rule.yaml": error validating data: ValidationError(ClusterPolicy.spec.rules[0].match.any[0].resources): unknown field "subjects" in io.kyverno.v1.ClusterPolicy.spec.rules.match.any.resources; if you choose to ignore these errors, turn validation off with --validate=false

I encountered the above error prompt, but I did the same thing as the official website. I don't understand what caused it. Please take a look. Thank you!

Here are my test cases.

``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-serviceaccount
  annotations:
    policies.kyverno.io/title: Restrict sysctls
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Sysctls can disable security mechanisms or affect all containers on a
      host, and should be disallowed except for an allowed "safe" subset. A
      sysctl is considered safe if it is namespaced in the container or the
      Pod, and it is isolated from other Pods or processes on the same Node.
      This policy ensures that only those "safe" subsets can be specified in
      a Pod.      
spec:
  validationFailureAction: enforce 
  background: true
  rules:
    - name: check-sa
      match:
        any:
        - resources:
            kinds:
            - Pod
            subjects: # this part is the problem
            - kind: User
              name: system:serviceaccount:default:sa-test
      validate:
        message: >-
          Setting additional sysctls above the allowed type is disallowed.
          The field spec.securityContext.sysctls must be unset or not use any other names
          than kernel.shm_rmid_forced, net.ipv4.ip_local_port_range,
          net.ipv4.ip_unprivileged_port_start, net.ipv4.tcp_syncookies and
          net.ipv4.ping_group_range. 
        pattern:
          spec:
            =(securityContext):
              =(sysctls):
                - =(name): "net.ipv4.ip_local_port_range | net.ipv4.ip_unprivileged_port_start | net.ipv4.tcp_syncookies | net.ipv4.ping_group_range"
```

### Solution Description

Want a successful test case

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
What version of Kyverno did you try this on?

**Comment by oceanweave** [comment]
> What version of Kyverno did you try this on?

It shows the version is v2.1.4
``` yaml
Node:         kind-control-plane/172.18.0.2
Start Time:   Tue, 22 Feb 2022 16:27:42 +0800
Labels:       app=kyverno
              app.kubernetes.io/component=kyverno
              app.kubernetes.io/instance=kyverno
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kyverno
              app.kubernetes.io/part-of=kyverno
              app.kubernetes.io/version=v2.1.4
              helm.sh/chart=kyverno-v2.1.4
              pod-template-hash=6d94754db4
Annotations:  <none>
Status:       Running
IP:           10.244.0.2
IPs:
  IP:           10.244.0.2
Controlled By:  ReplicaSet/kyverno-6d94754db4
Init Containers:
  kyverno-pre:
    Container ID:   containerd://5205bc01c42d76d23efe278d53aac930f0852321bd3ac856e943309c67cd07cb
    Image:          ghcr.io/kyverno/kyvernopre:v1.5.2```

**Comment by chipzoller** [comment]
This is Kyverno 1.5. The policy supports minimum of 1.6.0 as stated in the annotation.

**Comment by oceanweave** [comment]
> This is Kyverno 1.5. The policy supports minimum of 1.6.0 as stated in the annotation.

I just upgraded, but I still encounter the same problem. Can you provide an available test case? I'll test it. I can't find a complete test case on the official website

 
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/24841416/159144628-58ba52b2-10cf-4188-b66f-e1da53211bad.png">

**Comment by oceanweave** [comment]
https://kyverno.io/docs/writing-policies/match-exclude/

The above link refers to the use of "subjects" field, but this field is not found by using "kubectl explain", so "validate error" always appears. So is the field "subjects" currently under test and cannot be used normally?

``` yaml
spec:
  rules:
  - name: no-LoadBalancer
    match:
      any:
      - resources:
          names: 
          - "prod-*"
          - "staging"
          kinds:
          - Service
      - resources:
          kinds:
          - Service
          subjects:
          - kind: User
            name: dave
```



```
╰─ kubectl  explain policy.spec.rules.match.resources
KIND:     Policy
VERSION:  kyverno.io/v1

RESOURCE: resources <Object>

DESCRIPTION:
     ResourceDescription contains information about the resource being created
     or modified. Requires at least one tag to be specified when under
     MatchResources. Specifying ResourceDescription directly under match is
     being deprecated. Please specify under "any" or "all" instead.

FIELDS:
   annotations	<map[string]string>
     Annotations is a map of annotations (key-value pairs of type string).
     Annotation keys and values support the wildcard characters "*" (matches
     zero or many characters) and "?" (matches at least one character).

   kinds	<[]string>
     Kinds is a list of resource kinds.

   name	<string>
     Name is the name of the resource. The name supports wildcard characters "*"
     (matches zero or many characters) and "?" (at least one character).

   names	<[]string>
     Names are the names of the resources. Each name supports wildcard
     characters "*" (matches zero or many characters) and "?" (at least one
     character). NOTE: "Name" is being deprecated in favor of "Names".

   namespaceSelector	<Object>
     NamespaceSelector is a label selector for the resource namespace. Label
     keys and values in `matchLabels` support the wildcard characters `*`
     (matches zero or many characters) and `?` (matches one character).Wildcards
     allows writing label selectors like ["storage.k8s.io/*": "*"]. Note that
     using ["*" : "*"] matches any key and value but does not match an empty
     label set.

   namespaces	<[]string>
     Namespaces is a list of namespaces names. Each name supports wildcard
     characters "*" (matches zero or many characters) and "?" (at least one
     character).

   selector	<Object>
     Selector is a label selector. Label keys and values in `matchLabels`
     support the wildcard characters `*` (matches zero or many characters) and
     `?` (matches one character). Wildcards allows writing label selectors like
     ["storage.k8s.io/*": "*"]. Note that using ["*" : "*"] matches any key and
     value but does not match an empty label set.
```

> This is Kyverno 1.5. The policy supports minimum of 1.6.0 as stated in the annotation.

**Comment by chipzoller** [comment]
Your indentation is off when you added `subjects` to the [restrict-sysctls policy](https://kyverno.io/policies/pod-security/baseline/restrict-sysctls/restrict-sysctls/).

```
$ k explain policy.spec.rules.match.any
KIND:     Policy
VERSION:  kyverno.io/v1

RESOURCE: any <[]Object>

DESCRIPTION:
     Any allows specifying resources which will be ORed

     ResourceFilter allow users to "AND" or "OR" between resources

FIELDS:
   clusterRoles <[]string>
     ClusterRoles is the list of cluster-wide role names for the user.

   resources    <Object>
     ResourceDescription contains information about the resource being created
     or modified.

   roles        <[]string>
     Roles is the list of namespaced role names for the user.

   subjects     <[]Object>
     Subjects is the list of subject names like users, user groups, and service
     accounts.
```

**Comment by oceanweave** [comment]
> Your indentation is off when you added `subjects` to the [restrict-sysctls policy](https://kyverno.io/policies/pod-security/baseline/restrict-sysctls/restrict-sysctls/).
> 
> ```
> $ k explain policy.spec.rules.match.any
> KIND:     Policy
> VERSION:  kyverno.io/v1
> 
> RESOURCE: any <[]Object>
> 
> DESCRIPTION:
>      Any allows specifying resources which will be ORed
> 
>      ResourceFilter allow users to "AND" or "OR" between resources
> 
> FIELDS:
>    clusterRoles <[]string>
>      ClusterRoles is the list of cluster-wide role names for the user.
> 
>    resources    <Object>
>      ResourceDescription contains information about the resource being created
>      or modified.
> 
>    roles        <[]string>
>      Roles is the list of namespaced role names for the user.
> 
>    subjects     <[]Object>
>      Subjects is the list of subject names like users, user groups, and service
>      accounts.
> ```

It has been solved. Thank you very much!
As you said, the "subjects" field is indented incorrectly. It is recommended to update the wrong test case in this link（https://kyverno.io/docs/writing-policies/match-exclude/） because I was misled.


``` yaml
spec:
  rules:
  - name: no-LoadBalancer
    match:
      any:
      - resources:
          names: 
          - "prod-*"
          - "staging"
          kinds:
          - Service
      - resources:
          kinds:
          - Service
      subjects:
      - kind: User
        name: dave
```

> match.any[0] will now match on only Services that begin with the name “prod-” OR have the name “staging” and not those which begin with “dev-” or any other prefix. match.any[1] will match all Services being created by the dave user regardless of the name of the Service. And since these two are specified under the any key, the entire rule will act on all Services with names prod-* or staging OR on all services being created by the dave user. In both match and exclude statements, [wildcards](https://kyverno.io/docs/writing-policies/validate/#wildcards) are supported to make selection more flexible.



The description of this official example is as shown above. At present, it is found that "subjects" and "resources" are of the same level, so a problem arises: since there can be multiple "resources" fields, does a "subjects" field act on all "resources" fields or adjacent "resources" fields?
According to the understanding of the same level of the field, I think the "subjects" field acts on all "resources" fields, so the meaning will be different from the official use case: 
> the entire rule will act on all Services with names prod-* or staging ( by the dave user) OR on all services being created by the dave user.

**Comment by chipzoller** [comment]
> As you said, the "subjects" field is indented incorrectly. It is recommended to update the wrong test case in this link（[https://kyverno.io/docs/writing-policies/match-exclude/](https://kyverno.io/docs/writing-policies/match-exclude/%EF%BC%89) because I was misled.

Thank you, fixed!

Since `match.any` is an array of objects, and `subjects` is an object, including both `resources` and `subjects` under an `any` block is an OR logic. It will apply to any of those.

**Comment by oceanweave** [comment]
> > As you said, the "subjects" field is indented incorrectly. It is recommended to update the wrong test case in this link（[https://kyverno.io/docs/writing-policies/match-exclude/](https://kyverno.io/docs/writing-policies/match-exclude/%EF%BC%89) because I was misled.
> 
> Thank you, fixed!
> 
> Since `match.any` is an array of objects, and `subjects` is an object, including both `resources` and `subjects` under an `any` block is an OR logic. It will apply to any of those.


I'm sorry to bother you again. At present, there is no format error in the "subjects" field, but it doesn't seem to work. 

The first yaml file is: "this restriction rule applies when creating pod resources and the user is kind kind", and the second yaml file is "test file that violates the rule". 

However, no matter the "kind kind" user or the "yeah" user is used, an error will be reported when creating the test yaml. According to my understanding, "yeah" should not report an error when it is created, because it does not meet the limit range of the "subjects" field.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/24841416/159200909-43dca8a9-4cbf-4f78-8b70-ea65a4600876.png">

``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-serviceaccount
  annotations:
    policies.kyverno.io/title: Restrict sysctls
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Sysctls can disable security mechanisms or affect all containers on a
      host, and should be disallowed except for an allowed "safe" subset. A
      sysctl is considered safe if it is namespaced in the container or the
      Pod, and it is isolated from other Pods or processes on the same Node.
      This policy ensures that only those "safe" subsets can be specified in
      a Pod.      
spec:
  validationFailureAction: enforce 
  background: true
  rules:
    - name: check-sa
      match:
        all:
        - resources:
            kinds:
            - Pod
        subjects:
          - kind: User
            name: kind-kind
      validate:
        message: >-
          Setting additional sysctls above the allowed type is disallowed.
          The field spec.securityContext.sysctls must be unset or not use any other names
          than kernel.shm_rmid_forced, net.ipv4.ip_local_port_range,
          net.ipv4.ip_unprivileged_port_start, net.ipv4.tcp_syncookies and
          net.ipv4.ping_group_range. 
        pattern:
          spec:
            =(securityContext):
              =(sysctls):
                - =(name): "net.ipv4.ip_local_port_range | net.ipv4.ip_unprivileged_port_start | net.ipv4.tcp_syncookies | net.ipv4.ping_group_range"

```

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    sysctls:
    - name: kernel.shm_rmid_forced
      value: '1' 
  containers:
  - name: sec-ctx-demo
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      allowPrivilegeEscalation: false

```
