### ISSUE TITLE
re-organize tests

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#3]
would be good to allow multiple success and failure cases and automate execution.

**Comment by chipzoller** [comment]
Can you expound on what you mean here, at least on the "multiple success and failure cases"?

**Comment by realshuting** [comment]
Will this repo eventually replace what we have in https://github.com/kyverno/kyverno/tree/main/samples? 

How can we trigger the tests again each push in kyverno/kyverno?

**Comment by chipzoller** [comment]
Yes, that's the idea. We need to figure out the test scenario. Eventually, it'd be nice if every policy had an accompanying test manifest that could be used in a pipeline.

**Comment by JimBugwadia** [comment]
@realshuting - we can add this repo to the kyverno/kyverno repo as a [sub-module](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and invoke tests.

@chipzoller - was thinking that we can have a `test.yaml` that looks something like this:

```yaml
tests:
  - policy: <path to policy>
    resource: <path to resource>
    results:
        status: pass
        object: <optional mutation results>
```

The idea would be to allow testing different cases and variations.

May be good to organize each policy in its own sub-folder with this YAML, a kustomization.yaml, and the resource YAMLs.

If we can define a good structure everyone can then use the Kyverno CLI to execute tests:

```
kyverno test
````
