### ISSUE TITLE
[Bug] Image always being blocked from allowed registry domain rule

### ISSUE THREAD

**Issue by ChrisJBurns** [kyverno/policies#300]
### Kyverno Version

1.6.x

### Kubernetes Version

1.21.x

### Kubernetes Platform

AKS

### Description

Kyverno is running in my cluster, I am using the [following policy](https://kyverno.io/policies/best-practices/restrict_image_registries/restrict_image_registries/).

```yaml
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: validate-registries
  namespace: create
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.3.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from unknown, public registries can be of dubious quality and may not be
      scanned and secured, representing a high degree of risk. Requiring use of known, approved
      registries helps reduce threat exposure by ensuring image pulls only come from them. This
      sample validates that container images only originate from the registry `eu.foo.io` or
      `bar.io`.      
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: validate-registries
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Images to this namespaces may only come from our internal registry."
      pattern:
        spec:
          containers:
          - image: "harbor.domain.co.uk/*"
```

In combination with an image signature verification policy (that works fine when there is and isn't an image signature). However, I'm not sure why, but when I try to deploy the image into the cluster, I get the following:

```bash
> kubectl run test-project-signed  --image=harbor.domain.co.uk/create/test-project:726b3f3-dev -n create --kubeconfig $HOME/.kube/config/apps_config
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request:

resource Pod/create/test-project-signed was blocked due to the following policies

validate-registries:
  validate-registries: 'validation error: Images to this namespaces may only come
    from our internal registry. Rule validate-registries failed at path /spec/containers/1/image/'
```

I'm not entirely sure why it is blocking the image when it's definitely the right Harbor URL as without the policy, it deploys fine - but with it, it blocks the image, when it shouldn't?

P.S I may be stating the obvious but `harbor.domain.co.uk` is not the real URL.

### Steps to reproduce

1. Install Harbor
2. Install Kyverno
3. Add policy that only allows from specific registries as show above
4. Push image into Harbor
5. Try to push the private image into Kubernetes
6. Kyverno - if you get the same error as me - will block it from that registry, instead of allowing it.

### Expected behavior

I expect the image from the private registry to be deployed to the cluster without Kyverno blocking it.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
