### ISSUE TITLE
[Sample] Policies for nginx-ingress vulnerabilities CVE-2021-25745 and CVE-2021-25746

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#301]
## CVE-2021-25745: Ingress-nginx `path` can be pointed to service account token file

Issue Details
A security issue was discovered in [ingress-nginx](https://github.com/kubernetes/ingress-nginx) where a user that can create or update ingress objects can use the `spec.rules[].http.paths[].path` field of an Ingress object (in the `networking.k8s.io` or `extensions` API group) to obtain the credentials of the ingress-nginx controller. In the default configuration, that credential has access to all secrets in the cluster.

This issue has been rated High (CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L), and assigned CVE-2021-25745.

Affected Components and Configurations
This bug affects ingress-nginx. If you do not have ingress-nginx installed on your cluster, you are not affected. You can check this by running `kubectl get po -n ingress-nginx`.

Multitenant environments where non-admin users have permissions to create Ingress objects are most affected by this issue.

Affected Versions
<v1.2.0

Fixed Versions
v1.2.0-beta.0

v1.2.0

Mitigation
If you are unable to roll out the fix, this vulnerability can be mitigated by implementing an admission policy that restricts the `spec.rules[].http.paths[].path` field on the [networking.k8s.io](http://networking.k8s.io/)/Ingress resource to known safe characters (see the newly added rules, or the suggested value for annotation-value-word-blocklist).

Detection
If you find evidence that this vulnerability has been exploited, please contact [security@kubernetes.io](mailto:security@kubernetes.io)

Additional Details
See ingress-nginx Issue [#8502 ](https://github.com/kubernetes/ingress-nginx/issues/8502)for more details.

Acknowledgements
This vulnerability was reported by Gafnit Amiga.

## CVE-2021-25746: Ingress-nginx directive injection via annotations

Issue Details
A security issue was discovered in [ingress-nginx](https://github.com/kubernetes/ingress-nginx) where a user that can create or update ingress objects can use `.metadata.annotations` in an Ingress object (in the `networking.k8s.io` or `extensions` API group) to obtain the credentials of the ingress-nginx controller. In the default configuration, that credential has access to all secrets in the cluster.

This issue has been rated High ([CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L)), and assigned CVE-2021-25746.

Affected Components and Configurations
This bug affects ingress-nginx. If you do not have ingress-nginx installed on your cluster, you are not affected. You can check this by running `kubectl get po -n ingress-nginx`.

Multitenant environments where non-admin users have permissions to create Ingress objects are most affected by this issue.

Affected Versions
<v1.2.0

Fixed Versions
v1.2.0-beta.0

v1.2.0

Mitigation
If you are unable to roll out the fix, this vulnerability can be mitigated by implementing an admission policy that restricts the `metadata.annotations` values to known safe (see the newly added [rules](https://github.com/kubernetes/ingress-nginx/blame/main/internal/ingress/inspector/rules.go), or the suggested value for [annotation-value-word-blocklist](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotation-value-word-blocklist)).

Detection
If you find evidence that this vulnerability has been exploited, please contact [security@kubernetes.io](mailto:security@kubernetes.io)

Additional Details
See ingress-nginx Issue [#8503](https://github.com/kubernetes/ingress-nginx/issues/8503) for more details.

Acknowledgements
This vulnerability was reported by Anthony Weems, and separately by jeffrey&oliver.

### Solution Description

Sample policy that implements 

https://github.com/kubernetes/ingress-nginx/blame/main/internal/ingress/inspector/rules.go

Sample policy that implements

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotation-value-word-blocklist

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
See this below. Seems to work on all cases I can come up with. Needs polish, annotations, appropriate names, and a good description.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress-contains
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: cve-2021-25745
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: CREATE
    validate:
      message: "Ingress paths cannot use forbidden strings."
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'load_module') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'lua_package') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'_by_lua_') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'location') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'root') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'proxy_pass') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'serviceaccount') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'{') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'}') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'alias') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'/etc/') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.spec.rules[].http.paths[].path.contains(@,'/var/run/secrets') }}"
            operator: AnyIn
            value:
              - true
  - name: cve-2021-25746
    match:
      any:
      - resources:
          kinds:
          - Ingress
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: CREATE
    validate:
      message: "Ingress annotations cannot use forbidden strings."
      deny:
        conditions:
          any:
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'load_module') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'lua_package') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, '_by_lua') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'location') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'root') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'proxy_pass') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'serviceaccount') }}"
            operator: AnyIn
            value:
              - true
          ## If the check for {, }, ', and " are in place, this will fail validation since the API server
          ## will add the kubectl.kubernetes.io/last-applied-configuration containing these chars since
          ## it represents the entirety of the object as JSON.
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, 'alias') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, '/etc') }}"
            operator: AnyIn
            value:
              - true
          - key: "{{ request.object.metadata.annotations.values(@)[].contains(@, '/var/run/secrets') }}"
            operator: AnyIn
            value:
              - true
```

**Comment by chipzoller** [comment]
Some Ingress scaffolding you can use:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-bad-ingress
  annotations:
    foo: foo
    bar: /foo/bar
spec:
  rules:
  - host: https-good.good.com
    http:
      paths:
      - path: /cart
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
  # - host: https-good.bad.com
  #   http:
  #     paths:
  #     - path: '/foo/bar/a_by_lua_boo'
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: service1
  #           port:
  #             number: 80
```
