### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sriramss** [kyverno/policies#303]
### Kyverno Version

1.6.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

Bare metal

### Description

Kyverno is running in my cluster and I am running the following policy -
```
apiVersion: [kyverno.io/v1]
kind: Policy
metadata:
  name: mutation-policy
  namespace: services
  annotations:
    [policies.kyverno.io/title](http://policies.kyverno.io/title): Mutate pod and container security contexts
    [policies.kyverno.io/category](http://policies.kyverno.io/category): Pod Security Standards (Baseline)
    [kyverno.io/kyverno-version](http://kyverno.io/kyverno-version): 1.6.0
    [policies.kyverno.io/minversion](http://policies.kyverno.io/minversion): 1.6.0
    [policies.kyverno.io/subject](http://policies.kyverno.io/subject): Pod
    [policies.kyverno.io/description](http://policies.kyverno.io/description): >-
      Highly restrictive mutate policy setting container security context
spec:
  rules:
  - name: set-container-security-context
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            [app.kubernetes.io/managed-by](http://app.kubernetes.io/managed-by): Helm
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - (name): "{{element.name}}"
              securityContext:
                +(runAsUser): 65534
                +(runAsGroup): 65534
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                privileged: false
```
I have a total of 28 policies(similar to the above) in my cluster. These policies are not enforced on any workloads but, I see kyverno is generating false-positive events like this -

```
ncn-m001:~ # kubectl get events -A | grep Policy
services               59m         Normal    PolicyApplied  policy/mutation-policy  Rule(s) ' ' successfully applied on resource Pod/services/cray-console-data-postgres-1
```

whereas an actual event(when policy gets applied to the workload) looks like this -
```
services               59m         Normal    PolicyApplied  policy/mutation-policy  Rule(s) '[set-container-security-context] ' successfully applied on resource Pod/services/cray-console-data-postgres-1
```
These false-positive events are consuming the buffer space. 

### Steps to reproduce

1. Install Kyverno
2. Add multiple policies pointing to different workloads
3. Check events before restarting the workloads (**Note:** Restart is required for the policy to be enforced)

### Expected behavior

I expect kyverno to not generate any events until policy gets enforced.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
