### ISSUE TITLE
Check deprecated APIs

### ISSUE THREAD

**Issue by smcaine** [kyverno/policies#312]
This ClusterPolicy unfortunately breaks if any of the api's are deprecated, so for example this policy wont get applied to v1.22.x k8s due to following error:\

```
err: kind 'ValidatingWebhookConfiguration' not found in apiVersion 'admissionregistration.k8s.io/v1beta1
```

Would be good to have another suggested way of doing this in the docs.. like what was posted [here](https://github.com/kyverno/kyverno/issues/3261#issuecomment-1068822279) to avoid apply failures, something like:

```yaml
rules:
  - name: validate-v1-22-removals
    match:
      resources:
        kinds:
        - "*"
    preconditions:
      all:
      - key: "{{request.object.apiVersion}}"
        operator: In
        value:
        - admissionregistration.k8s.io/v1beta1
        - apiextensions.k8s.io/v1beta1
        - apiregistration.k8s.io/v1beta1
        - authentication.k8s.io/v1beta1
```

As we use Kustomization to apply a load of other policies, this causes the kustomize to fail and no other policies then get applied.
