### ISSUE TITLE
[Bug] disallow-capabilities-strict allows add NET_BIND_SERVICE without drop ALL

### ISSUE THREAD

**Issue by joebowbeer** [kyverno/policies#346]
### Kyverno Version

1.7.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

EKS

### Description

The PSS/restricted disallow-capabilities-strict policy states:

> Adding capabilities other than `NET_BIND_SERVICE` is disallowed. In addition, all containers must explicitly drop `ALL` capabilities.

However, none of the test cases that add NET_BIND_SERVICE drop _any_ capabilities, let alone ALL.

For example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: addcap-goodpod02
spec:
  containers:
  - name: container01
    image: dummyimagename
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
```

### Steps to reproduce

Eyeball the source:
* https://github.com/kyverno/policies/blob/main/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml
* https://github.com/kyverno/policies/blob/main/pod-security/restricted/disallow-capabilities-strict/resource.yaml#L1289

### Expected behavior

addcap-goodpod02 should fail.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
