### ISSUE TITLE
[Sample] Add label from Dockerfile build as container env var

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#362]
### Problem Statement

Apps in containers might need access to the value of a label defined at build time either statically in a Dockerfile or set via CI/CD system. Kyverno can inject this value as an environment variable.

### Solution Description

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-image-data
spec:
  rules:
  - name: add-env-maintainer
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: NotEquals
        value: DELETE
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        context: 
        - name: maintainer
          imageRegistry: 
            reference: "{{ element.image }}"
            jmesPath: "configData.config.Labels.maintainer || ''"
        preconditions:
          all:
          - key: "{{maintainer}}"
            operator: NotEquals
            value: ""
        patchesJson6902: |-
          - op: add
            path: "/spec/containers/{{elementIndex}}/env/-"
            value: {"name":"MAINTAINER","value":"{{maintainer}}"}
```

### Example "Good" Resource

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mypod
  # annotations:
  #   foo: bar
  name: mypod
spec:
  automountServiceAccountToken: false
  containers:
  - name: container03
    image: ghcr.io/kyverno/kyverno:latest
    env:
    - name: FOO
      value: bar
  - name: container04
    image: busybox:latest
```

### Slack discussion

https://kubernetes.slack.com/archives/C09NXKJKA/p1658499989465959

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
