### ISSUE TITLE
[Sample] Label Nodes with CRI

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#363]
### Problem Statement

CRI engines log in different formats. Loggers deployed as DaemonSets don't know which format to apply because they can't see this information. By Kyverno writing a label to each node with its runtime, loggers can use node label selectors to know which parsing logic to use.

### Solution Description

Add this policy:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-node
  annotations:
    note: Need to remove the Node resource filter and grant the Kyverno SA permission to update Nodes.
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: label-node-containerd
      match:
        any:
        - resources:
            kinds:
            - Node
      mutate:
        targets:
        - apiVersion: v1
          kind: Node
          name: "{{ request.object.metadata.name }}"
        patchStrategicMerge:
          metadata:
            labels:
              runtime: containerd
          status:
            nodeInfo:
              <(containerRuntimeVersion): containerd*
    - name: label-node-docker
      match:
        any:
        - resources:
            kinds:
            - Node
      mutate:
        targets:
        - apiVersion: v1
          kind: Node
          name: "{{ request.object.metadata.name }}"
        patchStrategicMerge:
          metadata:
            labels:
              runtime: docker
          status:
            nodeInfo:
              <(containerRuntimeVersion): docker*
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
