### ISSUE TITLE
Restrict Binding to Cluster-Admin

### ISSUE THREAD

**Issue by dschunack** [kyverno/policies#365]
Hi, 

the policy is not correct. "name:" is missing under RoleRef.

```yaml
      validate:
        message: "Binding to cluster-admin is not allowed."
        pattern:
          roleRef: 
            name: "!cluster-admin"
```
I will create a PR to for this with the correct Code.
