### ISSUE TITLE
How can I exclude  certain namespaces from policies

### ISSUE THREAD

**Issue by jyotibhanot** [kyverno/policies#382]
### Problem Statement

I am trying to implement `LimitRange` on specific namespaces. But I would like to exclude few namespaces. How can I achieve that. Tried doing this:

```

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-ns-limits
  annotations:
    policies.kyverno.io/title: Add Limits
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: LimitRange
    policies.kyverno.io/description: >-
      To provide default resource consumption limits for Pods,
      LimitRange resources are recommended. This policy will generate 
      LimitRange resources when a new Namespace is created.
spec:
  rules:
  - name: generate-limitrange
    match:
      resources:
        kinds:
        - Namespace
    exclude:
      any:
      - namespaces:
        - kube-system
        - kube-node-lease
    generate:
      kind: LimitRange
      name: default-limitrange
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          limits:
          - max:
              cpu: 1
              memory: 4Gi
            type: Pod
```

Any leads would be highly recommended

### Solution Description

A solution that would help to achieve the above scenario

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Your match and exclude blocks would look like this:

```yaml
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - kube-system
          - kube-node-lease
          - sample
```

Also note that by default, Kyverno will exclude `kube-system` and `kube-node-lease` Namespaces automatically. This means you don't need to exclude them again in a policy. The exception would be if you removed the relevant entries from the [resource filter](https://main.kyverno.io/docs/installation/#resource-filters) in the ConfigMap.

Closing but feel free to respond or come to the #kyverno channel on Kubernetes Slack.
