### ISSUE TITLE
Verify Flux Sources

### ISSUE THREAD

**Issue by zensqlmonitor** [kyverno/policies#401]
Kyverno Version
1.7.x

Kubernetes Version
1.23.x

Kubernetes Platform
EKS

Description

When trying to do a Kustomization reconciliation with Flux, resources of kinds ImageRepository is not accepted (works for HelmRepository and GitRepository)

E0924 16:06:30.959019       1 admission.go:95] WebhookServer/PolicyValidationWebhook "msg"="policy validation errors" "error"="the kind defined in the any match resource is invalid: unable to convert GVK to GVR for kinds [ImageRepository], err: kind 'ImageRepository' not found in apiVersion ''" "gvk"="kyverno.io/v1, Kind=ClusterPolicy" "kind"={"group":"kyverno.io","version":"v

Policy:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-repositories
  annotations:
    policies.kyverno.io/title: Verify Flux Sources
    policies.kyverno.io/category: Flux
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.7.3, 1.8.0-rc2
    policies.kyverno.io/minversion: 1.7.3
    kyverno.io/kubernetes-version: "1.23-1.24"
    policies.kyverno.io/subject: ImageRepository
    policies.kyverno.io/description: >-
      Flux source APIs include a number of different sources such as
      GitRepository, Bucket, HelmRepository, and ImageRepository resources. Each of these
      by default can be pointed to any location. In a production environment,
      it may be desired to restrict these to only known sources to prevent
      accessing outside sources. This policy verifies that each of the Flux
      sources comes from a trusted location.
spec:  
  validationFailureAction: audit # Change to 'enforce' once the specific org url is set.
  rules:
    - name: MyOrg-image-repositories-only
      match:
        any:
        - resources:
            kinds:
              - ImageRepository
      exclude:
        any:
        - resources:
            namespaces:
              - flux-system
              - kube-system
      validate:
        message: ".spec.image must be from an image repository in the org X"
        pattern:
          spec:
            image: "XXX?*" 
```
