### ISSUE TITLE
[Sample] Kubeops Config Syncer Secret Generation From Rancher CAPI Secret

### ISSUE THREAD

**Issue by ron1** [kyverno/policies#418]
### Problem Statement

The AppsCode Config Syncer supports syncing ConfigMaps/Secrets across Clusters. This feature requires a pre-existing kubeconfig Secret described [here:](https://appscode.com/products/kubed/v0.12.0/guides/config-syncer/inter-cluster/#deploy-kubed). The Helm chart for this tool has a property `config.kubeconfigContent` which is used to create the above secret if it is provided.

The proposed Kyverno Generate policy entitled `config-syncer-secret-generation-from-rancher-capi` is intended to automate the generation of this kubeconfig Secret on Rancher Management Clusters so that ConfigMaps/Secrets can easily be synced to downstream clusters.

### Solution Description

The metadata for the proposed ClusterPolicy is included below:

```
kind: ClusterPolicy
metadata:
  name: config-syncer-secret-generation-from-rancher-capi
  annotations:
    policies.kyverno.io/title: Kubeops Config Syncer Secret Generation From Rancher CAPI Secret
    policies.kyverno.io/category: Kubeops
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Secret
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      This policy generates and synchronizes a Kubeops Config Syncer merged kubeconfig
      Secret from Rancher managed cluster CAPI secrets. This kubeconfig Secret is
      required by the Kubeops Config Syncer for it to sync ConfigMaps/Secrets from
      the Rancher management cluster to downstream clusters.
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
