### ISSUE TITLE
[Bug] Unique Ingress Host 

### ISSUE THREAD

**Issue by cuishuyuanCode** [kyverno/policies#422]
### Kyverno Version

1.7.4

### Kubernetes Version

1.24.x

### Kubernetes Platform

Other (specify in description)

### Description

when use the unique-ingress-host policy and create a ingress,

I see a fail report message

"The Ingress host name must be unique."

but my ingress host name is unique

### Steps to reproduce

1.Create and apply the Policy
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
  annotations:
    policies.kyverno.io/title: Unique Ingress Host
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/minversion: 1.3.2
    policies.kyverno.io/description: >-
      An Ingress host is a URL at which services may be made available externally. In most cases,
      these hosts should be unique across the cluster to ensure no routing conflicts occur.
      This policy checks an incoming Ingress resource to ensure its hosts are unique to the cluster.
      It also ensures that only a single host may be specified in a given manifest.      
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: check-single-host
      match:
        resources:
          kinds:
            - Ingress
      context:
        - name: hosts
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[].spec.rules[].host"
      preconditions:
        all:
        - key: "{{ request.operation }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host }}"
          operator: In
          value: "{{ hosts }}"
      validate:
        message: "The Ingress host name must be unique."
        deny: {}
    - name: deny-multiple-hosts
      match:
        resources:
          kinds:
            - Ingress
      preconditions:
        all:
        - key: "{{ request.operation }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host | length(@)}}"
          operator: GreaterThan
          value: 1
      validate:
        message: "An Ingress resource may only contain a single host entry."
        deny: {}
```
2.Create and apply the Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kyverno-host
spec:
  rules:
  - host: www.kyverno.com
    http:
      paths:
      - pathType: Prefix
        path: "/kyverno"
        backend:
          service:
            name: service1
            port:
              number: 80

```
i will see a fail report about the policy message.
![image](https://user-images.githubusercontent.com/101328588/195746216-a949f5d7-b384-4cba-8f30-e34ce31c8b1d.png)
but my ingress host is unique
![image](https://user-images.githubusercontent.com/101328588/195746315-4ee0760f-457d-4385-9b30-2173e1ac291d.png)

### Expected behavior

I think the policy will be passed

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@cuishuyuanCode I cannot reproduce this with Kyverno 1.7.5. When I test a cluster that has no prior Ingress resources, create this policy, and create your sample Ingress, the policy report is a `Skip`. In 1.8.0 this is a `Pass`.

**Comment by cuishuyuanCode** [comment]
> @cuishuyuanCode I cannot reproduce this with Kyverno 1.7.5. When I test a cluster that has no prior Ingress resources, create this policy, and create your sample Ingress, the policy report is a `Skip`.



> @cuishuyuanCode I cannot reproduce this with Kyverno 1.7.5. When I test a cluster that has no prior Ingress resources, create this policy, and create your sample Ingress, the policy report is a `Skip`.

i have problem with kyverno at 1.7.4.

**Comment by cuishuyuanCode** [comment]
I find that istio ingress affects ingress policy

**Comment by cuishuyuanCode** [comment]
I don't know is this normal?

**Comment by chipzoller** [comment]
I'm not understanding why this is a problem for you. The policy does work as designed. If you're finding that it doesn't, I need a way to reproduce this on my end. Please supply more details here.

**Comment by cuishuyuanCode** [comment]
1.i create and apply policy
2.create and apply ingress
3.
````
kubectl get polr -A
````
now,i get the result is skip.
![image](https://user-images.githubusercontent.com/101328588/196578115-2e45f2ec-7b09-4458-8440-e7c634631ed8.png)

4.delete ingress
````
kubectl delete --all ingress -n test
````
now, my ingress is empty
![image](https://user-images.githubusercontent.com/101328588/196578264-03c9c364-b636-45b5-b356-27c3cbc82393.png)

5.now,i apply the ingress again
````
kubectl apply -f ingress.yaml
````
6.get the policy report
![image](https://user-images.githubusercontent.com/101328588/196578825-e910b465-80c5-412d-b0e3-24720dc938be.png)

i think it's will pass or skip , but result is fail ,

**Comment by cuishuyuanCode** [comment]
if i delete ingress and wait about 5minutes,now create ingress the result is skip,
If I delete the ingress and immediately recreate it, the result is fail

**Comment by cuishuyuanCode** [comment]
kyverno 1.8.1-rc2 also has the problem.

### **Steps to reproduce**
1.create and apply policy
```
kubectl apply -f unique-ingress-host.yaml
```
unique-ingress-host.yaml
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
  annotations:
    policies.kyverno.io/title: Unique Ingress Host
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/minversion: 1.3.2
    policies.kyverno.io/description: >-
      An Ingress host is a URL at which services may be made available externally. In most cases,
      these hosts should be unique across the cluster to ensure no routing conflicts occur.
      This policy checks an incoming Ingress resource to ensure its hosts are unique to the cluster.
      It also ensures that only a single host may be specified in a given manifest.      
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: check-single-host
      match:
        resources:
          kinds:
            - Ingress
      context:
        - name: hosts
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[].spec.rules[].host"
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host }}"
          operator: In
          value: "{{ hosts }}"
      validate:
        message: "The Ingress host name must be unique."
        deny: {}
    - name: deny-multiple-hosts
      match:
        resources:
          kinds:
            - Ingress
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host | length(@)}}"
          operator: GreaterThan
          value: 1
      validate:
        message: "An Ingress resource may only contain a single host entry."
        deny: {}

```

2.see the ingress is empty
![image](https://user-images.githubusercontent.com/101328588/197126358-91abbf1e-2e4b-441f-91fb-82586602ee85.png)

3.create and apply ingress
```
kubectl apply -f ingress-host.yaml
```
ingress-host.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: www.kyverno.com
    http:
      paths:
      - pathType: Prefix
        path: "/kyverno"
        backend:
          service:
            name: service1
            port:
              number: 80
```
4.my ingress is unique
![image](https://user-images.githubusercontent.com/101328588/197126151-af7281a8-1b16-4e44-8c9f-55ef1fc286fe.png)

**According to the policy description, Policy report result will be passed or skip** 

5.get policy report 
```
kubectl get polr -A
```
my policy report has a fail, I think it's will be passed or skip. (Sometimes the policy report for this step is skip, Proceed to the next step)
![image](https://user-images.githubusercontent.com/101328588/197127018-5f9c9b95-a7c2-497c-95e7-4dc666123ab3.png)

6.delete the ingress 
```
kubectl delete --all ingress
```
now, My ingress is empty
![image](https://user-images.githubusercontent.com/101328588/197129657-9ff2529c-48e7-4726-a3e0-4678f9421026.png)

7.apply the ingress again
```
kubectl apply -f ingress-host.yaml
```
8.get policy report 
```
kubectl get polr -A
```
![image](https://user-images.githubusercontent.com/101328588/197130262-9636ebf6-58e2-4728-a008-405fc3759bc4.png)

**According to the policy description, Policy report result will be passed or skip, But now has a fail**

if you policy report is skip or pass, you can repeat operations step 6~8，you will see the policy report has a fail.

**Comment by cuishuyuanCode** [comment]
And I find that if I use ```configMap``` instead of ```apiCall```, the policy report will not have this problem.

**Comment by chipzoller** [comment]
Thanks for the report. I found the issue. It's outdated policy language which is somehow copying the value of the ingress hosts from the resource into the results of the API call. This updated version works. I will fix this immediately in the library.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
  annotations:
    policies.kyverno.io/title: Unique Ingress Host
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/minversion: 1.3.2
    policies.kyverno.io/description: >-
      An Ingress host is a URL at which services may be made available externally. In most cases,
      these hosts should be unique across the cluster to ensure no routing conflicts occur.
      This policy checks an incoming Ingress resource to ensure its hosts are unique to the cluster.
      It also ensures that only a single host may be specified in a given manifest.      
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: check-single-host
      match:
        any:
        - resources:
            kinds:
              - Ingress
      context:
        - name: hosts
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[].spec.rules[].host"
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host }}"
          operator: AnyIn
          value: "{{ hosts }}"
      validate:
        message: "The Ingress host name must be unique."
        deny: {}
    - name: deny-multiple-hosts
      match:
        any:
        - resources:
            kinds:
              - Ingress
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host | length(@)}}"
          operator: GreaterThan
          value: 1
      validate:
        message: "An Ingress resource may only contain a single host entry."
        deny: {}
```

Please confirm it works for you.

**Comment by cuishuyuanCode** [comment]
hello @chipzoller ,I tried to use the policy you provided. it's also has the problem，


**Steps to reproduce**

kyverno version:  latest
```
kubectl create -f https://raw.githubusercontent.com/kyverno/kyverno/main/config/install.yaml
```

1.confirm my ingress is empty
```
kubectl get ingress -A
```
![image](https://user-images.githubusercontent.com/101328588/197686601-c3cdeaa4-cf19-4788-84e5-4a20d0f69a57.png)

2.create and apply policy
```
kubectl apply -f unique-ingress-host.yaml
```
unique-ingress-host.yaml
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
  annotations:
    policies.kyverno.io/title: Unique Ingress Host
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/minversion: 1.3.2
    policies.kyverno.io/description: >-
      An Ingress host is a URL at which services may be made available externally. In most cases,
      these hosts should be unique across the cluster to ensure no routing conflicts occur.
      This policy checks an incoming Ingress resource to ensure its hosts are unique to the cluster.
      It also ensures that only a single host may be specified in a given manifest.      
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: check-single-host
      match:
        any:
        - resources:
            kinds:
              - Ingress
      context:
        - name: hosts
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[].spec.rules[].host"
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host }}"
          operator: AnyIn
          value: "{{ hosts }}"
      validate:
        message: "The Ingress host name must be unique."
        deny: {}
    - name: deny-multiple-hosts
      match:
        any:
        - resources:
            kinds:
              - Ingress
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: Equals
          value: CREATE
        - key: "{{ request.object.spec.rules[].host | length(@)}}"
          operator: GreaterThan
          value: 1
      validate:
        message: "An Ingress resource may only contain a single host entry."
        deny: {}
```
3.create and apply the ingress
```
kubectl apply -f ingress-host.yaml
```
ingress-host.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: www.test.com
    http:
      paths:
      - pathType: Prefix
        path: "/kyverno"
        backend:
          service:
            name: service1
            port:
              number: 80
```
4.get policy report
```
kubectl get polr -A
```
![image](https://user-images.githubusercontent.com/101328588/197687026-79267886-c22e-4ad2-8f8e-3c97661a4a9f.png)

5.delete ingress
```
kubectl delete --all ingress
```
6.Make sure my ingress is deleted
```
kubectl get ingress -A
```
![image](https://user-images.githubusercontent.com/101328588/197687391-3f93a663-6201-49cf-8a25-e817cbc2ed3e.png)

7.reapply ingress 
```
kubectl apply -f ingress-host.yaml
```
8.get policy report
```
kubectl get polr -A
```
![image](https://user-images.githubusercontent.com/101328588/197687564-31925d5c-c548-4f91-b898-b1bf49c935d6.png)

**I think the policy report result should be passed or skip, but now the result has a fail**

if you policy report is skip or pass, you can repeat operations step 5~8，you will see the policy report has a fail.

I also used version 1.7.4 for testing. I find this problem occurs if I delete ingress multiple times and reapply it.

 Under the same conditions，sometimes the policy report was normal，and sometimes the policy report has a fail.
