### ISSUE TITLE
[Bug] Collision between policies

### ISSUE THREAD

**Issue by franroa** [kyverno/policies#430]
### Kyverno Version

1.7.x

### Kubernetes Version

1.22.x

### Kubernetes Platform

EKS

### Description

Hi, I have created two policies that are tightly related and collide.
The Idea is that I want to:
Set my pods nodeSelector with a label in the pod's namespace. This is working perfectly,
Set a namespace label by default in case that the namespace were not created with labels. This is working perfectly. 

The thing here is that when the first policy applies, it will immediately trigger the second, at least this is what I would expect.

Instead, kyverno seems to merge both policies somehow. The error it is throwing is:
**ValidationError(io.k8s.api.core.v1.Namespace.spec): unknown field "template" in io.k8s.api.core.v1.NamespaceSpec**
Which leads me to think that the patchStrategie from one policy (setting the nodeSelector with the label namespace) is applied for the resource selection of the other policy (getting the namespace without labels and setting a default label)

### Steps to reproduce
Just create a namespace with this policies
The first policy is setting the label in the namespace
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-default-namespace-label
  annotations:
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.8.0
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  rules:
    - name: check-namespace-to-shutdown-if-no-label-is-specified-and-set-it #@ TODO change the value to active after migration
      match:
        any:
        - resources:
            kinds:
            - Namespace
            selector:
              matchExpressions:
                - {key: shutdown, operator: DoesNotExist }
      exclude:
        any:
        - resources:
            namespaces:
            - kube-system
            - kyverno
            - common
            - flux
            - monitoring
            - default
            - kube-public
            - kube-node-lease
            - argocd
            - external-secrets
      mutate:
        patchStrategicMerge:
            metadata:
                labels:
                  shutdown: "inactive"
```

The second policy sets the nodeSelector by the namespace label:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-pod-template-node-selector-from-namespace-when-ns-changes
  annotations:
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.8.0
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  rules:
    - name: check-namespace-to-keep-running
      match:
        any:
        - resources:
            kinds:
            - Namespace
            selector:
              matchLabels:
                shutdown: "active"
      mutate:
        targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: "{{ request.object.metadata.name }}"
        patchStrategicMerge:
            spec:
              template:
                spec:
                  nodeSelector:
                    shutdown: "active"
    - name: check-namespace-to-shutdown
      match:
        any:
        - resources:
            kinds:
            - Namespace
            selector:
              matchLabels:
                shutdown: "inactive"
      mutate:
        targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: "{{ request.object.metadata.name }}"
        patchStrategicMerge:
            spec:
              template:
                spec:
                  nodeSelector:
                    shutdown: "inactive"

```

### Expected behavior

I would expect that the first policy will only get triggers once, when I create the namespace without labels. The patchStrategy would set a default value, which in turn it triggers a second policy with the selector given by the first one and the the patchStrategy would set the nodeSelector. 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
In your first rule, you probably should use a precondition which restricts the matching of Namespaces to a `CREATE` operation so that subsequent labeling (which triggers an `UPDATE`) is excluded.

**Comment by franroa** [comment]
Hi, thank you for the answer. I also tried it.
So this was my last try:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cluster-spec
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/synaos/pi/specs/cluster-specs.git
    targetRevision: poc/tenants-shutdownK
    path: "development/resources"
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
```
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-pod-template-node-selector-from-namespace-when-ns-changes
  annotations:
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.8.0
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  failurePolicy: Ignore
  validationFailureAction: audit
  rules:
    - name: check-namespace-to-keep-running
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: Equals
            value: UPDATE
      match:
        all:
        - resources:
            kinds:
            - Namespace
            selector:
              matchLabels:
                shutdown: "active"
      mutate:
        targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: "{{ request.object.metadata.name }}"
        patchStrategicMerge:
            spec:
              template:
                spec:
                  nodeSelector:
                    shutdown: "active"
    - name: check-namespace-to-shutdown
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: Equals
            value: UPDATE
      match:
        all:
        - resources:
            kinds:
            - Namespace
            selector:
              matchExpressions:
              - {key: shutdown, operator: NotIn, values: [active] }
      mutate:
        targets:
        - apiVersion: apps/v1
          kind: Deployment
          namespace: "{{ request.object.metadata.name }}"
        patchStrategicMerge:
            spec:
              template:
                spec:
                  nodeSelector:
                    shutdown: "inactive"

```

I ended up ignoring the failure.
