### ISSUE TITLE
[Bug] Only last rule applied with multiple mutating rules 

### ISSUE THREAD

**Issue by passie** [kyverno/policies#451]
### Kyverno Version

1.7.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

K3d

### Description

We are using the proxy cache functionality with in Harbor and need to change the registries to our internal registry server.
When applying one single rule this work fine, though when applying multiple rules for different registries, only applies the last rule.

Even splitting the rules in 2 different clusterpolicies gives the same output.

### Steps to reproduce
```
rules:
    - name: replaceRegistry
      match:
        any:
        - resources:
            kinds:
            - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('(hub.docker.com)', '{{element.image}}', 'harbor.internal.com' )}}"
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('(registry.io)', '{{element.image}}', 'harbor.internal.com' )}}"`
```
Applied registry.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: hub.docker.com/test/image:v3
        name: test3
      - image: registry.io/test/image:v4
        name: test4
```
### Expected behavior

All rules should be applied, not the last rule in the clusterpolicy. 
```
harbor.internal.com/test/image:v3
harbor.internal.com/test/image:v4
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
You'll need to use preconditions inside those `foreach` loops. Here's a snippet from the community which will do exactly this:

```yaml
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "quay.io/*"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', 'harbor.company.com/quay' )}}"
```
