### ISSUE TITLE
[Bug] drop 'ALL' is not covering the 'CAP_NET_RAW' inside capabilities for securityContext, throws warnings

### ISSUE THREAD

**Issue by sankalp28** [kyverno/policies#455]
### Kyverno Version

1.8.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

Other (specify in description)

### Description

Despite using drop 'ALL' , in capabilities inside securityContext, get events throws warnings asking for to drop 'CAP_NET_RAW' , as seen in code snippet below:
```
securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault 

```

**warnings seen for these values as below:**

`**Warning   PolicyViolation     deployment/yard-umbrella-proxy              policy drop-cap-net-raw/autogen-require-drop-cap-net-raw fail: validation failure: Containers must drop the `CAP_NET_RAW` capability.** 
`

### Steps to reproduce

1. securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault 

kubectl get events -n <namespace>

### Expected behavior

No warnings 
CAP_NET_RAW is covered by 'ALL' 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
