### ISSUE TITLE
Kyverno Mutate Policy to replace the metada "annotation" key with some other key name

### ISSUE THREAD

**Issue by gbhi** [kyverno/policies#460]
### Kyverno Version

1.7.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

Bare metal

### Description

Is there a Kyverno Mutate Policy to replace the metadata "annotation" key with some other key name ?

Example : Below is the Ingress Object where we have a Kong annotation key as "plugins.konghq.com", now in latest version of Kong new annotation key is "konghq.com/plugins" . Our requirement is to write a Kyverno Policy to replace the annotation key in all the existing Ingress Object with the new key. 

Existing Ingress Object ->

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    **plugins.konghq.com**: jwt,authz

After Mutate expectation is below New Ingress Object:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    **konghq.com/plugins**: jwt,authz

### Steps to reproduce

NA

### Expected behavior

NA

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Hi, this is interesting. This is required for a Kong upgrade? Can you point us to some documentation on this, please?

**Comment by chipzoller** [comment]
Try this out:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kong
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: replace-annotation
    match:
      any:
      - resources:
          kinds:
          - Ingress
          annotations:
            plugins.konghq.com: "?*"
    mutate:
      targets:
        - apiVersion: networking.k8s.io/v1
          kind: Ingress
      patchesJson6902: |-
        - op: add
          path: /metadata/annotations/konghq.com~1plugins
          value: '{{target.metadata.annotations."plugins.konghq.com"}}'
        - op: remove
          path: /metadata/annotations/plugins.konghq.com
```
