### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by haarchri** [kyverno/policies#461]
### Kyverno Version

1.7.x

### Kubernetes Version

1.22.x

### Kubernetes Platform

EKS

### Description

we created the following policy:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Tenant
    policies.kyverno.io/description: Sync docker.io pull-secret to tenant-namespaces
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/title: Sync Image Pull Secret docker.io
  name: sync-docker-io-secret
spec:
  background: true
  failurePolicy: Fail
  generateExistingOnPolicyUpdate: true
  rules:
  - generate:
      apiVersion: v1
      clone:
        name: docker.io
        namespace: flux-system
      kind: Secret
      name: docker-io-image-pull-secret
      namespace: '{{request.object.metadata.name}}'
      synchronize: true
    match:
      resources:
        kinds:
        - Namespace
    name: sync-docker-io-secret
  validationFailureAction: audit
```

any reason why the secrets not synced to kube-system namespace? in all other namespaces the sync is working

### Steps to reproduce

create the policy
no secret in kube-system namespace

### Expected behavior

secret also created in kube-system namespace

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
