### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ep4sh** [kyverno/policies#465]
### Kyverno Version

1.7.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

GKE

### Description

verify image doesn't work with images from private registry 
my kyverno version is 1.8.2 **but I can't select it from the list.**
k8s is v1.24.7-gke.900

### Steps to reproduce

0. We must have an image with available signature with cosign.
Validation of the image must pass:
```
$ cosign verify --key cosign.pub my-internal-registry.com/images/ingress:1.4.0

Verification for my-internal-registry.com/images/ingress:1.4.0--
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key

[{"critical":{"identity":{"docker-reference":"my-internal-registry.com/images/ingress"},"image":{"docker-manifest-digest":"sha256:d7012e4ff51cac4914eb37bbe507b5ee9750586d1760e398e5d34794c8ff9514"},"type":"cosign container image signature"},"optional":null}]
```

1. Create a `kyverno` cluster policy. The public key should be invalid (different from cosign.pub) - we must fail any given image to prove that policy works.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image
  annotations:
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.7.0
    policies.kyverno.io/description: >-
      Using the Cosign project, OCI images may be signed to ensure supply chain
      security is maintained. Those signatures can be verified before pulling into
      a cluster. This policy checks the signature of an image repo called
      ghcr.io/kyverno/test-verify-image to ensure it has been signed by verifying
      its signature against the provided public key. This policy serves as an illustration for
      how to configure a similar rule and will require replacing with your image(s) and keys.
spec:
  validationFailureAction: enforce
  background: false
  failurePolicy: Fail
  rules:
    - name: verify-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "my-internal-registry.com/images/*:*"
        mutateDigest: true
        attestors:
        - entries:
          - keys:
              publicKeys: |
                -----BEGIN PUBLIC KEY-----
              <ANY INVALID PUBLIC KEY TO FAIL DEPLOYMENT
                -----END PUBLIC KEY-----

```

2. Create a deployment for which uses an image from private registry
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kyverno-my
  labels:
    app: test-kyverno-my
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kyverno-my
  template:
    metadata:
      labels:
        app: test-kyverno-my
    spec:
      imagePullSecrets:
        - name: my-dockery-key
      containers:
      - name: test-kyverno-my
        image: my-internal-registry.com/images/ingress:1.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

```

3. Check that `kyverno` has access to the internal container registry (`imagePullSecrets` has been specified during `kyverno` installation)

### Expected behavior

Deployment has a broken pod (with Crashloopback error or something), not a running one.

### Screenshots

<img width="1761" alt="Screenshot 2022-12-06 at 13 53 49" src="https://user-images.githubusercontent.com/19505042/205892719-2acba4db-f1f7-42f5-8be2-f9bd6a6e5f2f.png">

### Kyverno logs

```shell
there are no logs for any action, why?
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
