### ISSUE TITLE
[Bug] Upgrading from 1.8.2 to 1.8.3 breaks the cluster mutating policy

### ISSUE THREAD

**Issue by passie** [kyverno/policies#471]
### Kyverno Version

1.7.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

Other (specify in description)

### Description

When applying a deployment while running a cluster policy with  version 1.8.1 the cluster policy is activated I'm receiving the following warning message: 

> Warning: policy replaceregistryaquasec.replaceregistryaquasec: failed to evaluate list request.object.spec.containers: JMESPath query failed: Unknown key "containers" in path
Though the rules get applied successfully 

When applying the same deployment with version 1.8.3 I'm receiving the following 

> Error from server: error when creating "e2etest.yaml": admission webhook "mutate.kyverno.svc-fail" denied the request: mutation policy replaceregistryaquasecerror: failed to apply policy replaceregistryaquasec rules [replaceregistryaquasec]

The mutation of the registry url's isn't applied. 
Below is the clusterpolicy. Don't mind the extra `{{`they are needed for ArgoCD. 

### Steps to reproduce

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replaceregistryaquasec
  annotations:
    policies.kyverno.io/title: Replace aquasec Registry
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pods
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Replace aquasec Registry
spec:
  background: false
  rules:
    - name: replaceregistryaquasec
      match:
        any:
        - resources:
            kinds:
              - Pod
              - Deployment
              - StatefulSet
              - DaemonSet
              - ReplicaSet
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          preconditions:
              all:
                - key: "{{ `{{` }} element.image {{ `}}` }}"
                  operator: Equals
                  value: "registry.aquasec.com/*"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ `{{` }}  element.name {{ `}}` }}"
                image: "{{ `{{` }}  regex_replace_all_literal('^[^/]+', '{{ `{{` }} element.image {{ `}}` }}', 'example.com/aquasec' ){{ `}}` }}"
```

### Expected behavior

The registry should be mutated with the correct internal registry.

### Kyverno logs

```shell
E1213 08:55:21.139374       1 handlers.go:175] webhooks/resource/mutate "msg"="mutation failed" "error"="mutation policy replaceregistryaquasec error: failed to apply policy replaceregistryaquasec ru                        les [replaceregistryaquasec]" "kind"="Deployment" "name"="trident-csi" "namespace"="trident" "operation"="UPDATE" "uid"="190af8b0-a762-4dc3-92fc-12e344d8f13e" "user"={"username":"system:serviceaccoun                        t:trident:trident-operator","uid":"59c3f337-b543-475d-b5af-6a924e52d572","groups":["system:serviceaccounts","system:serviceaccounts:trident","system:authenticated"],"extra":{"authentication.kubernete                        s.io/pod-name":["trident-operator-657c48b9c6-rb4v8"],"authentication.kubernetes.io/pod-uid":["d40c7261-f1ee-4ac0-82e3-62ebdfdc68ec"]}}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
