### ISSUE TITLE
[Sample] Policy Exception

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#478]
### Problem Statement

Add a sample policy which protects against PolicyException resources introduced in 1.9 with some common, helpful rules included.

### Solution Description

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: policy-for-exceptions
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: single-policy
    match:
      any:
      - resources:
          kinds:
          - PolicyException
    validate:
      message: >-
        An exception is only allowed for a single policy.
        Please create a separate exception per policy.
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.exceptions[] | length(@)}}"
            operator: GreaterThan
            value: 1
  - name: require-match-name
    match:
      any:
      - resources:
          kinds:
          - PolicyException
    validate:
      message: >-
        An exception must explicitly specify a name for a resource match.
      pattern:
        spec:
          match:
            =(any):
            - resources:
                names: "?*"
            =(all):
            - resources:
                names: "?*"
  - name: require-subject
    match:
      any:
      - resources:
          kinds:
          - PolicyException
    validate:
      message: >-
        An exception must explicitly specify a subject which is expected to create the resource.
      pattern:
        spec:
          match:
            =(any):
            - subjects: 
              - name: "?*"
            =(all):
            - subjects: 
              - name: "?*"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
