### ISSUE TITLE
[Sample] Subresource support in 1.9

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#479]
### Problem Statement

Need policies illustrating extended subresource support in Kyverno 1.9.

### Solution Description

Add samples which cover the extended subresource support introduced in 1.9. Cover mutating for Node/status and validating for /scale.

https://github.com/kyverno/kyverno/pull/4916

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: advertise-resource
spec:
  background: false
  rules:
    - name: advertise-dongle
      match:
        any:
        - resources:
            kinds:
            - Node/status
      mutate:
        patchStrategicMerge:
          status:
            capacity:
              example.com/dongle: 2
```

**Comment by chipzoller** [comment]
```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: restrict-replicas
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  # This rule can be used to limit scale operations based upon Deployment labels assuming the given label
  # is also used as a selector.
  - name: scale-max-eight
    match:
      any:
      - resources:
          kinds:
          - Deployment/scale
    validate:
      message: The replica count for this Deployment may not exceed 8.
      pattern:
        =(status):
          =(selector): "*type=monitoring*"
        spec:
          replicas: <9
  # This rule can be used for more advanced decision making, for example limiting scale based
  # upon Deployment annotations which are not sent by the API server to admission controllers
  # when a scale is performed.
  - name: scale-max-eight-annotations
    match:
      any:
      - resources:
          kinds:
          - Deployment/scale
    context:
      - name: parentdeploy
        apiCall:
          urlPath: "/apis/apps/v1/namespaces/{{request.namespace}}/deployments?fieldSelector=metadata.name={{request.name}}"
          jmesPath: "items[0]"
      - name: dept
        variable:
          jmesPath: parentdeploy.metadata.annotations."corp.org/dept"
          default: empty
    validate:
      message: The replica count for this Deployment may not exceed 8.
      deny:
        conditions:
          all:
          - key: "{{dept}}"
            operator: Equals
            value: engineering
          - key: "{{request.object.spec.replicas}}"
            operator: GreaterThan
            value: 8
  # This rule, which is a simple check on Deployments for replicas (not scaling them) can be used
  # to complement scale operations. This may be needed along with at least one of the prior two rules
  # to fully limit the number of total replicas allowed. For example, this rule would limit creation of
  # Deployments to no more than 4 replicas, without an additional rule for scaling it would not prevent
  # scaling over 4. By combining this CREATE rule with one of the scale rules above, a cluster admin
  # may effectively provide an allowed range of replicas good for both day1 and day2 operations.
  - name: create-max-four
    match:
      any:
      - resources:
          kinds:
          - Deployment
          selector:
            matchLabels:
              type: monitoring
    validate:
      message: The replica count for this Deployment may not exceed 4.
      pattern:
        spec:
          replicas: <5
```
