### ISSUE TITLE
[Sample] Nested `foreach` sample

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#480]
### Problem Statement

Add a policy sample covering nested `foreach` in Kyverno 1.9.

### Solution Description

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
spec:
  background: false
  rules:
    - name: replace-dns-suffix
      match:
        any:
          - resources:
              kinds:
                - Ingress
      mutate:
        foreach:
          - list: request.object.spec.tls[]
            foreach:
              - list: "element.hosts"
                patchesJson6902: |-
                  - path: /spec/tls/{{elementIndex0}}/hosts/{{elementIndex1}}
                    op: replace
                    value: "{{ replace_all('{{element}}', '.old.com', '.new.com') }}"
          - list: request.object.spec.tls[]
            patchesJson6902: |-
              - path: /spec/tls/{{elementIndex}}/secretName
                op: replace
                value: "{{ replace_all('{{element.secretName}}', '.old.com', '.new.com') }}"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
