### ISSUE TITLE
Random rewrites initcontainers 

### ISSUE THREAD

**Issue by passie** [kyverno/policies#493]
### Kyverno Version

1.8.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

Other (specify in description)

### Description

it's probably not a bug though i can't seem to find out how to fix it. 

I have created a clusterpolicy to rewrite the internet registries to our internal proxy cache registry.
For "normal" containers this is working as expected, though for initContainers it doesn't.
All our code is applied via ArgoCD. 
On the first run the registries are rewritten. but on the second etc... runs, sometimes they are not rewritten to the correct registry and the original registry remains. currently is looks like random rewrites.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replaceregistryquayio
  annotations:
    policies.kyverno.io/title: Replace quayio Registry
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pods
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Replace quayio Registry
spec:
  background: false
  rules:
    - name: replaceregistryquayio
      match:
        any:
        - resources:
            kinds:
              - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "quay.io/*"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('^[^/]+', '{{ element.image }}', 'harbor-internal.example.com/quayio' )}}"
    - name: replaceregistryquayinitcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "quay.io/*"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('quay.io/', '{{ element.image }}', 'harbor-internal.example.com/quayio/' )}}"
```

### Steps to reproduce

1.  Create a cluster policy which both replaces containers and initcontainers. 
On the first run all registries are rewritten on the second run the original registry is placed back. 
This looks random since it doesn't do this all the time.

### Expected behavior

I would expect the same behavior with every run.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
The reproduction steps here are a bit confusing. Explain "run" and how you're testing this to see the inconsistencies.

**Comment by passie** [comment]
> The reproduction steps here are a bit confusing. Explain "run" and how you're testing this to see the inconsistencies.

I should have be more clear on the  issue. 
When I first apply the yaml the registries are rewritten to the correct internal registry.  But when I apply the same file again randomly the registries are not rewritten. 
Then when I delete the resource and re-apply the same file again the registries are rewritten or not. 

please note that the yaml files are applied with ArgoCD.
I hope it's a bit clearer now.

**Comment by chipzoller** [comment]
This might somehow be related to some earlier bugs in 1.8 or maybe the filter. In any case, I've tested a variant of this with the `regex_replace_all` filter on 1.10.0-alpha.2 and can repeatedly apply a Pod to this policy and in every case it's getting replaced properly.

Try this out and see if it's any better:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replaceregistryquayio
spec:
  rules:
    - name: replaceregistryquayio
      match:
        any:
        - resources:
            kinds:
              - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "quay.io/*"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^([^/]+\\.[^/]+/)?(.*)$', '{{ element.image }}', 'harbor-internal.example.com/quayio/$2' )}}"
    - name: replaceregistryquayinitcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          preconditions:
              all:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "quay.io/*"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^([^/]+\\.[^/]+/)?(.*)$', '{{ element.image }}', 'harbor-internal.example.com/quayio/$2' )}}"
```

Going to close this for now but re-open in kyverno/kyverno if it persists. Also feel free to respond.
