### ISSUE TITLE
[Sample] Limit hosts usage per projectID in Rancher

### ISSUE THREAD

**Issue by ikarlashov** [kyverno/policies#495]
### Problem Statement

We have a cluster managed by Rancher. In rancher we have projects, where each project can have multiple namespaces. 
It's allowed to use same **host** in **Ingress** within a project(multiple namespaces). Hence, forbidden to use same host in different projects.

### Solution Description

When user creates an ingress with the host(s) that is(are) already used by other project - validation of request should fail.

### Other Comments

I've made the example policy. The problem is: it can be applicable only if the only one host is set in a reviewed object. And we're not blocking users from creation of more than 1 host per Ingress object. I need to iterate through arrays very badly and AFAIK it's only possible with **request.object** and not with variables in context.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-ingress-hostname-in-use
spec:
  background: false
  validationFailureAction: enforce
  rules:
    - name: deny-ingress-hostname-in-use
      match:
        resources:
          kinds:
            - Ingress
      preconditions:
        - key: "{{ request.operation }}"
          operator: AnyIn
          value: ["CREATE", "UPDATE"]
      context:
        - name: project_id
          apiCall:
            urlPath: "/api/v1/namespaces/{{ request.namespace }}"
            jmesPath: "metadata.labels.\"field.cattle.io/projectId\" || ''"
        ## for_each?
        - name: namespace_with_host
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[?spec.rules[].host | contains(@, '{{ request.object.spec.rules[0].host || ''}}')].metadata.namespace | [0]"
        - name: namespaces_from_project_id
          apiCall:
            urlPath: "/api/v1/namespaces"
            jmesPath: "items[?metadata.labels.\"field.cattle.io/projectId\" == '{{ project_id }}' ].metadata.name || ''"            
      validate:
        message: "Ingress host {{ request.object.spec.rules[0].host }} can not be used because it is in use in a namespace that belongs to a different project"
        deny:
          conditions:
            any:
            - key: "{{ namespace_with_host }}"
              operator: AnyNotIn
              value: "{{ namespaces_from_project_id }}"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
