### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by khalid-lemghari** [kyverno/policies#497]
### Kyverno Version

1.9.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

Other (specify in description)

### Description

Hello,

I report that I just used the policy  "Require Limits and Requests" shared in link below : 

- https://kyverno.io/policies/best-practices/require_pod_requests_limits/require_pod_requests_limits/

But it doesn't checks the resources requests. My policy is as below : 

```yaml
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: 1.24
    kyverno.io/kyverno-version: 2.7.0
    meta.helm.sh/release-name: kyverno-policies
    meta.helm.sh/release-namespace: kyverno
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Omnia Compliance Framework
    policies.kyverno.io/description: Disallow besteffort pod
    policies.kyverno.io/minversion: 2.7.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/title: Disallow besteffort pod
  name: o2-cpol-disallow-besteffort-pod-v0
spec:
  background: true
  rules:
  - name: o2-check-resources
    match:
      resources:
        kinds:
        - Pod
        namespaces:
          - o2-limits-workshop
    validate:
      message: "The cpu/memory limits and requests are required."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                cpu: "?*"
                memory: "?*"
              requests:
                cpu: "?*"
                memory: "?*"
  validationFailureAction: Enforce
```

**Note** :  I'm using an RKE2 as Kubernetes Platform : 

```bash
Client Version: v1.24.3+rke2r1
Kustomize Version: v4.5.4
Server Version: v1.24.3+rke2r1
```

### Steps to reproduce

1. Install kyverno : 
 
      ```
      helm install kyverno kyverno/kyverno \
          --create-namespace \
          --namespace kyverno \
          --values helm-values.yml
      ```
  
      ```yaml
      ---
      replicaCount: 3
      resources:
        limits:
          memory: 384Mi
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      cleanupController:
        replicas: 3
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      ```

3. Install kyverno-policies :

      ```bash
      helm install kyverno-policies kyverno/kyverno-policies \
          --create-namespace \
          --namespace kyverno
      ```

4. Installation policy-reporter : 

      ```
      helm install policy-reporter policy-reporter/policy-reporter \
          --create-namespace \
          --namespace policy-reporter \
          --set kyvernoPlugin.enabled=true \
          --set ui.enabled=true \
          --set ui.plugins.kyverno=true
      ```

5. Apply  the cpol :
      ```bash
      kubectl apply -f - <<EOF 
      apiVersion : kyverno.io/v1
      kind: ClusterPolicy
      metadata:
        annotations:
          kyverno.io/kubernetes-version: 1.24
          kyverno.io/kyverno-version: 2.7.0
          meta.helm.sh/release-name: kyverno-policies
          meta.helm.sh/release-namespace: kyverno
          pod-policies.kyverno.io/autogen-controllers: none
          policies.kyverno.io/category: Omnia Compliance Framework
          policies.kyverno.io/description: Disallow besteffort pod
          policies.kyverno.io/minversion: 2.7.0
          policies.kyverno.io/severity: medium
          policies.kyverno.io/subject: Pod
          policies.kyverno.io/title: Disallow besteffort pod
        name: o2-cpol-disallow-besteffort-pod-v0
      spec:
        background: true
        rules:
        - name: o2-check-resources
          match:
            resources:
              kinds:
              - Pod
              namespaces:
                - o2-limits-workshop
          validate:
            message: "The cpu/memory limits and requests are required."
            pattern:
              spec:
                containers:
                - resources:
                    limits:
                      cpu: "?*"
                      memory: "?*"
                    requests:
                      cpu: "?*"
                      memory: "?*"
        validationFailureAction: Enforce
      EOF
      ```

7. Deploy somes pods as poc :

    ```bash
    kubectl apply -f https://github.com/khalid-lemghari/poc/tree/main/kyverno/pod -n ocf-limits-workshop
    ```

### Expected behavior
pod/ocf-pod-1111-burstable.yml created
pod/ocf-pod-1111-guaranteed.yml created

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

My regards,

**Comment by chipzoller** [comment]
Please provide complete reproduction steps.

**Comment by khalid-lemghari** [comment]
Hi @chipzoller, 

Foremost, thank you for your reply. 

I updated my message and you can download the pods' manifests from : 

- https://github.com/khalid-lemghari/poc/tree/main/kyverno/pod

My regards,

**Comment by chipzoller** [comment]
Please add the Pod manifest which can be reproduced into this issue.

**Comment by khalid-lemghari** [comment]
The pod manifest as example are : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-0000-besteffort
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1100-guaranteed
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1101-burstable
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
      requests:
        memory: 128M
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1110-burstable
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
      requests:
        cpu: 18m
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1111-burstable
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
      requests:
        cpu: 18m
        memory: 128M
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1111-guaranteed
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
      requests:
        cpu: 72m
        memory: 256M
```

**Comment by chipzoller** [comment]
Your policy states:

```yaml
    match:
      resources:
        kinds:
        - Pod
        namespaces:
          - o2-limits-workshop
```

All your Pods state:

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: ocf-limits-workshop
```

You have told Kyverno to only match on Pods in the `o2-limits-workshop` Namespace yet that isn't where your Pods are going. You change either your policy to match the Pods' Namespace or change the Pods' Namespace to match the policy and it works as intended. Not a bug. Closing.

**Comment by khalid-lemghari** [comment]
Hello @chipzoller, The namespace was correct and I changed it for a privacy purpose... I ask you again to to test from your side and analyze the behavior that I'm reporting...

**Comment by chipzoller** [comment]
All Pods are successfully created except for the first Pod which has neither requests nor limits. The reason why the second through fourth Pods are created despite not defining all the fields the policy does is because how Kubernetes treats resources. If you check the created Pods, these missing fields are now present. This is documented [here](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/):

>Note: If a Container specifies its own memory limit, but does not specify a memory request, Kubernetes automatically assigns a memory request that matches the limit. Similarly, if a Container specifies its own CPU limit, but does not specify a CPU request, Kubernetes automatically assigns a CPU request that matches the limit.

**Comment by khalid-lemghari** [comment]
Absolutely right! This is what I suspected from the begining.

If you allow, I have another question: When I also apply the "Enforce resources ratio to 1" policy, this deny the deployment of the two pods with QoS : Guaranteed !

```yaml
---
# Enforce resources ratio to 1
apiVersion : kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.24"
    kyverno.io/kyverno-version: "2.7.0"
    meta.helm.sh/release-name: kyverno-policies
    meta.helm.sh/release-namespace: kyverno
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Omnia Compliance Framework
    policies.kyverno.io/description: Disallow burstable pod
    policies.kyverno.io/minversion: "2.7.0"
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/title: Disallow burstable pod
  name: ocf-cpol-disallow-burstable-pod
spec:
  background: true
  rules:
  - name: ocf-check-resources
    match:
      resources:
        kinds:
        - Pod
        namespaces:
          - ocf-limits-workshop
    validate:
      message: "The cpu/memory limits are required."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                cpu: "?*"
                memory: "?*"
  - name: ocf-check-cpu-ratio
    match:
      resources:
        kinds:
        - Pod
        namespaces:
          - ocf-limits-workshop
    validate:
      message: "The resources cpu requests and limits must be equal."
      foreach:
      - list: "request.object.spec.containers"
        deny:
          conditions:
            any:
            - key: "{{ divide('{{ element.resources.limits.cpu || '0' }}', '{{ element.resources.requests.cpu || '1' }}') }}"
              operator: NotEquals
              value: 1
  - name: ocf-check-memory-ratio
    match:
      resources:
        kinds:
        - Pod
        namespaces:
          - ocf-limits-workshop
    validate:
      message: "The resources memory requests and limits must be equal."
      foreach:
      - list: "request.object.spec.containers"
        deny:
          conditions:
            any:
            - key: "{{ divide('{{ element.resources.limits.memory || '0' }}', '{{ element.resources.requests.memory || '1m' }}') }}"
              operator: NotEquals
              value: 1
  validationFailureAction: Enforce
```

And thank you a lot.

**Comment by chipzoller** [comment]
Which specific rule and which specific Pod(s) are you pointing out here?

**Comment by khalid-lemghari** [comment]
I tested the spec below :  

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1100-guaranteed
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1111-guaranteed
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
      requests:
        cpu: 72m
        memory: 256M
```

And this is the output : 

```bash
Error from server: error when creating "kyverno/pod/ocf-pod-1100-guaranteed.yml": admission webhook "validate.kyverno.svc-fail" denied the request: 

policy Pod/ocf-limits-workshop/ocf-pod-1100-guaranteed for resource violation: 

ocf-cpol-disallow-burstable-pod:
  ocf-check-memory-ratio: 'validation failure: The resources memory requests and limits
    must be equal.'

Error from server: error when creating "kyverno/pod/ocf-pod-1111-guaranteed.yml": admission webhook "validate.kyverno.svc-fail" denied the request: 

policy Pod/ocf-limits-workshop/ocf-pod-1111-guaranteed for resource violation: 

ocf-cpol-disallow-burstable-pod:
  ocf-check-memory-ratio: 'validation failure: The resources memory requests and limits
    must be equal.'
```
