### ISSUE TITLE
Policy to disallow x-y range ports for service binding

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#51]
See: https://www.reddit.com/r/kubernetes/comments/mtucy4/53_kyverno_policies_including_pod_security/

**Comment by chipzoller** [comment]
Probably going to need the `forEach` function (since `svc.spec.ports` is an array of objects) as well as a range function, right @JimBugwadia ?

**Comment by chipzoller** [comment]
Can you confirm my suspicion that such a policy isn't possible currently?

**Comment by JimBugwadia** [comment]
Hi @chipzoller - I was thinking that this request is for `networkpolicy.spec.ingress.ports`, but am not sure. 

For `networkpolicy.spec.ingress.ports` it should be possible to provide a validation pattern with a list of allowed values without requiring a `forEach`. 

We would need to test if the list options are flexible enough to do something like this:

```yaml
validate:
   pattern:
      spec:
        ingress:
        - ports:
          - port: "https | 443 | 32000-33000"
```

**Comment by chipzoller** [comment]
What I was specifically referring to was the range. For example, this doesn't seem to work:

```yaml
spec:
  validationFailureAction: enforce
  rules:
  - name: restrict-port-range
    match:
      resources:
        kinds:
        - Service
    validate:
      message: Ports must be between 32000-33000
      pattern:
        spec:
          ports:
          - port: 32000-33000
```

`svc.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  ports:
    - port: 32111
```
