### ISSUE TITLE
[Bug] Issue with add-default-resources policy

### ISSUE THREAD

**Issue by MoritzBinder** [kyverno/policies#511]
### Kyverno Version

1.9.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

Other (specify in description)

### Description

Kubernetes platform: RKE

We are using a Kyverno policy that should add default resources to all containers which do not specify resource limits explicitly. While the policy is working as expected for most deployments, we've observed an issue in a particular case. For a deployment with two containers, where one specifies resources explicitly, while the other one does not, the Kyverno policy overwrites the resources of the container that already contains explicit resource limits in the specs. Note that if both containers in the deployment specify resource limits explicitly, the policy does not overwrite them (as expected).

### Steps to reproduce

The Kyverno policy we are using is essentially the same as the add-default-resources policy on the Kyverno website: https://kyverno.io/policies/other/add_default_resources/add-default-resources/

```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-default-resources
  annotations:
    policies.kyverno.io/title: Add default resources
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Policy for testing
spec:
  background: false
  rules:
  - name: add-default-resources
    match:
      any:
      - resources:
          kinds:
            - Pod
    preconditions:
      any:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    mutate:
      patchStrategicMerge:
        spec:
          containers:
            - (name): "*"
              resources:
                requests:
                  +(memory): "100Mi"
                  +(cpu): "20m"
                  +(ephemeral-storage): 64Mi
                limits:
                  +(memory): "256Mi"
                  +(cpu): "1000m"
                  +(ephemeral-storage): 1Gi
```

The test deployment has two containers, of which one specifies resources explicitly, while the other one does not:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyverno-test-deployment
  template:
    metadata:
      labels:
        app: kyverno-test-deployment
    spec:
      containers:
        - name: container-with-resource-specs
          image: busybox:1.36.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsGroup: 1000
            runAsUser: 1000
          command: ["sh", "-c", "tail -f /dev/null"]
          resources:
            limits:
              cpu: 1
              ephemeral-storage: 2345Mi
              memory: 2345Mi
            requests:
              cpu: 789m
              ephemeral-storage: 1234Mi
              memory: 1234Mi
        - name: container-without-resource-specs
          image: busybox:1.36.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsGroup: 1000
            runAsUser: 1000
          command: ["sh", "-c", "tail -f /dev/null"]
```

In this case, Kyverno mutates the manifest such that the container `container-with-resource-specs` does not keep the resources from the manifest above, but instead gets the default resources from the Kyverno policy assigned. (As expected, the default resources are also added to the container `container-without-resource-specs`.)

### Expected behavior

As the description on the Kyverno website says (https://kyverno.io/policies/other/add_default_resources/add-default-resources/), we expected the policy to mutate any container in a Pod which doesn't specify resource requests and limits. Therefore, it should not change the resource requests and limits of containers that already contain explicit resource limits and requests in their specs.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
