### ISSUE TITLE
[Bug] Check-sa policy false positive on deployments with Service Account

### ISSUE THREAD

**Issue by gjkamstra** [kyverno/policies#514]
### Kyverno Version

1.9.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

EKS

### Description

I have [check-sa](https://raw.githubusercontent.com/kyverno/policies/main/other/check_serviceaccount/check_serviceaccount.yaml) applied on my cluster. When adding a deployment that uses a service account, there is a policy violation reported. (Visible in Policy Reporter UI).

### Steps to reproduce

1. Install [check-sa](https://raw.githubusercontent.com/kyverno/policies/main/other/check_serviceaccount/check_serviceaccount.yaml)
2. Apply a Deployment that uses a Service Account

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: dev
  name: dev-echo-server
  namespace: gjktest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
      env: dev
  template:
    metadata:
      labels:
        app: echo-server
        env: dev
    spec:
      containers:
        image: jmalloc/echo-server:0.3.3
        imagePullPolicy: Always
        …
        securityContext:
          capabilities:
            drop:
            - NET_RAW
            - ALL
          readOnlyRootFilesystem: true
      serviceAccountName: build-robot
  
```

Same happens when killing a previously installed pod (e.g. restart).

### Expected behavior

No violation of the policy. The deployment/pod is created by me, not by a service Account. If I understand the description correctly, it should only fail when pods are created by a SA.

### Kyverno logs

```shell
No relevant logs
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
