### ISSUE TITLE
[Sample] Backup persistent volumes with Velero

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#516]
### Problem Statement

Velero requires an annotation with a comma-separated value of the Pod's persistent volume names to be backed up.

### Solution Description

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: backup-velero-pv
spec:
  rules:
  - name: backup-velero-pv
    preconditions:
      all:
      - key: "{{ request.object.spec.volumes[?contains(keys(@), 'persistentVolumeClaim')] | length(@) }}"
        operator: GreaterThanOrEquals
        value: 1
      - key: "{{request.operation}}"
        operator: Equals
        value: CREATE
    context:
      - name: volumes
        variable:
          jmesPath: join(',',request.object.spec.volumes[?persistentVolumeClaim].name)
    match:
      any:
      - resources:
          kinds:
          - Pod
        namespaceSelector:
          matchLabels:
            velero-backup-pvc: 'true'
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            backup.velero.io/backup-volumes: '{{ volumes }}'
```

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1678217775979389

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
