### ISSUE TITLE
[Bug] patchStrategicMerge removes container content

### ISSUE THREAD

**Issue by acBartPeeters** [kyverno/policies#520]
### Kyverno Version

1.9.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

RKE

### Description

Kubernetes platform: RKE

We created a policy that adds resources to a container when they are not defined. Whilst this works, it also removes other information specified in the container (image/comand/args), which should not happen if I understand patchStrategicMerge correctly.

### Steps to reproduce

The Kyverno policy we are using is based on the add-default-resources policy on the Kyverno website: https://kyverno.io/policies/other/add_default_resources/add-default-resources/
```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: replace-workflow-resource
spec:
  background: false
  rules:
    - name: add-resources
      match:
        resources:
          kinds:
            - Workflow
      mutate:
        patchStrategicMerge:
          spec:
            templates:
              - (name): "*"
                container:
                  resources:
                    requests:
                      +(memory): "100Mi"
                      +(cpu): "20m"
                      +(ephemeral-storage): 64Mi
                    limits:
                      +(memory): "256Mi"
                      +(cpu): "1000m"
                      +(ephemeral-storage): 1Gi
```
And it was tested on this simple workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: test-bart-    # name of the workflow spec
  labels:
    delete: drtest
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
    - name: whalesay              # name of the template
      serviceAccountName: end-to-end-pipeline
      container:
        image: busybox:1.36.0
        command: [ cowsay ]
        args: [ "hello world" ]
```

### Expected behavior

I expected the resources would be added to the container without removing the rest of the content, so it should look like this:
```
container:
  image: busybox:1.36.0
  command: [ cowsay ]
  args: [ "hello world" ]
  resources:
    requests:
      memory: 100Mi
      cpu: 20m
      ephemeral-storage: 64Mi
    limits:
      memory: 256Mi
      cpu: 1000m
      ephemeral-storage: 1Gi
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Since this is a CRD, it's likely the way it was authored there is no merge key similar to how there is one for the Pod resource in Kubernetes. Since, for strategic merge patches, Kyverno uses Kustomize under the covers, if authors of CRDs don't use merge keys then these are some of the types of things that can result. You may need to convert this rule to use a JSON patch and probably a `foreach` statement.

**Comment by acBartPeeters** [comment]
Thank you, that makes sense. I made the following alternative solution:
```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-workflow-resources
spec:
  background: false
  rules:
    - name: add-request-memory
      match:
        resources:
          kinds:
            - Workflow
      preconditions:
        all:
        - key: "{{request.object.spec.templates[0].container.image }}"
          operator: notEquals
          value: ""
        - key: "{{request.object.spec.templates[0].container.resources.requests.memory || ''}}"
          operator: Equals
          value: ""
      mutate:
        patchesJson6902: |-
          - path: "/spec/templates/0/container/resources/requests/memory"
            op: add
            value: 100Mi
    - name: add-request-cpu
      match:
        resources:
          kinds:
            - Workflow
      preconditions:
        all:
        - key: "{{request.object.spec.templates[0].container.image }}"
          operator: notEquals
          value: ""
        - key: "{{request.object.spec.templates[0].container.resources.requests.cpu || ''}}"
          operator: Equals
          value: ""
      mutate:
        patchesJson6902: |-
          - path: "/spec/templates/0/container/resources/requests/cpu"
            op: add
            value: 20m
    - name: add-request-ephemeral-storage
      match:
        resources:
          kinds:
            - Workflow
      preconditions:
        all:
        - key: "{{request.object.spec.templates[0].container.image }}"
          operator: notEquals
          value: ""
        - key: "{{request.object.spec.templates[0].container.resources.requests.\"ephemeral-storage\" || ''}}"
          operator: Equals
          value: ""
      mutate:
        patchesJson6902: |-
          - path: "/spec/templates/0/container/resources/requests/ephemeral-storage"
            op: add
            value: 64Mi
    - name: add-limit-memory
      match:
        resources:
          kinds:
            - Workflow
      preconditions:
        all:
        - key: "{{request.object.spec.templates[0].container.image }}"
          operator: notEquals
          value: ""
        - key: "{{request.object.spec.templates[0].container.resources.limits.memory || ''}}"
          operator: Equals
          value: ""
      mutate:
        patchesJson6902: |-
          - path: "/spec/templates/0/container/resources/limits/memory"
            op: add
            value: 256Mi
    - name: add-limit-cpu
      match:
        resources:
          kinds:
            - Workflow
      preconditions:
        all:
        - key: "{{request.object.spec.templates[0].container.image }}"
          operator: notEquals
          value: ""
        - key: "{{request.object.spec.templates[0].container.resources.limits.cpu || ''}}"
          operator: Equals
          value: ""
      mutate:
        patchesJson6902: |-
          - path: "/spec/templates/0/container/resources/limits/cpu"
            op: add
            value: 1000m
    - name: add-limit-ephemeral-storage
      match:
        resources:
          kinds:
            - Workflow
      preconditions:
        all:
        - key: "{{request.object.spec.templates[0].container.image }}"
          operator: notEquals
          value: ""
        - key: "{{request.object.spec.templates[0].container.resources.limits.\"ephemeral-storage\" || ''}}"
          operator: Equals
          value: ""
      mutate:
        patchesJson6902: |-
          - path: "/spec/templates/0/container/resources/limits/ephemeral-storage"
            op: add
            value: 1Gi
```
The first precondition is to see whether a container exist (image defined). The second is to see whether the type of storage is already defined. If not it will be added (this is done 6 times). However, I would like to do this for all templates without copy pasting it a bunch of times. I tried a little bit with ```foreach``` but I don't know how to do it with preconditions. Would you know how to do this?

**Comment by chipzoller** [comment]
You can use preconditions inside (as well as outside) the `foreach` loop. If you do an `explain` on the schema you should see that as well as some examples in the docs. Have you given that a look?

**Comment by acBartPeeters** [comment]
Yes I looked at them and figured it out. The following works:
```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-workflow-resources
spec:
  background: false
  rules:
    - name: add-request-memory
      match:
        resources:
          kinds:
            - Workflow
      mutate:
        foreach:
          - list: request.object.spec.templates
            preconditions:
              all:
              - key: "{{ element.container.image }}"
                operator: NotEquals
                value: ""
              - key: "{{ element.container.resources.requests.memory || ''}}"
                operator: Equals
                value: ""
            patchesJson6902: |-
              - path: "/spec/templates/{{elementIndex}}/container/resources/requests/memory"
                op: add
                value: 100Mi
```
Thank you for your help!
