### ISSUE TITLE
Disallow Service Type LoadBalancer

### ISSUE THREAD

**Issue by PankajGrg** [kyverno/policies#527]
this is my clusterpolicy and i am unable to enfore it on my devcluster. the load balance svc still gets created.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: no-loadbalancer-service
  annotations:
    policies.kyverno.io/title: Disallow Service Type LoadBalancer
    policies.kyverno.io/category: Configuration Management
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: This policy restricts use of the Service type LoadBalancer.

spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: no-LoadBalancer
    match:
      any:
      - resources:
          kinds:
          - Service
          selector:
            matchLabels:
              app: no-loadbalancer
    validate:
      message: "Service of type LoadBalancer is not allowed."
      pattern:
        spec:
          type: "!LoadBalancer"

```
