### ISSUE TITLE
[Enhancement] Update policies with add anchor

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#540]
### Kyverno Version

1.9.x

### Kubernetes Version

1.25.x

### Kubernetes Platform

EKS

### Description

Update policies which use the add anchor based on https://github.com/kyverno/website/issues/800. Need to use `foreach` in combination with add anchor.

### Steps to reproduce

1. Try something like https://kyverno.io/policies/other/add_default_resources/add-default-resources/ with a Pod written like so
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: pod03 #### doesn't work
spec:
  automountServiceAccountToken: false
  containers:
  - name: busybox
    image: busybox:1.35
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
  - name: sidecar    #### doesn't add any fields here
    image: busybox:1.35
```
2. Notice for the second container it doesn't add any fields.

### Expected behavior

Policies which use add anchor with any containers modified to use foreach along with add anchor.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
