### ISSUE TITLE
[Sample] Mutate Pod binding

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#556]
### Problem Statement

Pod bindings can now be mutated in 1.10 which can be used to project the bound Node's label value(s) into its Pods.

### Solution Description

This requires removal of the Binding resourceFilter.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-name
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  background: false
  rules:
    - name: rule-name
      match:
        any:
        - resources:
            kinds:
            - Pod/binding
      context:
      - name: node
        variable:
          jmesPath: request.object.target.name
          default: ''
      - name: foolabel
        apiCall:
          urlPath: "/api/v1/nodes/{{node}}"
          jmesPath: metadata.labels.foo || 'empty'
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              foo: "{{ foolabel }}"
```

Test with this resource:

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: mypod
spec:
  automountServiceAccountToken: false
  containers:
  - name: busybox
    image: busybox:1.35
    args:
    - sleep
    - 1d
    env:
    - name: FOO_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['foo']
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
