### ISSUE TITLE
[Sample] Generate event

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#558]
### Problem Statement

Generate a custom Event when a user exec's into a Pod.

### Solution Description

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: audit-pods
spec:
  background: false
  rules:
  - name: generate-event-on-exec
    match:
      any:
      - resources:
          kinds:
          - Pod/exec
    context:
    - name: parentPodUID
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}/pods/{{request.name}}"
        jmesPath: "metadata.uid"
    generate:
      apiVersion: v1
      kind: Event
      name: "exec.{{ random('[a-z0-9]{6}') }}"
      namespace: "{{request.namespace}}"
      synchronize: false
      data:
        firstTimestamp: "{{ time_now_utc() }}"
        involvedObject:
          apiVersion: v1
          kind: Pod
          name: "{{ request.name }}"
          namespace: "{{ request.namespace }}"
          uid: "{{ parentPodUID }}"
        lastTimestamp: "{{ time_now_utc() }}"
        message: An exec was performed by {{ request.userInfo | to_string(@) }} running commands {{ request.object.command }}
        reason: Exec
        source:
          component: kyverno
        type: Warning
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Generate an Event upon editing of a ConfigMap named `foocm`:

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: audit-cm
spec:
  background: false
  rules:
  - name: generate-event-on-edit
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          names:
          - foocm
    preconditions:
      any:
      - key: "{{ request.operation }}"
        operator: Equals
        value: UPDATE
    generate:
      apiVersion: v1
      kind: Event
      name: "edit.{{ random('[a-z0-9]{12}') }}"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: false
      data:
        firstTimestamp: "{{ time_now_utc() }}"
        involvedObject:
          apiVersion: v1
          kind: ConfigMap
          name: "{{ request.name }}"
          namespace: "{{ request.namespace }}"
          uid: "{{request.object.metadata.uid}}"
        lastTimestamp: "{{ time_now_utc() }}"
        message: This resource was updated by {{ request.userInfo | to_string(@) }}. The previous contents were {{request.oldObject.data}}.
        reason: Edit
        source:
          component: kyverno
        type: Warning
```
