### ISSUE TITLE
[Sample] Check against SubjectAccessReview

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#570]
### Problem Statement

1.10, via PR https://github.com/kyverno/kyverno/pull/6948, will add the ability for K8s API context calls to do POST ops with custom data.

### Solution Description

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: check-subjectaccessreview
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-sar
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
    context:
      - name: subjectaccessreview
        apiCall:
          urlPath: /apis/authorization.k8s.io/v1/subjectaccessreviews
          method: POST
          data:
          - key: kind
            value: SubjectAccessReview
          - key: apiVersion
            value: authorization.k8s.io/v1
          - key: spec
            value:
              resource: "namespace"
              resourceAttributes:
                namespace: "{{ request.namespace }}"
                verb: "delete"
                group: ""
              #user: "{{ request.userInfo.username }}"
              user: "system:serviceaccount:kyverno:kyverno-admission-controller"
    validate:
      message: "User is not authorized."
      deny:
        conditions:
          any:
          - key: "{{ subjectaccessreview.status.allowed }}"
            operator: NotEquals
            value:  true
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
