### ISSUE TITLE
[Sample] Add policy to generate Event upon DELETE operation

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#588]
Kyverno 1.10 will support resource generation upon a DELETE operation. This can be used to do things like generate an Event, for audit purposes, when a resource is deleted.

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: audit-secret
spec:
  background: false
  rules:
  - name: generate-event-on-delete
    match:
      any:
      - resources:
          kinds:
          - Secret
          operations:
          - DELETE
    generate:
      apiVersion: v1
      kind: Event
      name: "delete.{{ random('[a-z0-9]{12}') }}"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: false
      data:
        firstTimestamp: "{{ time_now_utc() }}"
        involvedObject:
          apiVersion: v1
          kind: Secret
          name: "{{ request.name }}"
          namespace: "{{ request.namespace }}"
          uid: "{{request.oldObject.metadata.uid}}"
        lastTimestamp: "{{ time_now_utc() }}"
        message: The {{ request.name }} Secret was deleted by {{ request.userInfo | to_string(@) }}.
        reason: Delete
        source:
          component: kyverno
        type: Warning
```
