### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by salecharohit** [kyverno/policies#594]
### Kyverno Version

1.4.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

EKS

### Description

I am trying to follow the restrict images policy provided in kyverno with the following policy

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-images-to-ecr
  annotations:
    policies.kyverno.io/title: Restrict Images to AWS ECR
    policies.kyverno.io/category: Pod Security, EKS Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      All pods executed by (except the system ones) must be deployed through the ECR registry created in AWS       
spec:
  validationFailureAction: Enforce
  background: true
  namespaceSelector:
    matchExpressions:
      - key: type
        operator: In
        values:
        -  "something"
  rules:
  - name: check-image-registry
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Pods can only use images from the AWS ECR registry"
      pattern:
        spec:
          containers:
            image: "707972254062.dkr.ecr.us-east-2.amazonaws.com/*"
```

But when I try to run a deployment with an image like

```
707972254062.dkr.ecr.us-east-2.amazonaws.com/atsasecr:app-prod-43bc0a
```

The policy is unable to allow this image and errors out.

### Steps to reproduce

1. Spin up an EKS
2. Install Kyverno 
3. Execute the Policy

### Expected behavior

Expected behaviour is to allow the image to run

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
