### ISSUE TITLE
[Sample] Disallow certain commands in probes

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#595]
### Problem Statement

Some commands should be disallowed in probes when used as a poor workaround for correct probes.

### Solution Description

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: probes
  # annotations:
  #   pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-commands
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
        all:
        - key: "{{ length(request.object.spec.containers[].livenessProbe.exec.command[] || `[]`) }}"
          operator: GreaterThan
          value: 0
        - key: "{{ request.operation }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: Cannot use commands `jcmd`, `ps`, or `ls` in liveness probes.
        deny:
          conditions:
            any:
            - key:
              - true
              operator: AnyIn
              value: "{{ request.object.spec.containers[].livenessProbe.exec.command[].regex_match('\\bjcmd\\b',@) }}"
            - key:
              - true
              operator: AnyIn
              value: "{{ request.object.spec.containers[].livenessProbe.exec.command[].regex_match('\\bps\\b',@) }}"
            - key:
              - true
              operator: AnyIn
              value: "{{ request.object.spec.containers[].livenessProbe.exec.command[].regex_match('\\bls\\b',@) }}"
```

### Example "Good" Resource

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: container01
    image: czjunkfoo
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - grep Main
```

### Example "Bad" Resource

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: container01
    image: czjunkfoo
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - jcmd | grep Main
  - name: container02
    image: czjunkfoo
  - name: container03
    image: czjunkfoo
    livenessProbe:
      httpGet:
        port: 8080
  - name: container04
    image: czjunkfoo
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - cat | ls -l
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
