### ISSUE TITLE
[Bug] verifyImages on ECR: context canceled

### ISSUE THREAD

**Issue by chds13** [kyverno/policies#614]
### Kyverno Version

1.9.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

EKS

### Description

When we are trying to verify an image from a private ECR(signatures also in ECR) with more than one signature - we get an error. In my case, it is two signatures.
In kyverno logs we can see:
`"image attestors verification failed" "errors"=".attestors[0].entries[0].keys: Get "7777777777777.dkr.ecr.region-1.amazonaws.com/v2/": context canceled"`
Rising log verbosity doesn't lead to more useful information.

So we have three cases here:
1. If we are verifying only one signature(any of the once described before) - it's ok, rule works correctly
2. If we are using Harbor instead of ECR - it's ok for both signatures and rules work correctly too
3. If we are trying to use two signatures in ECR - then only one signature validates correctly, but the second fails(sometimes fails the first, and the second is ok)

Firstly, I created these checks in one rule, but for investigation I divided them into two different - no influence.

### Steps to reproduce

1. Put image in private ECR
2. Sign it with two different signatures like
`cosign sign --tlog-upload=false --key ~/some_key/cosign.key 7777777777777.dkr.ecr.region-1.amazonaws.com/tag:version`
3. Create two different kyverno policies(or you can create one like in [docs](https://kyverno.io/policies/other/verify_image_with_multi_keys/))
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cosign-qg1-verification(in logs this is just cosign-verification, but it doesn't matter)
spec:
  validationFailureAction: enforce
  background: true
  failurePolicy: Fail
  rules:
    - name: cosign-qg1-verification
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - attestors:
          - count: 1
            entries:
              - keys:
                  secret:
                    name: cosign-qg1-pub
                    namespace: chds-test
          imageReferences:
            - "7777777777777.dkr.ecr.region-1.amazonaws.com/*"
          mutateDigest: true
          required: true
          verifyDigest: true
``` 
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cosign-qg2-verification
spec:
  validationFailureAction: enforce
  background: true
  failurePolicy: Fail
  rules:
    - name: cosign-qg2-verification
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - attestors:
          - count: 1
            entries:
              - keys:
                  secret:
                    name: cosign-qg2-pub
                    namespace: chds-test
          imageReferences:
            - "7777777777777.dkr.ecr.region-1.amazonaws.com/*"
          mutateDigest: true
          required: true
          verifyDigest: true
```
4. Apply manifest:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: chds-test
  labels:
    admission.kyverno: enabled
    audit.kyverno: enabled
    mutation.kyverno: enabled
---
apiVersion: v1
kind: Secret
metadata:
  name: cosign-qg1-pub
  namespace: chds-test
type: Opaque
data:
  cosign.pub: some_public_key
---
apiVersion: v1
kind: Secret
metadata:
  name: cosign-qg2-pub
  namespace: chds-test
type: Opaque
data:
  cosign.pub: another_public_key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chds-test
  namespace: chds-test
  labels:
    app: chds-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chds-label
  template:
    metadata:
      labels:
        app: chds-label
    spec:
      containers:
      - name: chds-test
        image: 7777777777777.dkr.ecr.region-1.amazonaws.com/tag:version
        imagePullPolicy: Always
``` 
5. Check that your pod isn't raised

### Expected behavior

Pods up if all images is signed by both of signatures

### Kyverno logs

```shell
kyverno-645cfff97-9m7xd I0516 09:35:19.335669       1 imageVerifyValidate.go:112] EngineVerifyImages "msg"="missing image metadata in annotation" "key"="kyverno.io/verify-images" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-verification"
kyverno-645cfff97-9m7xd I0516 09:35:19.335719       1 imageVerify.go:329] EngineVerifyImages "msg"="verifying image signatures" "attestations"=0 "attestors"=1 "image"="7777777777777.dkr.ecr.region-1.amazonaws.com/tag:version" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-verification"
kyverno-645cfff97-9m7xd I0516 09:35:26.650509       1 imageVerify.go:511] EngineVerifyImages "msg"="image attestors verification succeeded" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-verification" "requiredCount"=1 "verifiedCount"=1
kyverno-645cfff97-9m7xd I0516 09:35:26.654719       1 imageVerifyValidate.go:112] EngineVerifyImages "msg"="missing image metadata in annotation" "key"="kyverno.io/verify-images" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-qg2-verification"
kyverno-645cfff97-9m7xd I0516 09:35:26.654754       1 imageVerify.go:329] EngineVerifyImages "msg"="verifying image signatures" "attestations"=0 "attestors"=1 "image"="7777777777777.dkr.ecr.region-1.amazonaws.com/tag:version" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-qg2-verification"
kyverno-645cfff97-dtp29 I0516 09:35:29.704538       1 imageVerifyValidate.go:112] EngineVerifyImages "msg"="missing image metadata in annotation" "key"="kyverno.io/verify-images" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-verification"
kyverno-645cfff97-dtp29 I0516 09:35:29.704586       1 imageVerify.go:329] EngineVerifyImages "msg"="verifying image signatures" "attestations"=0 "attestors"=1 "image"="7777777777777.dkr.ecr.region-1.amazonaws.com/tag:version" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-verification"
kyverno-645cfff97-9m7xd I0516 09:35:30.206802       1 cosign.go:82] cosign "msg"="image verification failed" "error"="Get \"https://7777777777777.dkr.ecr.region-1.amazonaws.com/v2/\": context canceled"
kyverno-645cfff97-9m7xd I0516 09:35:30.206855       1 imageVerify.go:520] EngineVerifyImages "msg"="image attestors verification failed" "errors"=".attestors[0].entries[0].keys: Get \"https://7777777777777.dkr.ecr.region-1.amazonaws.com/v2/\": context canceled" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-qg2-verification" "requiredCount"=1 "verifiedCount"=0
kyverno-645cfff97-9m7xd E0516 09:35:30.206885       1 imageVerify.go:384] EngineVerifyImages "msg"="failed to verify image" "error"=".attestors[0].entries[0].keys: Get \"https://7777777777777.dkr.ecr.region-1.amazonaws.com/v2/\": context canceled" "kind"="Pod" "name"="" "namespace"="chds-test" "policy"="cosign-qg2-verification"
kyverno-645cfff97-9m7xd I0516 09:35:33.734674       1 block.go:29] webhooks/resource/mutate "msg"="blocking admission request" "gvk"={"group":"","version":"v1","kind":"Pod"} "kind"="Pod" "name"="" "namespace"="chds-test" "operation"="CREATE" "policy"="cosign-qg2-verification" "uid"="541e98da-7676-4c9f-ac8a-1c23d6006415" "user"={"username":"system:serviceaccount:kube-system:replicaset-controller","uid":"2b742969-38f8-42ff-ac3d-0d93fee19231","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]}
kyverno-645cfff97-9m7xd E0516 09:35:33.734753       1 handlers.go:190] webhooks/resource/mutate "msg"="image verification failed" "error"="\n\npolicy Pod/chds-test/ for resource error: \n\ncosign-qg2-verification:\n  cosign-qg2-verification: 'failed to update digest: failed to fetch image reference:\n    7777777777777.dkr.ecr.region-1.amazonaws.com/tag:version, error:\n    Get \"https://7777777777777.dkr.ecr.region-1.amazonaws.com/v2/\": context canceled'\n" "gvk"={"group":"","version":"v1","kind":"Pod"} "kind"="Pod" "name"="" "namespace"="chds-test" "operation"="CREATE" "uid"="541e98da-7676-4c9f-ac8a-1c23d6006415" "user"={"username":"system:serviceaccount:kube-system:replicaset-controller","uid":"2b742969-38f8-42ff-ac3d-0d93fee19231","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
