### ISSUE TITLE
[Bug] Require StoreClass policy should optionally verify StatefulSet volumeClaimTemplates

### ISSUE THREAD

**Issue by joebowbeerxealth** [kyverno/policies#617]
### Kyverno Version

1.9.x

### Kubernetes Version

1.25.x

### Kubernetes Platform

EKS

### Description

The [Require StorageClass](https://kyverno.io/policies/other/require_storageclass/require_storageclass/) policy does not accommodate StatefulSets that do not have a volume claim template, such the[ argocd-application-controller](https://github.com/argoproj/argo-cd/blob/f356a54f193086b0fd5b8fdc3ea4d3b2e757b995/manifests/install.yaml#L17903).

The policy should be changed to only require storageClassName if it has volumeClaimTemplates:

```yaml
  - name: ss-storageclass
    match:
      any:
      - resources:
          kinds:
          - StatefulSet
    validate:
      message: "StatefulSets must define a storageClassName."
      pattern:
        spec:
          =(volumeClaimTemplates):
            - spec:
                storageClassName: "?*"
```

### Steps to reproduce

```bash
kyverno apply \
  <(curl -sL https://github.com/kyverno/policies/raw/main/other/require-storageclass/require-storageclass.yaml) \
  -r <(curl -sL https://github.com/argoproj/argo-cd/raw/master/manifests/install.yaml)
```

Output:

```plain
Applying 2 policy rules to 56 resources...

policy require-storageclass -> resource default/StatefulSet/argocd-application-controller failed:
1. ss-storageclass: validation error: StatefulSets must define a storageClassName. rule ss-storageclass failed at path /spec/volumeClaimTemplates/

pass: 0, fail: 1, warn: 0, error: 0, skip: 111
```

### Expected behavior

No violation because the StatefulSet does not have a volume claim.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
