### ISSUE TITLE
Add sample to drop CAP_NET_RAW

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#64]
See: https://twitter.com/mrgcastle/status/1396108915109101575

**Comment by JimBugwadia** [comment]
More at:

https://blog.aquasec.com/dns-spoofing-kubernetes-clusters

https://snyk.io/blog/kubernetes-securitycontext-linux-capabilities/

https://www.stackrox.com/post/2020/06/mitigating-kubernetes-cve-2020-10749/

**Comment by chipzoller** [comment]
Do you think we need a separate policy for this if there's the [require drop all policy](https://kyverno.io/policies/best-practices/require_drop_all/require_drop_all/)?

**Comment by chipzoller** [comment]
Bump

**Comment by chipzoller** [comment]
@JimBugwadia last attempt before closing

**Comment by JimBugwadia** [comment]
I would just add as a separate best practice policy and add an OR check across the two.

The description can clarify that when drop all is not possible, at least dropping net raw is required.

Of we can at least add this as a comment in the existing policy.

```
      pattern:
        spec:
          containers:
          - securityContext:
              capabilities:
                drop: ["ALL" | "CAP_NET_RAW"]
          =(initContainers):
          - =(securityContext):
              (capabilities):
                drop: ["ALL" | "CAP_NET_RAW"]
```

**Comment by chipzoller** [comment]
Makes sense. I'll implement this change probably in the existing policy.

**Comment by chipzoller** [comment]
The expression `drop: ["ALL" | "CAP_NET_RAW"]` isn't valid so it's probably just best to make this a separate policy.

**Comment by chipzoller** [comment]
Proposing this:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-cap-net-raw
  annotations:
    policies.kyverno.io/title: Drop CAP_NET_RAW
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access. The
      CAP_NET_RAW capability, enabled by default, allows processes in a container to
      forge packets and bind to any interface potentially leading to MitM attacks.
      This sample ensures that all containers explicitly drop the CAP_NET_RAW
      ability.
spec:
  validationFailureAction: enforce
  rules:
  - name: drop-cap-net-raw
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "The capability CAP_NET_RAW must be explicitly dropped."
      pattern:
        spec:
          containers:
          - securityContext:
              capabilities:
                drop: ["CAP_NET_RAW"]
          =(initContainers):
          - securityContext:
              capabilities:
                drop: ["CAP_NET_RAW"]
```

Notice that this is slightly different in the anchors for initContainers when compared to the [drop all policy](https://kyverno.io/policies/best-practices/require_drop_all/require_drop_all/). I'm thinking the drop all needs to modified like this. Agree/disagree?
