### ISSUE TITLE
[Bug] Require Signed Tekton Task

### ISSUE THREAD

**Issue by dirien** [kyverno/policies#640]
### Kyverno Version

1.10.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

Other (specify in description)

### Description

I installed the `ClusterPolicy` via `https://raw.githubusercontent.com/kyverno/policies/main/tekton/verify-tekton-taskrun-signatures/verify-tekton-taskrun-signatures.yaml`

And then created a `TaskRun` with a bundle:

```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-run
spec:
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: output
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: url
      value: https://github.com/kelseyhightower/nocode
  taskRef:
    name: git-clone
    bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.9
```

The image is not signed with the key in the policy:

```bash
cosign verify --key key  gcr.io/tekton-releases/catalog/upstream/git-clone:0.9
Error: no signatures found for image
main.go:69: error during command execution: no signatures found for image
```

The logs in  kyverno shows that no matching signatures are found but still pass the validation.

### Steps to reproduce

1. Install Tekton
2. Install ClusterPolicy -> https://raw.githubusercontent.com/kyverno/policies/main/tekton/verify-tekton-taskrun-signatures/verify-tekton-taskrun-signatures.yaml
3. Apply Task Run (see description from above)
4. TaskRun pass validation

### Expected behavior

No pass valiadtion

### Kyverno logs

```shell
I0611 13:23:18.837140       1 event.go:307] "Event occurred" object="default/git-clone-run" fieldPath="" kind="TaskRun" apiVersion="tekton.dev/v1" type="Warning" reason="PolicyViolation" message=<policy signed-tekton-task-bundle/check-signature fail: failed to verify image gcr.io/tekton-releases/catalog/upstream/git-clone@sha256:1ee0f45892faf152aa631b0745f192e353c684408286bc55e9041edfaf22cb5e: .attestors[0].entries[0].keys: no matching signatures:>     


...

I0611 13:24:08.755627       1 event.go:307] "Event occurred" object="signed-tekton-task-bundle" fieldPath="" kind="ClusterPolicy" apiVersion="kyverno.io/v1" type="Normal" reason="PolicyApplied" message="TaskRun default/git-clone-run: pass"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
The policy is in `audit` mode which means resources which violate it will still be created. There will be events and policy reports which indicate it failed. This is by design.

**Comment by dirien** [comment]
hey @chipzoller,

thanks for the feedback. The Reports shows pass:

![image](https://github.com/kyverno/policies/assets/38325136/6ac67149-0b2f-45f7-b8dd-5cb8476f72c4)
![image](https://github.com/kyverno/policies/assets/38325136/1c668276-129e-420d-902c-5d86e459e6ab)


Maybe I do something wrong. Thanks for the help

**Comment by chipzoller** [comment]
Logs indicate signature verification failed:

```log
kyverno-admission-controller-576d658464-pld2g kyverno I0611 15:19:37.519393       1 cosign.go:62] cosign "msg"="image verification failed" "error"="no matching signatures:\n"
kyverno-admission-controller-576d658464-pld2g kyverno I0611 15:19:37.519503       1 imageverifier.go:424] engine.verify "msg"="image attestors verification failed" "errors"=".attestors[0].entries[0].keys: no matching signatures:\n" "new.kind"="TaskRun" "new.name"="git-clone-run" "new.namespace"="default" "policy.apply"="All" "policy.name"="signed-tekton-task-bundle" "policy.namespace"="" "requiredCount"=1 "rule.name"="check-signature" "verifiedCount"=0
kyverno-admission-controller-576d658464-pld2g kyverno E0611 15:19:37.519544       1 imageverifier.go:291] engine.verify "msg"="failed to verify image" "error"=".attestors[0].entries[0].keys: no matching signatures:\n" "new.kind"="TaskRun" "new.name"="git-clone-run" "new.namespace"="default" "policy.apply"="All" "policy.name"="signed-tekton-task-bundle" "policy.namespace"="" "rule.name"="check-signature"
```

Policy Report initially listed as `pass` then changes to `error`:

```yaml
results:
- category: Tekton
  message: 'failed to instantiate handler: failed to extract images: invalid key'
  policy: signed-tekton-task-bundle
  resources:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: git-clone-run
    namespace: default
    uid: e7732a8c-4862-4024-9599-b1c1870dd8b1
  result: error
  rule: check-signature
  scored: true
  severity: medium
  source: kyverno
  timestamp:
    nanos: 0
    seconds: 1686496808
```
