### ISSUE TITLE
[Bug] Polocy do prevent deletion works for CRD but not for Deployment

### ISSUE THREAD

**Issue by chmodrs** [kyverno/policies#645]
### Kyverno Version

1.7.x

### Kubernetes Version

1.22.x

### Kubernetes Platform

EKS

### Description

Hi,

I need to create some policies to protect system resources, like some CRDs, deployments, Istio gateways.

I create the following policy to protect some CRDs and works.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-crds-deletion
  annotations:
    policies.kyverno.io/description: 'Kubernetes RBAC allows for controls on kinds
      of resources or those with specific names. But it does not have the type of
      granularity often required in more complex environments. This policy restricts
      updates and deletes to Custom Resource Definition.'
    policies.kyverno.io/subject: RBAC
    policies.kyverno.io/title: Block CRDs Deletion
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - exclude:
      all:
      - resources:
          selector:
            matchLabels:
              allow-deletion: "yes"
    match:
      resources:
        kinds:
        - CustomResourceDefinition
        names:
        - "*istio*"
        - "istio*"
        - "*kong*"
    name: block-crds-deletion
    validate:
      message: "This resource is protected and changes are not allowed. Please contact
          psm-platform squad."
      deny:
        conditions:
          all:
          - key: '{{request.operation}}'
            operator: In
            value:
            - DELETE
            - UPDATE
```
      

but i tried to create almost the same policy, just changing name and kind to protect Deployment and ReplicaSets, but i still can delete.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-system-resources
  annotations:
    policies.kyverno.io/description: 'Kubernetes RBAC allows for controls on kinds
      of resources or those with specific names. But it does not have the type of
      granularity often required in more complex environments. This policy restricts
      updates and deletes to Custom Resource Definition.'
    policies.kyverno.io/subject: RBAC
    policies.kyverno.io/title: Protect System Resources
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - exclude:
      all:
      - resources:
          selector:
            matchLabels:
              allow-deletion: "yes"
    match:
      resources:
        kinds:
        - Deployment
        names:
        - "nginx-deployment"
    name: protect-system-resources
    validate:
      message: "This resource is protected and changes are not allowed. Please contact
          psm-platform squad."
      deny:
        conditions:
          any:
          - key: '{{request.operation}}'
            operator: In
            value:
            - DELETE
            - UPDATE
```
     

Does anyone have an idea of what I made wrong?

Thanks!

### Steps to reproduce

1. Create the first policy and try to delete resources with the name -> you cannot delete
2. Create the second policy and try to delete resources with -> you will can

### Expected behavior

I expect to cannot delete deployments with name that i configure in second policy

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
You must use `any` or `all` for BOTH `match` and `exclude` blocks, you can't just use it in once place.

Also, the `In` and `NotIn` operators are deprecated. Please use `AnyIn` in this situation.

**Comment by chmodrs** [comment]
Hi @chipzoller, thanks for your reply.

nice! now I understand. But maybe I still doing something wrong, because I still can delete "nginx-deployment"

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-system-resources
  annotations:
    policies.kyverno.io/description: 'Kubernetes RBAC allows for controls on kinds
      of resources or those with specific names. But it does not have the type of
      granularity often required in more complex environments. This policy restricts
      updates and deletes to Custom Resource Definition.'
    policies.kyverno.io/subject: RBAC
    policies.kyverno.io/title: Protect System Resources
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - exclude:
      any:
      - resources:
          selector:
            matchLabels:
              allow-deletion: "yes"
    match:
      any:
      - resources:
          kinds:
          - Deployment
          names:
          - "nginx*"
    name: protect-system-resources
    validate:
      message: "This resource is protected and changes are not allowed. Please contact
          psm-platform squad."
      deny:
        conditions:
          any:
          - key: '{{request.operation}}'
            operator: AnyIn
            value:
            - DELETE
            - UPDATE
```

**Comment by chmodrs** [comment]
weird that, with the same policy, i can protect CRD, but dont Deployment or replicasets, for example, like below::


```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-system-resources
  annotations:
    policies.kyverno.io/description: 'Kubernetes RBAC allows for controls on kinds
      of resources or those with specific names. But it does not have the type of
      granularity often required in more complex environments. This policy restricts
      updates and deletes to Custom Resource Definition.'
    policies.kyverno.io/subject: RBAC
    policies.kyverno.io/title: Protect System Resources
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: protect-system-resources
    exclude:
      all:
      - resources:
          selector:
            matchLabels:
              allow-deletion: "yes"
    match:
      all:
      - resources:
          kinds:
          - CustomResourceDefinition
          names:
          - "myapps*"
    validate:
      message: "This resource is protected and changes are not allowed. Please contact
          psm-platform squad."
      deny:
        conditions:
          all:
          - key: '{{request.operation}}'
            operator: AnyIn
            value:
            - DELETE
```
      
if i tried to delete CRD

```
$ kubectl delete crd myapps.example.com
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request:

resource CustomResourceDefinition//myapps.example.com was blocked due to the following policies

protect-system-resources:
  protect-system-resources: This resource is protected and changes are not allowed.
    Please contact psm-platform squad.
```

But just changing kind and names:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-system-resources
  annotations:
    policies.kyverno.io/description: 'Kubernetes RBAC allows for controls on kinds
      of resources or those with specific names. But it does not have the type of
      granularity often required in more complex environments. This policy restricts
      updates and deletes to Custom Resource Definition.'
    policies.kyverno.io/subject: RBAC
    policies.kyverno.io/title: Protect System Resources
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: protect-system-resources
    exclude:
      all:
      - resources:
          selector:
            matchLabels:
              allow-deletion: "yes"
    match:
      all:
      - resources:
          kinds:
          - Deployment
          names:
          - "nginx*"
    validate:
      message: "This resource is protected and changes are not allowed. Please contact
          psm-platform squad."
      deny:
        conditions:
          all:
          - key: '{{request.operation}}'
            operator: AnyIn
            value:
            - DELETE
```
     
And tried delete deployment called: nginx-deployment

```
$ kubectl delete deploy nginx-deployment
deployment.apps "nginx-deployment" deleted
```
