### ISSUE TITLE
[Sample] add-capabilities policy doesn't check "ephemeralcontainers" and "initcontainers"

### ISSUE THREAD

**Issue by marcoval123** [kyverno/policies#650]
### Problem Statement

The following policy only checks and mutate if pod contains containers: https://kyverno.io/policies/psp-migration/add-capabilities/add-capabilities/

Note that, a pod could contains ephemeralcontainers, initcontainers and containers. For exemple, this policy "https://kyverno.io/policies/pod-security/baseline/disallow-capabilities/disallow-capabilities/" is checking for all containers types.

### Solution Description

We need policy example to mutate and check capabilities when a pod contains a ephemeralcontainers, initcontainers or containers.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Yes, we don't modify absolutely every policy to include this, but, for example, the PSS policies do have these checks. You can easily modify this or any other policy to your liking with these similar checks.

**Comment by chipzoller** [comment]
This policy, and others like it which use `foreach` methods to mutate containers, can be modified by simply adding another loop but for initContainers:

```yaml
      - list: request.object.spec.initContainers[] || `[]`
        preconditions:
          all:
          - key: SETFCAP
            operator: AnyNotIn
            value: "{{ element.securityContext.capabilities.drop[] || `[]` }}"
        patchesJson6902: |-
          - path: /spec/initContainers/{{elementIndex}}/securityContext/capabilities/add/-
            op: add
            value: SETFCAP          
```
