### ISSUE TITLE
[Bug] Permission checks fail on Kubernetes 1.24

### ISSUE THREAD

**Issue by jamalshahverdiev** [kyverno/policies#654]
### Kyverno Version

1.10.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

EKS

### Description

Hi Kyverno team.
I am trying to apply the following `ClusterPolicy` rule to my Kubernetes cluster.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restart-daemonset-on-secret-change
  annotations:
    policies.kyverno.io/title: Restart DaemonSet On Secret Change
    policies.kyverno.io/category: other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: DaemonSet
    kyverno.io/kyverno-version: 1.10.0
    policies.kyverno.io/minversion: 1.10.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/description: >-
      If Secrets are mounted in ways which do not naturally allow updates to
      be live refreshed it may be necessary to modify a DaemonSet. This policy
      watches a Secret and if it changes will write an annotation
      to one or more target DaemonSets thus triggering a new rollout and thereby
      refreshing the referred Secret. It may be necessary to grant additional privileges
      to the Kyverno ServiceAccount, via one of the existing ClusterRoleBindings or a new
      one, so it can modify DaemonSets.
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
  - name: update-secret-in-daemonset
    match:
      any:
      - resources:
          kinds:
          - Secret
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
      - key: "{{request.object.metadata.ownerReferences[0].kind}}"
        operator: Equals
        value: DaemonSet
      - key: '{{request.object.metadata.annotations."kyverno.domain.tech/read"}}'
        operator: Equals
        value: allow
      - key: "{{ equal_fold('{{request.object.data}}', '{{request.oldObject.data}}') }}"
        operator: NotEquals
        value: true      
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: DaemonSet
          name: "{{request.object.metadata.ownerReferences[0].name}}"
          namespace: "{{request.object.metadata.namespace}}"        
      patchStrategicMerge:
        spec:
          template:
            metadata:
              annotations: 
                kyverno.dif.tech/secretversion: '{{request.object.metadata.resourceVersion}}'

```

But getting this error.

```
one or more objects failed to apply, reason: admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].mutate.targets.: auth check fails, require additional privileges, update the ClusterRole 'kyverno:background-controller:additional':failed to get the Group Version Resource for kind DaemonSet;
```

Already created  `ClusterRole` with `ClusterRolebinding` which it required at the `ClusterPolicy` apply time. Just for you information in the Kubernetes version `1.25.5` and `1.26.5` will be enough to give an access only for `kyverno-background-controller`  service account and it works fine (In the kubernetes version 1.24 I have tried in the `ClusterRole` even all `*` in `apiGroups`, `resources` and `verbs`. It doesn't work too). 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:background-controller:additional
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-background-controller-additional-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:background-controller:additional
subjects:
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
- kind: ServiceAccount
  name: kyverno-cleanup-controller
  namespace: kyverno
- kind: ServiceAccount
  name: kyverno-cleanup-jobs
  namespace: kyverno
- kind: ServiceAccount
  name: kyverno-reports-controller
  namespace: kyverno
```

I have tried to get some logical errors from API server logs too (nothing).

### Steps to reproduce

1. The same version of `Kyverno` with the same `ClusterRole` and `ClusterRolebindings` (only with `kyverno-background-controller` service account) works fine in the Kubernetes version `1.25.5` and `1.26.5`

### Expected behavior

I expect to work with this `ClusterPolicy` rule in the Kubernetes `1.24.x` because I got this information from your official page Combability matrix (1.10.x | 1.24 | 1.26).

### Kyverno logs

```shell
E0619 14:14:22.568154       1 handlers.go:38] webhooks/policy/validate "msg"="policy validation errors" "error"="path: spec.rules[0].mutate.targets.: auth check fails, require additional privileges, update the ClusterRole 'kyverno:background-controller:additional':failed to get the Group Version Resource for kind DaemonSet; failed to get the Group Version Resource for kind DaemonSet" "gvk"={"group":"kyverno.io","version":"v1","kind":"ClusterPolicy"} "gvr"={"group":"kyverno.io","version":"v1","resource":"clusterpolicies"} "name"="restart-daemonset-on-secret-change" "namespace"="" "operation"="CREATE" "uid"="" "user"={"username":"kubernetes-admin","uid":"","groups":["system:masters","system:authenticated"],"extra":{"accessKeyId":[""],"arn":[""],"canonicalArn":[""],"principalId":[""],"sessionName":[""]}}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jamalshahverdiev** [comment]
In the same cluster `1.24` works fine same `ClusterPolicy` rule with the Kyverno version `1.8.5`

**Comment by chipzoller** [comment]
I just applied your policy to a 1.24 cluster after assigning the necessary permissions using this aggregating ClusterRole:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
  name: kyverno:update-daemonsets
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - update
```

```sh
$ k apply -f perms.yaml 
clusterrole.rbac.authorization.k8s.io/kyverno:update-daemonsets created

$ k apply -f cpol.yaml 
clusterpolicy.kyverno.io/restart-daemonset-on-secret-change created

$ helm ls -n kyverno
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kyverno kyverno         1               2023-06-20 19:12:24.1334319 -0400 EDT   deployed        kyverno-3.0.1   v1.10.0
```

**Comment by jamalshahverdiev** [comment]
Are you sure it is looking to this ClusterRole with name kyverno:update-daemonsets? Even from logs it says I require kyverno:background-controller:additional

**Comment by jamalshahverdiev** [comment]
I tested it again right now. Kubernetes version `v1.24.13`  

```
kubectl get deployment -n kyverno
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
kyverno-admission-controller    1/1     1            1           48m
kyverno-background-controller   1/1     1            1           48m
kyverno-cleanup-controller      1/1     1            1           48m
kyverno-reports-controller      1/1     1            1           48m
```

This is all `clusterroles`
```
kubectl get clusterrole | grep kyverno
kyverno-cleanup-jobs                                                   2023-06-21T07:38:22Z
kyverno:admission-controller                                           2023-06-21T07:38:22Z
kyverno:admission-controller:core                                      2023-06-21T07:38:22Z
kyverno:background-controller                                          2023-06-21T07:38:22Z
kyverno:background-controller:additional                               2023-06-21T07:38:22Z
kyverno:background-controller:core                                     2023-06-21T07:38:22Z
kyverno:cleanup-controller                                             2023-06-21T07:38:22Z
kyverno:cleanup-controller:core                                        2023-06-21T07:38:22Z
kyverno:rbac:admin:policies                                            2023-06-21T07:38:22Z
kyverno:rbac:admin:policyreports                                       2023-06-21T07:38:22Z
kyverno:rbac:admin:reports                                             2023-06-21T07:38:22Z
kyverno:rbac:admin:updaterequests                                      2023-06-21T07:38:22Z
kyverno:rbac:view:policies                                             2023-06-21T07:38:22Z
kyverno:rbac:view:policyreports                                        2023-06-21T07:38:22Z
kyverno:rbac:view:reports                                              2023-06-21T07:38:22Z
kyverno:rbac:view:updaterequests                                       2023-06-21T07:38:22Z
kyverno:reports-controller                                             2023-06-21T07:38:22Z
kyverno:reports-controller:core                                        2023-06-21T07:38:22Z
kyverno:update-daemonsets                                              2023-06-21T07:53:39Z
```

The content of the ClusterRole which you wrote same as mine which I created 

```
kubectl get clusterrole kyverno:update-daemonsets -o yaml | kubectl neat
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
  name: kyverno:update-daemonsets
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - update
```

The same output it says I need `ClusterRole` `kyverno:background-controller:additional` than `kyverno:update-daemonsets`

```
Error from server: error when creating "helm/kyverno/kyverno/kyverno/templates/08-clusterpolicy-daemonsets.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].mutate.targets.: auth check fails, require additional privileges, update the ClusterRole 'kyverno:background-controller:additional':failed to get the Group Version Resource for kind DaemonSet; failed to get the Group Version Resource for kind DaemonSet
```

Thank is the output of ClusterRole which it requires

```
kubectl get clusterrole kyverno:background-controller:additional -o yaml | kubectl neat
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
  name: kyverno:background-controller:additional
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

And `ClusterRoleBinding` which gives to SA to work with `ClusterRole`

```
kubectl get clusterrolebinding kyverno-background-controller-additional-binding -o yaml      
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2023-06-21T07:38:22Z"
  labels:
    dif.tech/argocd: kyverno-dt-dev-euc1-infra
  name: kyverno-background-controller-additional-binding
  resourceVersion: "238669103"
  uid: a2d04c78-b7b3-46f0-abbe-102df49bc605
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:background-controller:additional
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
```

The result is the same.

**Comment by Flydiverny** [comment]
We are seeing similar error on same versions when trying to update to new helm chart and new kyverno version.

Kyverno Version
1.10.x

Kubernetes Version
1.24.x

Kubernetes Platform
EKS


Example policy

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: test-namespace-team-label
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: reuse-namespace-team-label
      context:
        - name: nsTeam
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}"
            jmesPath: "metadata.labels.team"
      match:
        any:
          - resources:
              kinds:
                - Deployment
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
        patchStrategicMerge:
          metadata:
            labels:
              +(team-mma): "mma-test"
```

result

```
Error from server: error when creating "test-label-policy.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].mutate.targets.: auth check fails, require additional privileges, update the ClusterRole 'kyverno:background-controller:additional':failed to get the Group Version Resource for kind Deployment; failed to get the Group Version Resource for kind Deployment
```

We've tried a bunch of different RBAC constellations but cannot get it to work.

![image](https://github.com/kyverno/policies/assets/326929/7deaa626-009c-4633-8373-32a9dfd038c1)

My colleague has also managed to run things fine on a local cluster, so we are scratching our heads here and I'm getting ready to blame EKS at this point 😅
