### ISSUE TITLE
[Bug] Unable to validate SLSA provenance on Tekton Chains image

### ISSUE THREAD

**Issue by bradbeck** [kyverno/policies#655]
### Kyverno Version

1.9.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

Minikube

### Description

Unable to validate SLSA provenance on Tekton Chains image.

### Steps to reproduce

1. Create mock deployment of Tekton Chains (`chains.yaml`)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tekton-chains-controller
  namespace: tekton-chains
spec:
  containers:
  - image: gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller:v0.16.0@sha256:4923b3aa31130aaa44c2fd58d1b40afbe35afbaf5e01dca3dcfb9708cf2574c8
    name: tekton-chains-controller
```

2. Create ClusterPolicy to check SLSA attestation (`cp.yaml`)

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-code-review
spec:
  background: false
  failurePolicy: Fail
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
  - match:
      resources:
        kinds:
        - Pod
        namespaces:
        - tekton-pipelines
        - tekton-chains
    name: attest-code-review
    verifyImages:
    - imageReferences:
      - gcr.io/tekton-releases/github.com/tektoncd/*
      attestations:
      - predicateType: https://slsa.dev/provenance/v0.2
        attestors:
        - entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnLNw3RYx9xQjXbUEw8vonX3U4+tB
                kPnJq+zt386SCoG0ewIH5MB8+GjIDGArUULSDfjfM31Eae/71kavAUI0OA==
                -----END PUBLIC KEY-----
              signatureAlgorithm: sha256
        conditions:
        - all:
          - key: '{{ builder.id }}'
            operator: Equals
            value: https://tekton.dev/chains/v2
          - key: '{{ buildType }}'
            operator: Equals
            value: https://tekton.dev/attestations/chains@v2
```

3. Apply the policy with Kyverno CLI

```shell
$ kyverno apply -v 1 cp.yaml --resource chains.yaml                           

Applying 1 policy rule to 1 resource...
I0620 15:39:27.227318   17648 imageverifier.go:541] engine.verify "msg"="checking attestation" "image"="gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller@sha256:4923b3aa31130aaa44c2fd58d1b40afbe35afbaf5e01dca3dcfb9708cf2574c8" "new.kind"="Pod" "new.name"="tekton-chains-controller" "new.namespace"="tekton-chains" "policy.apply"="All" "policy.name"="attest-code-review" "policy.namespace"="" "predicates"=["https://slsa.dev/provenance/v0.2"] "rule.name"="attest-code-review"

policy attest-code-review -> resource tekton-chains/Pod/tekton-chains-controller failed: 
1. attest-code-review: .attestations[0].attestors[0].entries[0].keys: attestation checks failed for gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller@sha256:4923b3aa31130aaa44c2fd58d1b40afbe35afbaf5e01dca3dcfb9708cf2574c8 and predicate https://slsa.dev/provenance/v0.2:  

pass: 0, fail: 1, warn: 0, error: 0, skip: 2 
```

### Expected behavior

The policy should pass.

If we put the public key in a file (`tekton.pem`):

```txt
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnLNw3RYx9xQjXbUEw8vonX3U4+tB
kPnJq+zt386SCoG0ewIH5MB8+GjIDGArUULSDfjfM31Eae/71kavAUI0OA==
-----END PUBLIC KEY-----
```

Then we can verify the attestation with Cosign:

```shell
$ cosign verify-attestation --type https://slsa.dev/provenance/v0.2 --key tekton.pem gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller@sha256:4923b3aa31130aaa44c2fd58d1b40afbe35afbaf5e01dca3dcfb9708cf2574c8      

Verification for gcr.io/tekton-releases/github.com/tektoncd/chains/cmd/controller@sha256:4923b3aa31130aaa44c2fd58d1b40afbe35afbaf5e01dca3dcfb9708cf2574c8 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The claims were present in the transparency log
  - The signatures were integrated into the transparency log when the certificate was valid
  - The signatures were verified against the specified public key
{"payloadType":"application/vnd.in-toto+json","payload":"eyJfdHlwZSI6Imh0dHBzOi8vaW4tdG90by5pby9TdGF0ZW1lbnQvdjAuMSIsInByZWRpY2F0ZVR5cGUiOiJodHRwczovL3Nsc2EuZGV2L3Byb3ZlbmFuY2UvdjAuMiIsInN1YmplY3QiOlt7Im5hbWUiOiJhc2lhLmdjci5pby90ZWt0b24tcmVsZWFzZXMvZ2l0aHViLmNvbS90ZWt0b25jZC9jaGFpbnMvY21kL2NvbnRyb2xsZXIiLCJkaWdlc3QiOnsic2hhMjU2IjoiNDkyM2IzYWEzMTEzMGFhYTQ0YzJmZDU4ZDFiNDBhZmJlMzVhZmJhZjVlMDFkY2EzZGNmYjk3MDhjZjI1NzRjOCJ9fSx7Im5hbWUiOiJldS5nY3IuaW8vdGVrdG9uLXJlbGVhc2VzL2dpdGh1Yi5jb20vdGVrdG9uY2QvY2hhaW5zL2NtZC9jb250cm9sbGVyIiwiZGlnZXN0Ijp7InNoYTI1NiI6IjQ5MjNiM2FhMzExMzBhYWE0NGMyZmQ1OGQxYjQwYWZiZTM1YWZiYWY1ZTAxZGNhM2RjZmI5NzA4Y2YyNTc0YzgifX0seyJuYW1lIjoiZ2NyLmlvL3Rla3Rvbi1yZWxlYXNlcy9naXRodWIuY29tL3Rla3RvbmNkL2NoYWlucy9jbWQvY29udHJvbGxlciIsImRpZ2VzdCI6eyJzaGEyNTYiOiI0OTIzYjNhYTMxMTMwYWFhNDRjMmZkNThkMWI0MGFmYmUzNWFmYmFmNWUwMWRjYTNkY2ZiOTcwOGNmMjU3NGM4In19LHsibmFtZSI6InVzLmdjci5pby90ZWt0b24tcmVsZWFzZXMvZ2l0aHViLmNvbS90ZWt0b25jZC9jaGFpbnMvY21kL2NvbnRyb2xsZXIiLCJkaWdlc3QiOnsic2hhMjU2IjoiNDkyM2IzYWEzMTEzMGFhYTQ0YzJmZDU4ZDFiNDBhZmJlMzVhZmJhZjVlMDFkY2EzZGNmYjk3MDhjZjI1NzRjOCJ9fV0sInByZWRpY2F0ZSI6eyJidWlsZGVyIjp7ImlkIjoiaHR0cHM6Ly90ZWt0b24uZGV2L2NoYWlucy92MiJ9LCJidWlsZFR5cGUiOiJ0ZWt0b24uZGV2L3YxYmV0YTEvVGFza1J1biIsImludm9jYXRpb24iOnsiY29uZmlnU291cmNlIjp7fSwicGFyYW1ldGVycyI6eyJDSEFJTlMtR0lUX0NPTU1JVCI6IjVjYTQyNjRkMzQ5NjliYTM3Y2I1YWQwNzk5ZGEyZmZkMDc3ZjM3MzUiLCJDSEFJTlMtR0lUX1VSTCI6Imh0dHBzOi8vZ2l0aHViLmNvbS90ZWt0b25jZC9jaGFpbnMiLCJpbWFnZVJlZ2lzdHJ5IjoiZ2NyLmlvIiwiaW1hZ2VSZWdpc3RyeVBhdGgiOiJ0ZWt0b24tcmVsZWFzZXMiLCJpbWFnZVJlZ2lzdHJ5UmVnaW9ucyI6InVzIGV1IGFzaWEiLCJpbWFnZXMiOiJjb250cm9sbGVyIiwicGFja2FnZSI6ImdpdGh1Yi5jb20vdGVrdG9uY2QvY2hhaW5zIiwicGxhdGZvcm1zIjoibGludXgvYW1kNjQsbGludXgvYXJtNjQsbGludXgvcHBjNjRsZSxsaW51eC9zMzkweCIsInJlbGVhc2VBc0xhdGVzdCI6InRydWUiLCJzZXJ2aWNlQWNjb3VudFBhdGgiOiJyZWxlYXNlLmpzb24iLCJ2ZXJzaW9uVGFnIjoidjAuMTYuMCJ9fSwiYnVpbGRDb25maWciOnsic3RlcHMiOlt7ImVudHJ5UG9pbnQiOiIjIS9idXN5Ym94L3NoXG5zZXQgLWV4XG5cbiMgTG9naW4gdG8gdGhlIGNvbnRhaW5lciByZWdpc3RyeVxuRE9DS0VSX0NPTkZJRz0kKGNhdCAke0NPTlRBSU5FUl9SRUdJU1RZX0NSRURFTlRJQUxTfSB8IFxcXG4gIGNyYW5lIGF1dGggbG9naW4gLXUgX2pzb25fa2V5IC0tcGFzc3dvcmQtc3RkaW4gZ2NyLmlvIDJcdTAwM2VcdTAwMjYxIHwgXFxcbiAgc2VkICdzLF4uKmxvZ2dlZCBpbiB2aWEgXFwoLipcXCkkLFxcMSxnJylcblxuIyBBdXRoIHdpdGggYWNjb3VudCBjcmVkZW50aWFscyBmb3IgYWxsIHJlZ2lvbnMuXG5mb3IgcmVnaW9uIGluICR7UkVHSU9OU31cbmRvXG4gIEhPU1ROQU1FPSR7cmVnaW9ufS5nY3IuaW9cbiAgY2F0ICR7Q09OVEFJTkVSX1JFR0lTVFlfQ1JFREVOVElBTFN9IHwgY3JhbmUgYXV0aCBsb2dpbiAtdSBfanNvbl9rZXkgLS1wYXNzd29yZC1zdGRpbiAke0hPU1ROQU1FfVxuZG9uZVxuY3AgJHtET0NLRVJfQ09ORklHfSAvd29ya3NwYWNlL2RvY2tlci1jb25maWcuanNvblxuIiwiYXJndW1lbnRzIjpudWxsLCJlbnZpcm9ubWVudCI6eyJjb250YWluZXIiOiJjb250YWluZXItcmVnaXN0eS1hdXRoIiwiaW1hZ2UiOiJnY3IuaW8vZ28tY29udGFpbmVycmVnaXN0cnkvY3JhbmVAc2hhMjU2OjE2NWYyMzMxZDkwOTAxY2QxNjFiYjVhMGI1YzNiZDM0Yjg0NGE1MWFmMWI1Y2ZiZTZlZDM1ZDU1ZjVkODAxZGUifSwiYW5ub3RhdGlvbnMiOm51bGx9LHsiZW50cnlQb2ludCI6IiMhL3Vzci9iaW4vZW52IHNoXG5zZXQgLWV4XG5cbiMgU2V0dXAgZG9ja2VyLWF1dGhcbkRPQ0tFUl9DT05GSUc9fi8uZG9ja2VyXG5ta2RpciAtcCAke0RPQ0tFUl9DT05GSUd9XG5jcCAvd29ya3NwYWNlL2RvY2tlci1jb25maWcuanNvbiAke0RPQ0tFUl9DT05GSUd9L2NvbmZpZy5qc29uXG5cbiMgQ2hhbmdlIHRvIGRpcmVjdG9yeSB3aXRoIG91ciAua28ueWFtbFxuY2QgJHtQUk9KRUNUX1JPT1R9XG5cbiMgRm9yIGVhY2ggY21kLyogZGlyZWN0b3J5LCBpbmNsdWRlIGEgZnVsbCBnemlwcGVkIHRhciBvZiBhbGwgc291cmNlIGluXG4jIHZlbmRvci8uIFRoaXMgaXMgb3ZlcmtpbGwuIFNvbWUgZGVwcycgbGljZW5zZXMgcmVxdWlyZSB0aGUgc291cmNlIHRvIGJlXG4jIGluY2x1ZGVkIGluIHRoZSBjb250YWluZXIgaW1hZ2Ugd2hlbiB0aGV5J3JlIHVzZWQgYXMgYSBkZXBlbmRlbmN5LlxuIyBSYXRoZXIgdGhhbiB0cnlpbmcgdG8gZGV0ZXJtaW5lIHdoaWNoIGRlcHMgaGF2ZSB0aGlzIHJlcXVpcmVtZW50IChhbihwYXJhbXMuaW1hZ2VSZWdpc3RyeWRcbiMgcHJvYmFibHkgZ2V0IGl0IHdyb25nKSwgd2UnbGwganVzdCB0YXJneiB1cCB0aGUgd2hvbGUgdmVuZG9yIHRyZWUgYW5kXG4jIGluY2x1ZGUgaXQuIEFzIG9mIDkvMjAvMjAxOSwgdGhpcyBhbW91bnRzIHRvIGFib3V0IDExTUIgb2YgYWRkaXRpb25hbFxuIyBkYXRhIGluIGVhY2ggaW1hZ2UuXG5UTVBESVI9JChta3RlbXAgLWQpXG50YXIgY2Z6ICR7VE1QRElSfS9zb3VyY2UudGFyLmd6IHZlbmRvci9cbmZvciBkIGluIGNtZC8qOyBkb1xuICBpZiBbIC1kICR7ZH0va29kYXRhLyBdOyB0aGVuXG4gICAgbG4gLXMgJHtUTVBESVJ9L3NvdXJjZS50YXIuZ3ogJHtkfS9rb2RhdGEvXG4gIGZpXG5kb25lXG5cbiMgUmV3cml0ZSBcImRldmVsXCIgdG8gcGFyYW1zLnZlcnNpb25UYWdcbnNlZCAtaSAtZSAncy9cXChjaGFpbnMudGVrdG9uLmRldlxcL3JlbGVhc2VcXCk6IFwiZGV2ZWxcIi9cXDE6IFwidjAuMTYuMFwiL2cnIC1lICdzL1xcKGFwcC5rdWJlcm5ldGVzLmlvXFwvdmVyc2lvblxcKTogXCJkZXZlbFwiL1xcMTogXCJ2MC4xNi4wXCIvZycgLWUgJ3MvXFwodmVyc2lvblxcKTogXCJkZXZlbFwiL1xcMTogXCJ2MC4xNi4wXCIvZycgJHtQUk9KRUNUX1JPT1R9L2NvbmZpZy8qLnlhbWxcblxuIyBQdWJsaXNoIGltYWdlcyBhbmQgY3JlYXRlIHJlbGVhc2UueWFtbFxubWtkaXIgLXAgJE9VVFBVVF9SRUxFQVNFX0RJUlxuXG5rbyByZXNvbHZlIC0tcGxhdGZvcm09bGludXgvYW1kNjQsbGludXgvYXJtNjQsbGludXgvcHBjNjRsZSxsaW51eC9zMzkweCAtLXByZXNlcnZlLWltcG9ydC1wYXRocyAtdCB2MC4xNi4wIC1mICR7UFJPSkVDVF9ST09UfS9jb25maWcvIFx1MDAzZSAkT1VUUFVUX1JFTEVBU0VfRElSL3JlbGVhc2UueWFtbFxuXG4jIFB1Ymxpc2ggaW1hZ2VzIGFuZCBjcmVhdGUgcmVsZWFzZS5ub3RhZ3MueWFtbFxuIyBUaGlzIGlzIHVzZWZ1bCBpZiB5b3VyIGNvbnRhaW5lciBydW50aW1lIGRvZXNuJ3Qgc3VwcG9ydCB0aGUgYGltYWdlLXJlZmVyZW5jZTp0YWdAZGlnZXN0YCBub3RhdGlvblxuIyBUaGlzIGlzIGN1cnJlbnRseSB0aGUgY2FzZSBmb3IgYGNyaS1vYCAoYW5kIG1vc3QgbGlrZWx5IG90aGVycylcbmtvIHJlc29sdmUgLS1wbGF0Zm9ybT1saW51eC9hbWQ2NCxsaW51eC9hcm02NCxsaW51eC9wcGM2NGxlLGxpbnV4L3MzOTB4IC0tcHJlc2VydmUtaW1wb3J0LXBhdGhzIC10IHYwLjE2LjAgLWYgJHtQUk9KRUNUX1JPT1R9L2NvbmZpZy8gXHUwMDNlICRPVVRQVVRfUkVMRUFTRV9ESVIvcmVsZWFzZS5ub3RhZ3MueWFtbFxuIiwiYXJndW1lbnRzIjpudWxsLCJlbnZpcm9ubWVudCI6eyJjb250YWluZXIiOiJydW4ta28iLCJpbWFnZSI6Imdjci5pby90ZWt0b24tcmVsZWFzZXMvZG9nZm9vZGluZy9rb0BzaGEyNTY6MTE4MjIyZDYwMzQxOTI3M2RlZTAzNDM0OWQ4YTA0OTI4ODI2MDFjZTY4MWQ5YjUzMDkxMTdiZTQyYjNmNTRkMSJ9LCJhbm5vdGF0aW9ucyI6bnVsbH0seyJlbnRyeVBvaW50Ijoic2V0IC1leFxuXG5JTUFHRVNfUEFUSD0ke0NPTlRBSU5FUl9SRUdJU1RSWX0vZ2l0aHViLmNvbS90ZWt0b25jZC9jaGFpbnNcblxuZm9yIGNtZCBpbiBjb250cm9sbGVyXG5kb1xuICBJTUFHRVM9XCIke0lNQUdFU30gJHtJTUFHRVNfUEFUSH0vY21kLyR7Y21kfTp2MC4xNi4wXCJcbmRvbmVcblxuIyBQYXJzZSB0aGUgYnVpbHQgaW1hZ2VzIGZyb20gdGhlIHJlbGVhc2UueWFtbCBnZW5lcmF0ZWQgYnkga29cbmtvcGFyc2UgXFxcbiAgLS1wYXRoICRPVVRQVVRfUkVMRUFTRV9ESVIvcmVsZWFzZS55YW1sIFxcXG4gIC0tYmFzZSAke0lNQUdFU19QQVRIfSAtLWltYWdlcyAke0lNQUdFU30gXHUwMDNlIC93b3Jrc3BhY2UvYnVpbHRfaW1hZ2VzXG4iLCJhcmd1bWVudHMiOm51bGwsImVudmlyb25tZW50Ijp7ImNvbnRhaW5lciI6ImtvcGFyc2UiLCJpbWFnZSI6Imdjci5pby90ZWt0b24tcmVsZWFzZXMvZG9nZm9vZGluZy9rb3BhcnNlQHNoYTI1Njo1OTQ1ZjcwOWY1NTMzMzQ3ZTJmYWMyZjdlNzU3YTJhY2RlMmNlMjU0MThhNzE5MzQ4OWJmNDkwMjdhYTA0OTdmIn0sImFubm90YXRpb25zIjpudWxsfSx7ImVudHJ5UG9pbnQiOiIjIS9idXN5Ym94L3NoXG5zZXQgLWV4XG5cbiMgU2V0dXAgZG9ja2VyLWF1dGhcbkRPQ0tFUl9DT05GSUc9fi8uZG9ja2VyXG5ta2RpciAtcCAke0RPQ0tFUl9DT05GSUd9XG5jcCAvd29ya3NwYWNlL2RvY2tlci1jb25maWcuanNvbiAke0RPQ0tFUl9DT05GSUd9L2NvbmZpZy5qc29uXG5cblJFR0lPTlM9XCJ1cyBldSBhc2lhXCJcblxuIyBUYWcgdGhlIGltYWdlcyBhbmQgcHV0IHRoZW0gaW4gYWxsIHRoZSByZWdpb25zXG5mb3IgSU1BR0UgaW4gJChjYXQgL3dvcmtzcGFjZS9idWlsdF9pbWFnZXMpXG5kb1xuICBJTUFHRV9XSVRIT1VUX1NIQT0ke0lNQUdFJSVAKn1cbiAgSU1BR0VfV0lUSE9VVF9TSEFfQU5EX1RBRz0ke0lNQUdFX1dJVEhPVVRfU0hBJSU6Kn1cbiAgSU1BR0VfV0lUSF9TSEE9JHtJTUFHRV9XSVRIT1VUX1NIQV9BTkRfVEFHfUAke0lNQUdFIyMqQH1cblxuICBlY2hvICRJTUFHRV9XSVRIX1NIQSwgXHUwMDNlXHUwMDNlIC90ZWt0b24vcmVzdWx0cy9JTUFHRVNcblxuICBpZiBbWyBcInRydWVcIiA9PSBcInRydWVcIiBdXVxuICB0aGVuXG4gICAgY3JhbmUgY3AgJHtJTUFHRV9XSVRIX1NIQX0gJHtJTUFHRV9XSVRIT1VUX1NIQV9BTkRfVEFHfTpsYXRlc3RcbiAgZmlcblxuICBmb3IgUkVHSU9OIGluICR7UkVHSU9OU31cbiAgZG9cbiAgICBpZiBbWyBcInRydWVcIiA9PSBcInRydWVcIiBdXVxuICAgIHRoZW5cbiAgICAgIGZvciBUQUcgaW4gXCJsYXRlc3RcIiB2MC4xNi4wXG4gICAgICBkb1xuICAgICAgICBjcmFuZSBjcCAke0lNQUdFX1dJVEhfU0hBfSAke1JFR0lPTn0uJHtJTUFHRV9XSVRIT1VUX1NIQV9BTkRfVEFHfTokVEFHXG4gICAgICBkb25lXG4gICAgZWxzZVxuICAgICAgVEFHPVwidjAuMTYuMFwiXG4gICAgICBjcmFuZSBjcCAke0lNQUdFX1dJVEhfU0hBfSAke1JFR0lPTn0uJHtJTUFHRV9XSVRIT1VUX1NIQV9BTkRfVEFHfTokVEFHXG4gICAgZmlcbiAgICBlY2hvICR7UkVHSU9OfS4kSU1BR0VfV0lUSF9TSEEsIFx1MDAzZVx1MDAzZSAvdGVrdG9uL3Jlc3VsdHMvSU1BR0VTXG4gIGRvbmVcbmRvbmVcbiIsImFyZ3VtZW50cyI6bnVsbCwiZW52aXJvbm1lbnQiOnsiY29udGFpbmVyIjoidGFnLWltYWdlcyIsImltYWdlIjoiZ2NyLmlvL2dvLWNvbnRhaW5lcnJlZ2lzdHJ5L2NyYW5lQHNoYTI1NjoxNjVmMjMzMWQ5MDkwMWNkMTYxYmI1YTBiNWMzYmQzNGI4NDRhNTFhZjFiNWNmYmU2ZWQzNWQ1NWY1ZDgwMWRlIn0sImFubm90YXRpb25zIjpudWxsfV19LCJtZXRhZGF0YSI6eyJidWlsZFN0YXJ0ZWRPbiI6IjIwMjMtMDUtMDVUMTY6MjI6NDZaIiwiYnVpbGRGaW5pc2hlZE9uIjoiMjAyMy0wNS0wNVQxNjo0MTo1NFoiLCJjb21wbGV0ZW5lc3MiOnsicGFyYW1ldGVycyI6ZmFsc2UsImVudmlyb25tZW50IjpmYWxzZSwibWF0ZXJpYWxzIjpmYWxzZX0sInJlcHJvZHVjaWJsZSI6ZmFsc2V9LCJtYXRlcmlhbHMiOlt7InVyaSI6ImdpdCtodHRwczovL2dpdGh1Yi5jb20vdGVrdG9uY2QvY2hhaW5zLmdpdCIsImRpZ2VzdCI6eyJzaGExIjoiNWNhNDI2NGQzNDk2OWJhMzdjYjVhZDA3OTlkYTJmZmQwNzdmMzczNSJ9fV19fQ==","signatures":[{"keyid":"SHA256:hBaIlFGTWVTPgYandvyV4ISYKM27E4IOXckaDbLDTgw","sig":"MEUCIDb0i3TMACxYL+DrxukluY1I+wkmWwYIDZKIMSTCB4FBAiEAmQbtbYX3JdMJenDorLhb7QN3nTlyMDOe1W+FYLZPmZ4="}]}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
