### ISSUE TITLE
Set read-only = true on VolumeMounts that are connected to hostPath volumes with a certain path

### ISSUE THREAD

**Issue by maartenvdezz** [kyverno/policies#67]
We want to create a Kyverno policy that whitelists certain hostPath volume paths.

Therefore, we use: 
```
    validate:
      pattern:
         =(spec):
            =(volumes):
              - (hostPath):
                =(path): "/test/path"
```

But, we also want to validate with this policy that all VolumeMounts that are mounted to the volumes with the _/test/path_ path to be read-only. Is this possible in Kyverno?

Based on the documentation, it looks like this is not possible with the logic that is supported.

**Comment by chipzoller** [comment]
@maartenvdezz Sorry it has taken so long to respond here. I don't believe a hostPath volume can be mounted as read only in Kubernetes. Do you know differently?

**Comment by maartenvdezz** [comment]
Yes, in the volumeMount (so not in the volume) you can set the volume to readonly like this:

`apiVersion: v1
kind: Pod
metadata:
  name: voltest
spec:
  containers:
  - name: test
    image: test
    volumeMounts:
    - mountPath: /tmp-mount
      name: tmp-vol
      readOnly: true
  volumes:
  - name: tmp-vol
    hostPath:
      path: /tmp`

This is important because "Writeable hostPath directory volumes allow containers to write to the filesystem in ways that let them traverse the host filesystem outside the pathPrefix" 

But, I don't think it's possible with Kyverno. You will need to just set all volumemounts in general to readonly or block all hostpath volumes.

**Comment by chipzoller** [comment]
This may be possible. What is the behavior you would want from a policy? Can you describe exactly what you're looking to do?

**Comment by maartenvdezz** [comment]
The policy must set all volumeMounts to readonly that point to a hostPath with a certain path.

So in other words: if a volumeMount is linked to the volume tmp-vol which is a hostPath volume and it has path /xy/z, than that volumeMount must be set to readonly

**Comment by chipzoller** [comment]
Let me give it a try and see what I can do. My thought is this would be possible with some JMESPath expressions, but how to craft them I'm not quite sure.

**Comment by chipzoller** [comment]
I have identified a code problem that is preventing this policy from being implemented. See https://github.com/kyverno/kyverno/issues/2109

**Comment by chipzoller** [comment]
Ok @maartenvdezz it looks like this problem was already addressed upstream and the fix can be found in image tag `v1.4.1-52-g521ee0e6`. It'll be included as part of the 1.4.2 release here shortly. But with that fixed version, I was able to build a policy for you.

`cpol.yaml`

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-certain-hostpath-vols-readonly
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Set certain hostPath volumes to read-only
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: >-
      Assumes only a single hostPath volume per Pod with the designated directory. Adds `readOnly: true` to container volumeMounts which
      have this hostPath mounted. Note that this policy is only for a Pod and not higher-level controllers like Deployments, Jobs, etc.
spec:
  background: false
  validationFailureAction: enforce
  rules:
  - name: set-readonly
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.object.spec.volumes[].hostPath.path | to_string(@) | contains(@, '/dir1/dir2')}}"
        operator: Equals
        value: true
      - key: "{{request.operation}}"
        operator: Equals
        value: CREATE
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - (name): "{{request.object.spec.containers[?volumeMounts.name=={{request.object.spec.volumes[?hostPath.path=='/dir1/dir2'].name | [0]}}].name | [0]}}"
            volumeMounts:
            - (name): "{{request.object.spec.containers[?volumeMounts.name=={{request.object.spec.volumes[?hostPath.path=='/dir1/dir2'].name | [0]}}].volumeMounts[0].name | [0]}}"
              mountPath: "{{request.object.spec.containers[?volumeMounts.name=={{request.object.spec.volumes[?hostPath.path=='/dir1/dir2'].name | [0]}}].volumeMounts[0].mountPath | [0]}}"
              readOnly: true
  - name: limit-hostpath-volumes-from-specific-dirs
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{request.object.spec.volumes[].hostPath.path | to_string(@) | contains(@, '/dir1/dir2')}}"
        operator: Equals
        value: true
      - key: "{{request.operation}}"
        operator: Equals
        value: CREATE
    validate:
      message: Pods may only define a single hostPath volume at this location.
      deny:
        conditions:
        - key: "{{request.object.spec.volumes[?hostPath.path=='/dir1/dir2'] | length(@)}}"
          operator: GreaterThan
          value: 1
```

Test with `pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: jimmy
    image: asdfssfafafsdfs:latest
    volumeMounts:
    - name: boo
      mountPath: /data/redis
    - name: bar
      mountPath: /opt/junk
  - name: busybox
    image: jdkall2ls:1.28
  volumes:
  - name: boo
    hostPath:
      path: /dir1/dir2
  - name: bar
    hostPath:
      path: /foo/bar
```

This ClusterPolicy has two rules: one validates that a Pod does not contain more than a single definition to mount a hostPath volume at path `/dir1/dir2`. The second rule (on top) actually does the mutation. Yes, it looks convoluted, but it does work as you can see from the output below given the input Pod definition above.

```sh
$ k get po redis -o yaml | k neat | bat -l yaml -Pp
apiVersion: v1
kind: Pod
metadata:
  annotations:
    policies.kyverno.io/patches: |
      set-readonly.set-certain-hostpath-vols-readonly.kyverno.io: added /spec/containers/0/volumeMounts/0/readOnly
  name: redis
  namespace: default
spec:
  containers:
  - image: asdfssfafafsdfs:latest
    name: jimmy
    volumeMounts:
    - mountPath: /data/redis
      name: boo
      readOnly: true
    - mountPath: /opt/junk
      name: bar
  - image: jdkall2ls:1.28
    name: busybox
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: default
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /dir1/dir2
    name: boo
  - hostPath:
      path: /foo/bar
    name: bar
```

Although this is somewhat of a specific use case, it may still be good to include this policy among our [samples](https://kyverno.io/policies/).

Let me know of your feedback, please.
