### ISSUE TITLE
Support for apiCall with mutation rule in kyverno tests

### ISSUE THREAD

**Issue by Anisha-Kunjumman** [kyverno/policies#685]
### Problem Statement

I want to make a unit test for a policy that does an apiCall and mutates the gid and uid value based on existing namespace annotation. But since I am doing an API call I am getting the below error:

error while applying mutate policy check-group-id-uid -> resource default/Pod/test-pod
error: failed to mutate elements: variable substitution failed: failed to resolve allowedGID at path /patchStrategicMerge/spec/containers/0/securityContext/runAsGroup: JMESPath query failed: Unknown key "allowedGID" in pathI0713 15:50:22.494538   69866 rule.go:233] autogen "msg"="processing rule" "rulename"="mutate-group-id-uid"

Below is the ClusterPolicy:
              
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-group-id-uid
  annotations:
    policies.kyverno.io/title: Check Group ID and UID
    policies.kyverno.io/description: >-
      Ensures that the group ID and UID in the pod's security context match the namespace annotation range. If they don't match, the policy updates the values to the first allowed UID and GID in the allowed list.
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
spec:
  background: false
  schemaValidation: false
  rules:
  - name: mutate-group-id-uid
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      any:
      - resources:
          namespaces:
          - "core-*"
          - "kube-*"
    context:
    - name: allowedUID
      apiCall:
        urlPath: /api/v1/namespaces/{{ request.namespace }}
        jmesPath: abs(metadata.annotations."openshift.io/sa.scc.uid-range" | split(@, '/') | [0].to_number(@))
    - name: allowedGID
      apiCall:
        urlPath: /api/v1/namespaces/{{ request.namespace }}
        jmesPath: abs(metadata.annotations."openshift.io/sa.scc.supplemental-groups" | split(@, '/') | [0].to_number(@))
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              securityContext:
                runAsUser: "{{ allowedUID }}"
                runAsGroup: "{{ allowedGID }}"
```

### Solution Description

 I tested the policy in a test cluster and it does mutate the value. Seems like I am having trouble with Kyverno test failing due to a mutating policy that is fetching values using an API call. Kyverno doesn't mock or simulate these API calls. Is doing this kind of test  actually possible?  please, let me know.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
