### ISSUE TITLE
[BUG] The disallow-adding-capabilities incorrectly specifies null instead of "null"

### ISSUE THREAD

**Issue by FernFerret** [kyverno/policies#69]
The `disallow-adding-capabilities` policy uses `null` instead of `"null"`. Because of this, it doesn't actually enforce disallowing adding capabilities and instead I was able to add `NET_ADMIN` like so:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-caps
spec:
  selector:
    matchLabels:
      app: add-caps
  template:
    metadata:
      labels:
        app: add-caps
    spec:
      containers:
      - name: add-caps
        image: redis
        securityContext:
          capabilities:
            add:
              - "NET_ADMIN"
```

Once I fixed the policy to `"null"` the property was correctly enforced.

When set to `null` and applied, you can note that the rendered pattern spec is:

```yaml
spec:
  rules:
  - name: capabilities
    validate:
      ...
      pattern:
        spec:
          =(initContainers):
          - =(securityContext):
              =(capabilities): {}
          containers:
          - =(securityContext):
              =(capabilities): {}
```
