### ISSUE TITLE
[Bug] annotate-base-images policy with non existing image

### ISSUE THREAD

**Issue by jw-s** [kyverno/policies#701]
### Kyverno Version

1.9.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

Other (specify in description)

### Description

*Vanilla k8s running on AWS EC2*

When creating a pod (with valid pod resource schema) with a container referencing a non existing image, the admission request fails.

### Steps to reproduce

1. Create [policy](https://github.com/kyverno/policies/blob/main/other/annotate-base-images/annotate-base-images.yaml)
2. Create pod which references no existing image (doesn't exist in dockerhub for example)
```
apiVersion: v1
kind: Pod
metadata:
  name: test-kyverno-deploy
  namespace: default
spec:
  containers:
  - image: postgres:20.50 
    imagePullPolicy: IfNotPresent
    name: test-kyverno-pod
    resources:
      limits:
        cpu: "1"
        memory: 300Mi
      requests:
        cpu: 500m
        memory: 256Mi
```

### Expected behavior

Pod should be created although not running due to `ImagePullBackOff` status

I assume its to do with the error handling on the execution flow for `imageRegistry`.

### Kyverno logs

```shell
Error from server: error when creating "STDIN": admission webhook "mutate.kyverno.svc-fail" denied the request: mutation policy annotate-base-images error: failed to apply policy annotate-base-images rules [mutate-base-image]

E0727 08:33:58.530396       1 handlers.go:173] webhooks/resource/mutate "msg"="mutation failed" "error"="mutation policy annotate-base-images error: failed to apply policy annotate-base-images rules [mutate-base-image]" "gvk"={"group":"","version":"v1","kind":"Pod"} "kind"="Pod" "name"="test-kyverno-deploy" "namespace"="default" "operation"="CREATE" "uid"="XXXX" "user"={"username":"XXXXXX","groups":["system:masters","system:authenticated"]}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
