### ISSUE TITLE
[Bug] - Unique Ingress Host  policy is not allowing to update the spec of a deployed ingress. 

### ISSUE THREAD

**Issue by nischay30** [kyverno/policies#702]
### Kyverno Version

1.6.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

EKS

### Description

[Unique Ingress Host](https://kyverno.io/policies/other/restrict-ingress-host/restrict-ingress-host/)  policy is not allowing to update the spec of a deployed ingress. 

### Steps to reproduce

1. We have deployed this policy [Unique Ingress Host](https://kyverno.io/policies/other/restrict-ingress-host/restrict-ingress-host/) and used only the first rule `check-single-host` in out EKS cluster in `Enforce` mode. 
2. Then deploy the below Ingress object.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
spec:
  rules:
  - host: test.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 9117
        path: /
        pathType: ImplementationSpecific
```
3. Once deployed, then add an additional backend path in the existing object, the final k8s yaml looks like below
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
spec:
  rules:
  - host: test.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 9117
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: test1
            port:
              number: 9118
        path: /test
        pathType: ImplementationSpecific
```
4. When we try to deploy, we are blocked by the kyverno policy and below is the error.
```
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{},\"name\":\"test1\",\"namespace\":\"monitoring\"},\"spec\":{\"rules\":[{\"host\":\"test.com\",\"http\":{\"paths\":[{\"backend\":{\"service\":{\"name\":\"test\",\"port\":{\"number\":9117}}},\"path\":\"/\",\"pathType\":\"ImplementationSpecific\"},{\"backend\":{\"service\":{\"name\":\"test1\",\"port\":{\"number\":9118}}},\"path\":\"/test\",\"pathType\":\"ImplementationSpecific\"}]}}]}}\n"}},"spec":{"rules":[{"host":"test.com","http":{"paths":[{"backend":{"service":{"name":"test","port":{"number":9117}}},"path":"/","pathType":"ImplementationSpecific"},{"backend":{"service":{"name":"test1","port":{"number":9118}}},"path":"/test","pathType":"ImplementationSpecific"}]}}]}}
to:
Resource: "networking.k8s.io/v1, Resource=ingresses", GroupVersionKind: "networking.k8s.io/v1, Kind=Ingress"
Name: "test1", Namespace: "monitoring"
for: "black-box.yaml": admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Ingress/monitoring/test1 was blocked due to the following policies 

unique-ingress-host:
  unique-single-host: The Ingress host name must be unique.
```

As the error shows, once an Ingress is deployed, you cannot modify it at any stage. 

### Expected behavior

Modified Ingress should have been allowed by Kyverno in the EKS cluster. 

### Kyverno logs

```shell
I0727 09: 41: 36.897647       1 handlers.go: 139
] webhooks/resource/validate "msg"="admission request denied""clusterroles"=[
"cluster-admin",
"eks:podsecuritypolicy:privileged",
"eks:podsecuritypolicy:restricted",
"system:basic-user",
"system:discovery",
"system:public-info-viewer"
] "gvk"={
"group": "networking.k8s.io",
"version": "v1",
"kind": "Ingress"
} "gvr"={
"group": "networking.k8s.io",
"version": "v1",
"resource": "ingresses"
} "kind"="Ingress""name"="test1""namespace"="monitoring""operation"="UPDATE""resource.gvk"={
"Group": "networking.k8s.io",
"Version": "v1",
"Kind": "Ingress"
} "roles"=null "uid"="7116fdff-c89b-431b-9aa5-b9c0250e9a68""user"={
"username": "admin:{{XXXXXXXXX}}",
"uid": "XXXXXXXXX",
"groups": [
    "system:masters",
    "system:authenticated"
],
"extra": {
    "accessKeyId": [
        "XXXXXXXXX"
    ],
    "arn": [
        "XXXXXXXXX"
    ],
    "canonicalArn": [
        "XXXXXXXXX"
    ],
    "principalId": [
        "XXXXXXXXX"
    ],
    "sessionName": [
        "XXXXXXXXX"
    ]
}
}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
