### ISSUE TITLE
Require Limits and Requests

### ISSUE THREAD

**Issue by windowsrefund** [kyverno/policies#71]
I'd like to have a policy that checks for a match between resource requests and limits. Since there doesn't appear to be any kind of == operator, I tried making use of [variables](https://kyverno.io/docs/writing-policies/variables/) like so:

```
            containers:
              - resources:
                  requests:
                    memory: "?*"
                  limits:
                    memory: "$(./../../requests/memory)"
```

To my surprise though, my newly created pod (with non-matching memory requests/limits) passed validation. I suspect the variable is not interpolating what was set for requests.memory and is just using "?*". Am I thinking about this correctly? Is there another method I can use to evaluate?

**Comment by kacejot** [comment]
Hi, @windowsrefund.

Yes, your suspicion is correct. $() notation takes the part of policy by provided path and places it instead of itself.
So your policy is equivalent to:
```yaml
containers: 
- resources: 
    limits: 
      memory: "?*"
    requests: 
      memory: "?*"
```
Which allows all the policies with both `memory` fields specified.

I wrote a simple policy that denies not matching `memory` fields in `requests` and `limits`:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: all-containers-need-requests-and-limits
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: check-container-resources
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "resources.resquests.memory must be equal to resources.limits.memory"
      deny:
        conditions:
        - key: "{{ request.object.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}"
          operator: NotEquals
          value: 0
```

It uses JMESPath notation and traverses the containers list to check `memory` fields in each element. If it found any, the condition will fail.

**Comment by chipzoller** [comment]
Nice idea here, @kacejot ! I've taken it and expanded upon it to be applicable to all Pod controllers. I will get this added to the policy library so @windowsrefund and others can benefit.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: memory-requests-equal-limits
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: memory-requests-equal-limits-deployment
    match:
      resources:
        kinds:
        - Deployment
        - DaemonSet
        - StatefulSet
        - Job
    validate:
      message: "resources.requests.memory must be equal to resources.limits.memory"
      deny:
        conditions:
        - key: "{{ request.object.spec.template.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}"
          operator: NotEquals
          value: 0
  - name: memory-requests-equal-limits-pod
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "resources.requests.memory must be equal to resources.limits.memory"
      deny:
        conditions:
        - key: "{{ request.object.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}"
          operator: NotEquals
          value: 0
  - name: memory-requests-equal-limits-cronjob
    match:
      resources:
        kinds:
        - CronJob
    validate:
      message: "resources.requests.memory must be equal to resources.limits.memory"
      deny:
        conditions:
        - key: "{{ request.object.spec.jobTemplate.spec.template.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}"
          operator: NotEquals
          value: 0
```
