### ISSUE TITLE
[Bug] deny-exec-by-pod-name policy not working

### ISSUE THREAD

**Issue by nicolasbrieussel** [kyverno/policies#718]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

### Description

I aws trying to deny pod exec for some ClusterRole, without results. I ended up with trying the policy given [here](https://kyverno.io/policies/other/b-d/block-pod-exec-by-pod-name/block-pod-exec-by-pod-name/) with a little modification in the deny condition value 

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-exec-by-pod-name
  annotations:
    policies.kyverno.io/title: Block Pod Exec by Pod Name
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: deny-exec-redis
    match:
      any:
      - resources:
          kinds:
          - Pod/exec
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: Equals
        value: CONNECT
    validate:
      message: Exec'ing into Pods called "redis-*" is not allowed.
      deny:
        conditions:
          all:
          - key: "{{ request.name }}"
            operator: Equals
            value: redis-*
```

Just to be sure it was related to the policy itselft, and not something else, i tested another policy, which works perfectly fine 

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-non-admin-access
spec:
  background: false
  rules:
  - name: protect-critical-namespaces
    match:
      all:
      - clusterRoles:
        - dev
        resources:
          kinds:
          - "*"
          namespaces:
          - ns1
          - ns2
    validate:
      deny:
        conditions:
        - key: '{{request.operation}}'
          operator: AnyIn
          value:
          - DELETE
          - UPDATE
          - CREATE
          - CONNECT
      message: 'The operation {{request.operation}} in {{request.namespace}}
        is not allowed with one of your following ClusterRoles : {{request.clusterRoles}}. '
  validationFailureAction: Enforce
```

I tried the `deny-exec-by-pod-name` policy with system:masters and non system:masters users

I used helm to install Kyverno : `helm install kyverno kyverno/kyverno -f kyverno.yaml --version 3.0.4 -n kyverno`
I tested different values file content.

This one, since i use EKS and Cilium CNI
```yaml
admissionController:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
backgroundController:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
cleanupController:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
reportsController:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

config:
  webhooks:
    # Exclude objects from scope
    - objectSelector:
        matchExpressions:
          - key: webhooks.kyverno.io/exclude
            operator: 
```

And this one, just in case something above was wrong
```yaml
config:
  webhooks:
    # Exclude objects from scope
    - objectSelector:
        matchExpressions:
          - key: webhooks.kyverno.io/exclude
            operator: 
```

### Steps to reproduce

1. Apply policy https://kyverno.io/policies/other/b-d/block-pod-exec-by-pod-name/block-pod-exec-by-pod-name/
2. Try to exec into a protected pod.

### Expected behavior

`kubectl exec ...` denied, at least with the unprivileged user. 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
