### ISSUE TITLE
Restrict AppArmor breaks if annotations=null

### ISSUE THREAD

**Issue by jimethn** [kyverno/policies#721]
Problem: If the `annotations: null` instead of empty, this policy incorrectly fails validation.

Solution: Instead of

```
      validate:
        message: >-
          Specifying other AppArmor profiles is disallowed. The annotation
          `container.apparmor.security.beta.kubernetes.io` if defined
          must not be set to anything other than `runtime/default` or `localhost/*`.          
        pattern:
          =(metadata):
            =(annotations):
              =(container.apparmor.security.beta.kubernetes.io/*): "runtime/default | localhost/*"
```

do

```
      validate:
        message: >-
          Specifying other AppArmor profiles is disallowed. The annotation
          `container.apparmor.security.beta.kubernetes.io` if defined
          must not be set to anything other than `runtime/default` or `localhost/*`.          
        foreach:
        - list: "request.object.metadata.annotations"
          pattern:
            container.apparmor.security.beta.kubernetes.io/*: "runtime/default | localhost/*"
```

**Comment by chipzoller** [comment]
In what situation would `annotations` ever be defined but with a null map?

**Comment by jimethn** [comment]
@chipzoller the helm chart I'm rendering is doing it

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-operator
spec:
  template:
    metadata:
      annotations: null
      labels:
        name: cilium-operator
```
