### ISSUE TITLE
[Bug] apiVersion cannot be empty when applying add-Rolebinding policy

### ISSUE THREAD

**Issue by CaspervdKerk** [kyverno/policies#722]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

Minikube

### Description

When trying to apply the `add-rolebinding.yaml` policy via `kubectl apply -f add-rolebinding.yaml` I get the error
`Error from server: error when creating "add-rolebinding.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].generate.apiVersion.: apiVersion cannot be empty`.

Kyverno was installed in standalone mode with: `helm install kyverno kyverno/kyverno -n kyverno --create-namespace`

Yaml configuration of the policy (same as in the github repo):
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-rolebinding
  annotations:
    policies.kyverno.io/title: Add RoleBinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: RoleBinding
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Typically in multi-tenancy and other use cases, when a new Namespace is created,
      users and other principals must be given some permissions to create and interact
      with resources in the Namespace. Very commonly, Roles and RoleBindings are used to
      grant permissions at the Namespace level. This policy generates a RoleBinding
      called `<userName>-admin-binding` in the new Namespace which binds to the ClusterRole
      `admin` as long as a `cluster-admin` did not create the Namespace. Additionally, an annotation
      named `kyverno.io/user` is added to the RoleBinding recording the name of the user responsible
      for the Namespace's creation.
spec:
  background: false
  rules:
    - name: generate-admin-binding
      match:
        any:
        - resources:
            kinds:
              - Namespace
      exclude:
        any:
        - clusterRoles:
          - cluster-admin
      generate:
        synchronize: true
        kind: RoleBinding
        name: "{{request.userInfo.username}}-admin-binding"
        namespace: "{{request.object.metadata.name}}"
        data:
          metadata:
            annotations:
              kyverno.io/user: "{{request.userInfo.username}}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
            - kind: User
              name: "{{request.userInfo.username}}"
```

### Steps to reproduce

1. Install kyverno as standalone into minikube
2. Try to apply `add-rolebinding` policy with `kubectl apply -f add-rolebinding.yaml`

### Expected behavior

Add-roleBinding cluster policy get applied successfully 

### Kyverno logs

```shell
E0818 09:07:27.375898       1 handlers.go:38] webhooks/policy/validate "msg"="policy validation errors" "error"="path: spec.rules[0].generate.apiVersion.: apiVersion cannot be empty" "gvk"={"group":"kyverno.io","version":"v1","kind":"ClusterPolicy"} "gvr"={"group":"kyverno.io","version":"v1","resource":"clusterpolicies"} "name"="add-rolebinding" "namespace"="" "operation"="CREATE" "uid"="87f43cd7-5b8b-44d3-bea5-878d4843bf98" "user"={"username":"minikube-user","groups":["system:masters","system:authenticated"]}
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
