### ISSUE TITLE
[Bug] Helm versions related secrets.

### ISSUE THREAD

**Issue by mro-amboss** [kyverno/policies#739]
### Kyverno Version

1.10.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

EKS

### Description

Is it possible to set a policy, which would in general to prevent secrets form deleteion, but would let to delete the oldest secret.

Helm keeps its state and previous states in secrets. It keeps last 10 secrets (meaning last 10 releases).
So the helm secrets looks like:
```
kubectl get secret -n <namespace-name>
NAME                                                  TYPE                             DATA   AGE
sh.helm.release.v1.release-name.v10   helm.sh/release.v1               1      26m
sh.helm.release.v1.release-name.v11   helm.sh/release.v1               1      8m14s
sh.helm.release.v1.release-name.v12   helm.sh/release.v1               1      8s
sh.helm.release.v1.release-name.v3    helm.sh/release.v1               1      2d18h
sh.helm.release.v1.release-name.v4    helm.sh/release.v1               1      2d18h
sh.helm.release.v1.release-name.v5    helm.sh/release.v1               1      2d18h
sh.helm.release.v1.release-name.v6    helm.sh/release.v1               1      2d16h
sh.helm.release.v1.release-name.v7    helm.sh/release.v1               1      29m
sh.helm.release.v1.release-name.v8    helm.sh/release.v1               1      28m
sh.helm.release.v1.release-name.v9    helm.sh/release.v1               1      28m

```
It is possible to set policy preventing secrets from deletion, and excluding helm secrets from this policy.
The policy may looks as follows:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-deletes
  annotations:
    policies.kyverno.io/title: Block Deletes
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: >-
      Blocks deletion
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: block-deletes
    match:
      all:
      - resources:
          kinds:
          - Secret
          operations:
          - DELETE
          namespaces:
          - "dev*"
          - "test*"
    exclude:
      any:
      - resources:
          kinds:
          - Service
          - Deployment
          - Pod
          - Secret
          namespaces:
          - "pr-*"
      - resources:
          names:
          - "sh.helm.release*"
          kinds:
          - Secret
    validate:
      message: "This resource is protected and changes are not allowed. Please contact  channel #XXXXXXXX on Slack."
      deny:
        conditions:
          any:
            - key: "{{request.operation || 'BACKGROUND'}}"
              operator: AnyIn
              value:
              - DELETE
```

This will let to execute helm upgrade of the release, however in general this let's to delete all helm secrets.
When helm upgrade is performed it wants to delete the oldest secret to have stored 10 oldest versions?
In my example helm during the upgrade wants to delete following secret:
```
sh.helm.release.v1.release-name.v3    helm.sh/release.v1               1      2d18h
```

Is it possible to set a policy to let delete the oldest helm secret?

### Steps to reproduce

1. Set policy as above.
2. St policy as above.

### Expected behavior

to have policy as described above.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
