### ISSUE TITLE
[Bug] Kyverno Block Stale images not working, its wrongly calculating the image age

### ISSUE THREAD

**Issue by macbash** [kyverno/policies#740]
### Kyverno Version

1.10.3

### Description

re:f: https://kyverno.io/policies/other/b-d/block-stale-images/block-stale-images/
we have setup a kyverno version: 1.10.3 & 1.7.5, in both we are facing the block-stale-images isn't working as expected. its wrong calculating, we are using AWS ECR for image registry.

Bug:
I0911 11:58:48.789958       1 evaluate.go:24] EngineValidate "msg"="a condition failed in 'all' block" "kind"="Deployment" "name"="xyz" "namespace"="xyz" "policy"="block-stale-images" "rule"="autogen-block-stale-images" "condition"=**{"key":"94h35m32.961287512s","operator":"GreaterThan","value":"4380h"}**
I0911 11:58:48.973298       1 validate_audit.go:200] ValidateAuditHandler "**msg"="validation failed"** "action"="validate" "gvk"="apps/v1, Kind=Deployment" "operation"="UPDATE" "resource"="xyz/Deployment/xyz" "failed rules"=["autogen-block-stale-images"] "policy"="block-stale-images"

Please let me know how to move forward.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Transferred to kyverno/policies.

```
{"key":"94h35m32.961287512s","operator":"GreaterThan","value":"4380h"}
```

94 hours is, in fact, NOT greater than 4,380 hours. What about this is wrong?

**Comment by macbash** [comment]
thanks @chipzoller for your reply, thats where the confusion begins, its correct if you see the next line, the validation failed. would you pl help this ?

**Comment by chipzoller** [comment]
The log is just saying the condition evaluated to a false result. For a deny to occur, the condition must evaluate to a true.

**Comment by macbash** [comment]
we have used the same ref: https://kyverno.io/policies/other/b-d/block-stale-images/block-stale-images/ do we need to change anything from the policy side, pl share your recommendations. thanks.

**Comment by chipzoller** [comment]
Does it work or not work? What's the problem here?

**Comment by macbash** [comment]
itsnt working, its giving false validation. for the image which was build a week or 3-4 days it showing failed as stale block image

**Comment by chipzoller** [comment]
Please show how you're testing this and the exact result.

**Comment by macbash** [comment]
@chipzoller - pl find the below log
I0911 11:58:48.973298 1 validate_audit.go:200] **ValidateAuditHandler "msg"="validation failed"** "action"="validate" "gvk"="apps/v1, Kind=Deployment" "operation"="UPDATE" **_"resource"="xyz/Deployment/xyz" "failed rules"=["autogen-block-stale-images"] "policy"="block-stale-images"_**

**Comment by chipzoller** [comment]
Forget the log. Does the policy work or not?

**Comment by macbash** [comment]
@chipzoller  - Again. Policy not working as expected, its giving false values. we are also using kyverno-policy reporter UI. Pl see the below for one of the deployments.

![image](https://github.com/kyverno/policies/assets/14119469/c531c00e-25bc-4e55-88b4-2e47be17d026)

**Comment by macbash** [comment]
@chipzoller  - its same behavior in both 1.10.3 & 1.7.5 versions. Could you pl share how the image age is calculated by kyverno,  we are using AWS ECR. I need to figure why/how kyverno is wrong calculating, is there a way we can deep dive and see ? this policy is giving false positive for latest images which was deployed 3-4 days before.

**Comment by chipzoller** [comment]
I think maybe you might not understand how this policy works. This policy checks the created date of the image and NOT when it was deployed in a Pod. If an image was built more than 6 months ago, it will fail this policy.

You can check with the `crane` tool (install with homebrew using `brew install crane`) on the `created` field.

```sh
crane config ghcr.io/chipzoller/zulu:v0.0.14 | jq .created
"2022-10-06T02:15:30Z"
```

**Comment by chipzoller** [comment]
Please use code blocks and not screenshots for text and terminal output. We can't search it. No need to keep mentioning me, I see your responses.

Do you get a failed result for a fresh deployment of a new Pod?

**Comment by macbash** [comment]
sure, It failed for fresh and recently deployed ones also.

**Comment by chipzoller** [comment]
Please show the full policy you have (sanitize if you need) as well as the Policy Report where it's showing the failure. I know you're using Policy Reporter but I want to see the Policy Report YAML manifest itself.

**Comment by nmarchini** [comment]
> Thanks @chipzoller for sharing the details, but pl check the created date. ![image](https://user-images.githubusercontent.com/14119469/267056275-87067cca-42ac-4583-b51d-71e9c91ea6d3.png)

Here is the code output of the command

`crane config XXXXXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/XXXXX:v0.66.0 | jq .created
"2023-08-23T09:39:48.342672082Z"`

Here is the YAML policy.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.23"
    kyverno.io/kyverno-version: 1.10.3
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,Job,StatefulSet,CronJob
    policies.kyverno.io/category: Other
    policies.kyverno.io/description: 'Images that are old usually have some open security
      vulnerabilities which are not patched. This policy checks the contents of every
      container image and inspects them for the create time. If it finds any image
      which was built more than 6 months ago this policy blocks the deployment.      '
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/title: Block Stale Images
  creationTimestamp: "2023-03-23T13:20:17Z"
  generation: 306326
  labels:
    kustomize.toolkit.fluxcd.io/name: kyverno-policies-kustomize
    kustomize.toolkit.fluxcd.io/namespace: kyverno
  name: block-stale-images
  resourceVersion: "921818965"
  uid: XXXXX
spec:
  background: true
  failurePolicy: Fail
  rules:
  - exclude:
      resources: {}
    generate:
      clone: {}
    match:
      any:
      - resources:
          kinds:
          - Pod
      resources: {}
    mutate: {}
    name: block-stale-images
    validate:
      foreach:
      - context:
        - imageRegistry:
            reference: '{{ element.image }}'
          name: imageData
        deny:
          conditions:
            all:
            - key: '{{ time_since('''', ''{{ imageData.configData.created }}'', '''')
                }}'
              operator: GreaterThan
              value: 4380h
        list: request.object.spec.containers
      message: Images built more than 6 months ago are prohibited.
  - exclude:
      resources: {}
    generate:
      clone: {}
    match:
      any:
      - resources:
          kinds:
          - DaemonSet
          - Deployment
          - Job
          - StatefulSet
      resources: {}
    mutate: {}
    name: autogen-block-stale-images
    validate:
      foreach:
      - context:
        - imageRegistry:
            reference: '{{ element.image }}'
          name: imageData
        deny:
          conditions:
            all:
            - key: '{{ time_since('''', ''{{ imageData.configData.created }}'', '''')
                }}'
              operator: GreaterThan
              value: 4380h
        list: request.object.spec.template.spec.containers
      message: Images built more than 6 months ago are prohibited.
  - exclude:
      resources: {}
    generate:
      clone: {}
    match:
      any:
      - resources:
          kinds:
          - CronJob
      resources: {}
    mutate: {}
    name: autogen-cronjob-block-stale-images
    validate:
      foreach:
      - context:
        - imageRegistry:
            reference: '{{ element.image }}'
          name: imageData
        deny:
          conditions:
            all:
            - key: '{{ time_since('''', ''{{ imageData.configData.created }}'', '''')
                }}'
              operator: GreaterThan
              value: 4380h
        list: request.object.spec.jobTemplate.spec.template.spec.containers
      message: Images built more than 6 months ago are prohibited.
  validationFailureAction: audit

```


Here is the policy report 
```
kubectl get polr cpol-block-stale-images -n XXXX -o jsonpath='{.results[?(@.result=="fail")]}' | yq -p json -
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: apps/v1
    kind: Deployment
    name: myDeployment
    namespace: xxxx
    uid: xxx
result: fail
rule: autogen-block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694463715e+09
---
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: apps/v1
    kind: Deployment
    name: mydeployment
    namespace: xxxx
    uid: XXXX
result: fail
rule: autogen-block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694463042e+09
---
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: v1
    kind: Pod
    name: mypod
    namespace: XXXX
    uid: XXXX
result: fail
rule: block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694463638e+09
---
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: v1
    kind: Pod
    name: mypod
    namespace: XXXX
    uid: XXXX
result: fail
rule: block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694463066e+09
---
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: v1
    kind: Pod
    name: mypod
    namespace: XXXX
    uid: XXXX
result: fail
rule: block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694463633e+09
---
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: v1
    kind: Pod
    name: mypod
    namespace: XXXX
    uid: XXXX
result: fail
rule: block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694463063e+09
```

Please let us know if you need anything more. thanks

**Comment by chipzoller** [comment]
What I'm curious to know is can you reproduce this with a fresh Deployment using this image, right now, by creating a net new one? Take this image, leave your policy alone, and use it to create a new Deployment called `foo`. Does `foo` show up as failed in the same Policy Report even though the image, as reported by `crane`, is less than 4,380 hours old?

**Comment by nmarchini** [comment]
Looks like the container passes the policy validation when used in a different deployment. I tested in the default namespace and it worked/passed

I deleted the deployments that have the issue and let Flux create them again, the policy is still failing for these after they have been recreated

Evidence below of the test

```
kubectl get deployment foo-kyverno -n default
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
foo-kyverno   0/1     1            0           22m 
```

```
kubectl describe deployment foo-kyverno -n default
Name:                   foo-kyverno
Namespace:              default
CreationTimestamp:      Mon, 11 Sep 2023 22:01:37 +0100
Labels:                 app=foo-kyverno
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=foo-kyverno
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=foo-kyverno
  Containers:
   foo-kyverno:
    Image:        xxxx.dkr.ecr.eu-west-2.amazonaws.com/xxxx:xxxx
    Port:         8080/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   foo-kyverno-7585564466 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  23m   deployment-controller  Scaled up replica set foo-kyverno-7585564466 to 1
```

The kyverno policy passes without failing, the failure below is on the echo-deployment, the foo-kyverno passes


```
kubectl get polr cpol-block-stale-images -n default -o jsonpath='{.results[?(@.result=="fail")]}' | yq -p json -
category: Other
message: 'validation failure: Images built more than 6 months ago are prohibited.'
policy: block-stale-images
resources:
  - apiVersion: apps/v1
    kind: Deployment
    name: echo-deployment
    namespace: default
    uid: 26756c09-0d14-401b-8a70-7c720641c8f0
result: fail
rule: autogen-block-stale-images
scored: true
severity: medium
source: kyverno
timestamp:
  nanos: 0
  seconds: 1.694466132e+09 
```
