### ISSUE TITLE
Advanced Restrict Image Registries

### ISSUE THREAD

**Issue by PankajGrg** [kyverno/policies#770]
I have modified the policy to scan for namespace and policy looks like this:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-registries
  annotations:
    policies.kyverno.io/title: Advanced Restrict Image Registries
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      In instances where a ClusterPolicy defines all the approved image registries
      is insufficient, more granular control may be needed to set permitted registries,
      especially in multi-tenant use cases where some registries may be based on
      the Namespace. This policy shows an advanced version of the Restrict Image Registries
      policy which gets a global approved registry from a ConfigMap and, based upon an
      annotation at the Namespace level, gets the registry approved for that Namespace.      
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: validate-corp-registries
      match:
        any:
        - resources:
            kinds:
            - Pod
      context:
        - name: clusterregistries
          configMap:
            name: allowed-registries-kyverno
            namespace: services
      preconditions:
        any:
        - key: "{{request.operation || 'BACKGROUND'}}"
          operator: AnyIn
          value:
          - CREATE
          - UPDATE
      validate:
        message: This Pod names an image that is not from an approved registry.
        foreach:
        - list: "request.object.spec.[initContainers, ephemeralContainers, containers][]"
          deny:
            conditions:
              all:
                - key: "{{element.image}}"
                  operator: NotEquals
                  value: "{{clusterregistries.data.registries}}"

```
Here is the configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: allowed-registries-kyverno
  namespace: services
data:
  registries: '["ghcr.io/*", "quay.io/*", "602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/*", "k8s.gcr.io/*", "registry.k8s.io/*", "public.ecr.aws/*", "nvcr.io/*"]'
```
Reference : https://release-1-9-0.kyverno.io/policies/other/advanced_restrict_image_registries/advanced-restrict-image-registries/

I have applied the policy and configmap. The version of kyverno is 1.9.0 which is compitable with current k8s version. 

This policy block all the image pulls and unable to whitelist the once in the configmap. What am i missing here?
