### ISSUE TITLE
[Bug] restrict-binding-system-groups example is incorrect

### ISSUE THREAD

**Issue by RanganMahesh** [kyverno/policies#777]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

### Description

The code [here](https://github.com/kyverno/policies/blob/main/other/res/restrict-binding-system-groups/restrict-binding-system-groups.yaml) shows how to restrict Binding System Groups which refer to system groups such as system:anonymous, system:unauthenticated, and system:masters. 

The example however has a pattern match on **roleRef** which is incorrect, the system groups are used in **subject** section and do not come under the **roleRef** section.

I can see a bug on this issue [here](https://github.com/kyverno/policies/issues/411) which was resolved previously to fix an issue where this policy was not working on roles, but that is an incorrect implementation of this policy as the pattern is different when applied to a role/SA and while using system group as a target, the example in this page specifically refers to the system groups and it should have code sample that works for the particular use case.

### Steps to reproduce

1. Create a ClusterRole / Role: (creating a ClusterRole here)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
```

2. Create a ClusterRoleBinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters
```
3. Create the 'restrict-binding-system-groups' policy as given in the [documentation](https://kyverno.io/policies/other/res/restrict-binding-system-groups/restrict-binding-system-groups/):
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-binding-system-groups
  annotations:
    policies.kyverno.io/title: Restrict Binding System Groups
    policies.kyverno.io/category: Security, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: RoleBinding, ClusterRoleBinding, RBAC
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Certain system groups exist in Kubernetes which grant permissions that
      are used for certain system-level functions yet typically never appropriate
      for other users. This policy prevents creating bindings to some of these
      groups including system:anonymous, system:unauthenticated, and system:masters.      
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: restrict-anonymous
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      validate:
        message: "Binding to system:anonymous is not allowed."
        pattern:
          roleRef:
            name: "!system:anonymous"
    - name: restrict-unauthenticated
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      validate:
        message: "Binding to system:unauthenticated is not allowed."
        pattern:
          roleRef:
            name: "!system:unauthenticated"
    - name: restrict-masters
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      validate:
        message: "Binding to system:masters is not allowed."
        pattern:
          roleRef:
            name: "!system:masters"
```

> Note: This will not work because the pattern match checks for the **roleRef** and not **subjects**

### Expected behavior

The expected behavior would be that the pattern match checks for the system groups and restricts them:
Updating the policy with **subjects** instead of **roleRef** so that it works:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-binding-system-groups
  annotations:
    policies.kyverno.io/title: Restrict Binding System Groups
    policies.kyverno.io/category: Security, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: RoleBinding, ClusterRoleBinding, RBAC
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Certain system groups exist in Kubernetes which grant permissions that
      are used for certain system-level functions yet typically never appropriate
      for other users. This policy prevents creating bindings to some of these
      groups including system:anonymous, system:unauthenticated, and system:masters.      
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: restrict-anonymous
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      validate:
        message: "Binding to system:anonymous is not allowed."
        pattern:
          subjects:
            name: "!system:anonymous"
    - name: restrict-unauthenticated
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      validate:
        message: "Binding to system:unauthenticated is not allowed."
        pattern:
          subjects:
            name: "!system:unauthenticated"
    - name: restrict-masters
      match:
        any:
        - resources:
            kinds:
              - RoleBinding
              - ClusterRoleBinding
      validate:
        message: "Binding to system:masters is not allowed."
        pattern:
          subjects:
            name: "!system:masters"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
