### ISSUE TITLE
[Bug] Restrict image registries is not working for AWS ECR

### ISSUE THREAD

**Issue by ruko2023** [kyverno/policies#780]
### Kyverno Version

1.8.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

### Description

We have some images on AWS ECR, the policy worked (not blocking) when we allowed all images from our ECR.

```yaml
anyPattern:
  - spec:
      containers:
        - image: "xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/*"
```

However, it was not working when we would like to only allow **certain images** from ECR instead of all images from ECR

This issue didn't happen when we use other docker registris, like from **docker.io**.

For example, following 2 rules are still blocking our images from ECR

Note: dash `-` did exist in our both path and image name as part of ECR URL.

```yaml
anyPattern:
  - spec:
      containers:
        - image: "xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/my-path/*"
```

```yaml
anyPattern:
  - spec:
      containers:
        - image: "xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/my-path/my-image:*"
```

### Steps to reproduce

Below rule should not block images from ECR.

 > Note: dash `-` did exist in our both path and image name as part of ECR URL.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-images
  annotations:
    policies.kyverno.io/title: test
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
     test
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: allowed-images
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "my-app*"
              names:
                - "*"

      validate:
        message: "Unknown image registry. Please check ClusterPolicy"
        anyPattern:

          # Our full URL of registry is xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/my-path/my-image:1.0"
          # This is not working
          - spec:
              =(ephemeralContainers):
                - image: "xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/my-path/*"
              =(initContainers):
                - image: "xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/my-path/*"
              containers:
                - image: "xxxxxxxxxxxx.dkr.ecr.*.amazonaws.com/my-path/*"

          # this is working
          - spec:
              =(ephemeralContainers):
                - image: "docker.io/alpine/curl:*"
              =(initContainers):
                - image: "docker.io/alpine/curl:*"
              containers:
                - image: "docker.io/alpine/curl:*"

```

### Expected behavior

Above rule should not block certain images from AWS ECR

### Screenshots

No

### Kyverno logs

```shell
No
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
You're on 1.8, quite an old version at this point, and yet this was tested successfully on 1.10:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: allowed-images
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Unknown image registry. Please check ClusterPolicy"
        pattern:
          spec:
            =(ephemeralContainers):
              - image: "123456789.dkr.ecr.*.amazonaws.com/my-path/*"
            =(initContainers):
              - image: "123456789.dkr.ecr.*.amazonaws.com/my-path/*"
            containers:
              - image: "123456789.dkr.ecr.*.amazonaws.com/my-path/*"
```
`y.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: container01
    image: 123456789.dkr.ecr.foo.amazonaws.com/my-path/my-image:1.0
```

```sh
$ k apply -f y.yaml 
pod/mypod created
```
