### ISSUE TITLE
[Bug] require-emptydir-requests-and-limits fails for valid pod spec

### ISSUE THREAD

**Issue by bb-Ricardo** [kyverno/policies#781]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

EKS

### Description

During applying policies in our environment I stumbled across, what it seems like, an issue.

The policy "require-emptydir-requests-and-limits" seems to fail for a pod spec which should be considered valid and fulfilling the requirements.

### Steps to reproduce

donwload policy:
```bash
curl -LO https://github.com/kyverno/policies/raw/main/other/rec-req/require-emptydir-requests-limits/require-emptydir-requests-limits.yaml
```
specify pod spec:
```yaml
# test spec
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  initContainers:
    - name: certificates
      image: busybox
      volumeMounts:
        - name: etc-ssl-certs
          mountPath: /etc/ssl/certs
      resources:
        limits:
          ephemeral-storage: 256Mi
        requests:
          ephemeral-storage: 256Mi
    - name: configure
      image: busybox
      volumeMounts:
        - name: etc-ssl-certs
          mountPath: /etc/ssl/certs/
        - name: my-app-secrets
          mountPath: /init-secrets
      resources:
        limits:
          ephemeral-storage: 256Mi
        requests:
          ephemeral-storage: 256Mi
  containers:
    - name: my-app
      image: busybox
      resources:
        limits:
          cpu: "2"
          ephemeral-storage: 1Gi
          memory: 500Mi
        requests:
          ephemeral-storage: 500Mi
      volumeMounts:
        - name: etc-ssl-certs
          mountPath: /etc/ssl/certs/
        - name: my-app-secrets
          mountPath: /etc/secrets
  volumes:
    - name: my-app-secrets
      emptyDir:
        medium: Memory
    - name: etc-ssl-certs
      emptyDir:
        medium: "Memory"
```

run validation:
```shell
kyverno apply require-emptydir-requests-limits.yaml --resource pod.yaml

Applying 1 policy rule to 1 resource...

policy require-emptydir-requests-and-limits -> resource default/Pod/my-app-pod failed:
1. check-emptydir-requests-limits: validation failure: Containers mounting emptyDir volumes must specify requests and limits for ephemeral-storage.

pass: 0, fail: 2, warn: 0, error: 0, skip: 4 
```

### Expected behavior

the policy validation passes.

Adding the `my-app-secret` mount will validate successful
```diff
diff --git a/pod.yaml b/pod-working.yaml
index 09c59b3..8c31074 100644
--- a/pod.yaml
+++ b/pod-working.yaml
@@ -10,6 +10,8 @@ spec:
       volumeMounts:
         - name: etc-ssl-certs
           mountPath: /etc/ssl/certs
+        - name: my-app-secrets
+          mountPath: /init-secrets
       resources:
         limits:
           ephemeral-storage: 256Mi 
```

```bash
kyverno apply require-emptydir-requests-limits.yaml --resource pod-working.yaml

Applying 1 policy rule to 1 resource...

pass: 2, fail: 0, warn: 0, error: 0, skip: 4 
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
