### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RajatPorwal5** [kyverno/policies#783]
### Kyverno Version

1.10.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

EKS

### Description

We have created a cluster policy to sync secrets as below. As soon as the policy gets created, Kyverno floods the API server with UpdateRequest resources and results in throttling API Server. But when we  remove `synchronize: true` from policy, it works fine and we see only few UpdateRequest getting created.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: k8s-secret-replicator
spec:
  generateExisting: true
  validationFailureAction: Enforce
  rules:
    - name: replicate-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  generate.kyverno.io/policy-name: "k8s-secret-replicator"
      generate:
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        cloneList:
          namespace: test-ns
          kinds:
            - v1/Secret
          selector:
            matchLabels:
              k8s.expediagroup.com/replicate-to: "all"](exclude:)
```

### Steps to reproduce

Create below clusterpolicy to sync secrets.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: k8s-secret-replicator
spec:
  generateExisting: true
  validationFailureAction: Enforce
  rules:
    - name: replicate-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              selector:
                matchLabels:
                  generate.kyverno.io/policy-name: "k8s-secret-replicator"
      generate:
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        cloneList:
          namespace: test-ns
          kinds:
            - v1/Secret
          selector:
            matchLabels:
              k8s.expediagroup.com/replicate-to: "all"](exclude:)
```

### Expected behavior

Kube-api server should not be throttled because of updaterequest creation.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
