### ISSUE TITLE
[Bug] Mutate Deployments Policy doesn't mutate Deployments based on "organic" changes

### ISSUE THREAD

**Issue by L30Bola** [kyverno/policies#788]
### Kyverno Version

1.10.x

### Kubernetes Version

1.25.x

### Kubernetes Platform

KinD

### Description

To run Kyverno on my KinD I installed it using Helm with this values:

<details><summary><code>kyverno.yaml</code></summary>
<p>

```yaml
features:
  logging:
    verbosity: 10
    format: json

backgroundController:
  rbac:
    clusterRole:
      extraResources:
      - apiGroups:
        - 'apps'
        resources:
        - deployments
        - deployments/scale
        verbs:
        - "*"
```

</p>
</details> 

I installed like this `helm upgrade -i kyverno kyverno/kyverno --version 3.0.5 -n kyverno --create-namespace -f kyverno.yaml`

I tried using the policy defined [here](https://kyverno.io/policies/other/s-z/scale-deployment-zero/scale-deployment-zero/) and I needed to make some changes to make it work. Right now my policy is as follows:

<details><summary><code>scale-deployment-zero.yaml</code></summary>
<p>

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: scale-deployment-zero
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Scale Deployment to Zero
    policies.kyverno.io/category: other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      If a Deployment's Pods are seen crashing multiple times it usually indicates
      there is an issue that must be manually resolved. Removing the failing Pods and
      marking the Deployment is often a useful troubleshooting step. This policy watches
      existing Pods and if any are observed to have restarted more than
      once, indicating a potential crashloop, Kyverno scales its parent deployment to zero
      and writes an annotation signaling to an SRE team that troubleshooting is needed.
      It may be necessary to grant additional privileges to the Kyverno ServiceAccount,
      via one of the existing ClusterRoleBindings or a new one, so it can modify Deployments.
spec:
  rules:
  - name: annotate-deployment-rule
    match:
      any:
      - resources:
          kinds:
          - Pod.status
          namespaces:
          - test
    preconditions:
      all:
      - key: "{{ sum(request.object.status.containerStatuses[*].restartCount || [`0`]) }}"
        operator: GreaterThan
        value: 1
      - key: "{{ request.object.metadata.ownerReferences[0].kind }}"
        operator: Equals
        value: "ReplicaSet"
    context:
    - name: rsname
      variable:
        jmesPath: "request.object.metadata.ownerReferences[0].name"
        default: ''
    - name: deploymentname
      apiCall:
        urlPath: "/apis/apps/v1/namespaces/{{ request.object.metadata.namespace }}/replicasets/{{ rsname }}"
        jmesPath: "metadata.ownerReferences[0].name"
    mutate:
      targets:
      - apiVersion: apps/v1
        kind: Deployment/scale
        name: "{{ deploymentname }}"
        namespace: "{{ request.object.metadata.namespace }}"
      - apiVersion: apps/v1
        kind: Deployment
        name: "{{ deploymentname }}"
        namespace: "{{ request.object.metadata.namespace }}"
      patchStrategicMerge:
        spec:
          replicas: 0
        metadata:
          annotations:
            sre.corp.org/troubleshooting-needed: "true"
          labels:
            sre.corp.org/troubleshooting-needed: "true"
```

</p>
</details> 

The problem is that the policy only works when I manually change the watched resource (the Pod.status of a Pod inside the `test` namespace).  For this testing purpose, I'm using this Deployment:

<details><summary><code>deployment.yaml</code></summary>
<p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: test
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["false"]
```

</p>
</details> 

If we wait around 20 seconds, the Pod of the above Deployment will reach 2 RestartCount and that should trigger the above policy, but it doesn't (that's what I called "organic"). But, if I manually change any field of the status object of the Pod, then the policy is applied successfully. This `patch` is enough:

```
$ kubectl patch pod -n test alpine-6857cdb8cc-2tdl6 --subresource status --patch '{ "status":  { "containerStatuses": [ { "restartCount": 2 } ] } }'
```

### Steps to reproduce

1.  Apply this `kubectl apply -f scale-deployment-zero.yaml`:
<details><summary><code>scale-deployment-zero.yaml</code></summary>
<p>

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: scale-deployment-zero
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Scale Deployment to Zero
    policies.kyverno.io/category: other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      If a Deployment's Pods are seen crashing multiple times it usually indicates
      there is an issue that must be manually resolved. Removing the failing Pods and
      marking the Deployment is often a useful troubleshooting step. This policy watches
      existing Pods and if any are observed to have restarted more than
      once, indicating a potential crashloop, Kyverno scales its parent deployment to zero
      and writes an annotation signaling to an SRE team that troubleshooting is needed.
      It may be necessary to grant additional privileges to the Kyverno ServiceAccount,
      via one of the existing ClusterRoleBindings or a new one, so it can modify Deployments.
spec:
  rules:
  - name: annotate-deployment-rule
    match:
      any:
      - resources:
          kinds:
          - Pod.status
          namespaces:
          - test
    preconditions:
      all:
      - key: "{{ sum(request.object.status.containerStatuses[*].restartCount || [`0`]) }}"
        operator: GreaterThan
        value: 1
      - key: "{{ request.object.metadata.ownerReferences[0].kind }}"
        operator: Equals
        value: "ReplicaSet"
    context:
    - name: rsname
      variable:
        jmesPath: "request.object.metadata.ownerReferences[0].name"
        default: ''
    - name: deploymentname
      apiCall:
        urlPath: "/apis/apps/v1/namespaces/{{ request.object.metadata.namespace }}/replicasets/{{ rsname }}"
        jmesPath: "metadata.ownerReferences[0].name"
    mutate:
      targets:
      - apiVersion: apps/v1
        kind: Deployment/scale
        name: "{{ deploymentname }}"
        namespace: "{{ request.object.metadata.namespace }}"
      - apiVersion: apps/v1
        kind: Deployment
        name: "{{ deploymentname }}"
        namespace: "{{ request.object.metadata.namespace }}"
      patchStrategicMerge:
        spec:
          replicas: 0
        metadata:
          annotations:
            sre.corp.org/troubleshooting-needed: "true"
          labels:
            sre.corp.org/troubleshooting-needed: "true"
```

</p>
</details> 

2. Then apply this `kubectl create ns test && kubectl apply -n test -f deployment.yaml`:
<details><summary><code>deployment.yaml</code></summary>
<p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: test
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["false"]
```

</p>
</details> 

3. Wait around 20 seconds and check if the deployment was downscaled
4. Patch the running pod and check that the deployment was downscaled successfully

### Expected behavior

After the 20 seconds wait, the deployment should be downscaled, and the label and annotation should be applied.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
