### ISSUE TITLE
Sample mutate policy for pod security context attributes

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#79]
See: https://kubernetes.slack.com/archives/C8P1DRTJA/p1626520243195800

> Anyone know of a mutating webhook that will inject default security contexts into a pod?  Ie if you don't specify a runas it creates it for you?  Something similar to how openshift mutates pods

A Kyverno policy can check of `runAs` and other `securityContext` attributes like `runAsNonRoot` are specified and automatically inject them if needed.

**Comment by chipzoller** [comment]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-securitycontext
spec:
  background: false
  rules:
  - name: add-default-securitycontext
    match:
      resources:
        kinds:
        - Pod
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            +(runAsUser): 1000
            +(runAsGroup): 3000
            +(fsGroup): 2000
```
