### ISSUE TITLE
[Bug] disallow-capabilities-strict/require-drop-all policy doesn't match lowercase `all`.

### ISSUE THREAD

**Issue by bodgit** [kyverno/policies#790]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

### Description

We have had Kyverno installed with the validation rules set to audit. I've been going through and trying to clear up the failing policies. I noticed our coredns deployment was failing the `disallow-capabilities-strict/require-drop-all` policy. Looking at the deployment, it has the following `securityContext`:
```yaml
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
```
If I edit the Deployment and change the `all` to `ALL`, the rule clears.

Annoyingly, coredns is being deployed as an EKS addon so I can't easily manage the resource. I can edit the Deployment post-install, but then when it's upgraded it will revert back and assuming I can get the cluster to a state where I can change the validation rules to enforce rather than audit, this would block an upgrade.

Is it possible to make this policy case-insensitive? The Kubernetes API seems to accept the lowercase `all` so it seems to be a valid value.

### Steps to reproduce

1. Create a Pod with the following `securityContext`:
```yaml
securityContext:
  capabilities:
    drop:
      - all
```
2. Notice require-drop-all policy fires.
3. Change the `all` to `ALL`, watch policy clear.

### Expected behavior

If the Kubernetes API considers `all` a valid value, Kyverno policies should also.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
