### ISSUE TITLE
[Bug] add existing variable to number

### ISSUE THREAD

**Issue by younsl** [kyverno/policies#792]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

## My objective

After receiving the label that specifies the preStop time as a variable, I would like to create a Mutate Policy that does +10

Example 1:

- **preStop**: 50
- **tGPS**: 50 + 10 = 60

Example 2:

- **preStop sleep**: 35
- **tGPS**: 35 + 10 = 45

### Cluster Policy

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-variable-test
  annotations:
    policies.kyverno.io/title: Mutate termination grace period seconds
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.8.0-rc2
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Mutate policy for preStop script sleep.
      Mutate rules to replace onetool-eks.
spec:
  schemaValidation: false
  rules:
  # [1/2] prestop
  - name: mutate-prestop-script-sleep-test
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations:
          - CREATE
          namespaceSelector:
            matchLabels:
              policies.kyverno.io/variable-test-mutate-rules-injection: enabled
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              role: spring-app
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              policies.kyverno.io/variable-test-mutate-rules-injection: disabled
    context:
    - name: preStopSleepSeconds
      variable:
        jmesPath: request.object.metadata.labels.preStopSleepSeconds
        default: 30
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/containers/0/lifecycle/preStop/exec/command"
          value:
          - "/bin/sh"
          - "-c"
          - "sleep {{ preStopSleepSeconds }}"

  # [2/2] terminationGracePeriodSeconds
  - name: mutate-termination-grace-period-seconds-test
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations:
          - CREATE
          namespaceSelector:
            matchLabels:
              policies.kyverno.io/variable-test-mutate-rules-injection: enabled
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              role: spring-app
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              policies.kyverno.io/coinone-mutate-rules-injection: disabled
    context:
    - name: preStopSleepSeconds
      variable:
        jmesPath: request.object.metadata.labels.preStopSleepSeconds
        default: 30
    mutate:
      patchStrategicMerge:
        spec:
          terminationGracePeriodSeconds: add({{ preStopSleepSeconds }}, '10')
```

### Mutate testing resource

```bash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mutate-var-test
    policies.kyverno.io/variable-test-mutate-rules-injection: enabled
  name: mutate-var-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutate-var-test
  template:
    metadata:
      labels:
        app: mutate-var-test
        policies.kyverno.io/variable-test-mutate-rules-injection: enabled
        preStopSleepSeconds: "50"
    spec:
      containers:
      - image: nginx:1.25.2
        name: nginx
```

## Error

But error occured (Events for deployment):

```bash
  - lastTransitionTime: "2023-10-25T06:13:07Z"
    lastUpdateTime: "2023-10-25T06:13:07Z"
    message: 'admission webhook "mutate.kyverno.svc-fail" denied the request: mutation
      policy mutate-pre-post-scripts-injection error: failed to validate resource
      mutated by policy mutate-pre-post-scripts-injection: ValidationError(io.k8s.api.core.v1.Pod.spec.terminationGracePeriodSeconds):
      invalid type for io.k8s.api.core.v1.PodSpec.terminationGracePeriodSeconds: got
      "string", expected "integer"'
```

### Steps to reproduce

1. `kubectl create ns test`
2. `kubectl apply -f <CLUSTER_POLICY_FILENAME>.yaml`
3. `kubectl apply -f <DEPLOY_FILENAME>.yaml`

 The Manifest files I used for testing are above.

### Expected behavior

It should be Mutated as a result of terminationGracePeriodSeconds being +10.

> **Question**
> Can I use Integer type for kyverno variable?

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by younsl** [comment]
Thanks for your helping, @vishal-chdhry!

On [kubernetes kyverno channel](https://kubernetes.slack.com/archives/CLGR9BJU9/p1698217533513459), I got a solution in the following way:

## Solution

### Notes for JMESpath syntax

- JMESpath should be enclosed in “”
- Use `to_number()` JMESpath function: [kyverno policy example](https://kyverno.io/policies/cert-manager/limit-duration/limit-duration/)

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-variable-test
  annotations:
    policies.kyverno.io/title: Mutate termination grace period seconds
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.8.0-rc2
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Mutate policy for preStop script sleep.
      Mutate rules to replace onetool-eks.
spec:
  schemaValidation: false
  rules:
  # [1/2] prestop
  - name: mutate-prestop-script-sleep-test
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations:
          - CREATE
          namespaceSelector:
            matchLabels:
              policies.kyverno.io/variable-test-mutate-rules-injection: enabled
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              role: spring-app
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              policies.kyverno.io/variable-test-mutate-rules-injection: disabled
    context:
    - name: preStopSleepSeconds
      variable:
        jmesPath: request.object.metadata.labels.preStopSleepSeconds
        default: "30"
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/containers/0/lifecycle/preStop/exec/command"
          value:
          - "/bin/sh"
          - "-c"
          - "sleep {{ preStopSleepSeconds }}"

  # [2/2] terminationGracePeriodSeconds
  - name: mutate-termination-grace-period-seconds-test
    match:
      any:
      - resources:
          kinds:
          - Pod
          operations:
          - CREATE
          namespaceSelector:
            matchLabels:
              policies.kyverno.io/variable-test-mutate-rules-injection: enabled
    exclude:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              role: spring-app
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          selector:
            matchLabels:
              policies.kyverno.io/coinone-mutate-rules-injection: disabled
    context:
    - name: preStopSleepSeconds
      variable:
        jmesPath: request.object.metadata.labels.preStopSleepSeconds
        default: 30
    mutate:
      patchStrategicMerge:
        spec:
          # JMESpath should be enclosed in " "
          terminationGracePeriodSeconds: "{{ add(to_number(preStopSleepSeconds), to_number('10')) }}"
```

**Test Deployment**
`[2]` tGPS(terminationGracePeriodSeconds) was set to `[1]` preStop's sleep time + 10!

```yaml
...
spec:
  containers:
  - image: nginx:1.25.2
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - sleep 30 # [1]
  terminationGracePeriodSeconds: 40 # [2]
```

I am closing this Issue because the issue has been resolved.
