### ISSUE TITLE
[Bug] Unexpected Kyverno Policy require-requests-limits Triggering on Deployment and ReplicaSet Resources

### ISSUE THREAD

**Issue by neverlless** [kyverno/policies#795]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

Bare metal

### Description

I am facing an issue with the Kyverno policy require-requests-limits causing Deployment and ReplicaSet resource validation errors, even though the policy was created for the Pod they are being validated with the required resource requests and limits specified. The validation error message received is:

`validation error: CPU and memory resource requests and limits are required. rule autogen-validate-resources failed at path /spec/template/spec/containers/0/resources/limits/`

The error is not exclusive to a particular application; it's prevalent across various applications including but not limited to metallb-controller. The policy seems to work fine on Pod resources but fails to validate Deployment and ReplicaSet resources.

Below are the snippets from a representative Deployment manifest and the Kyverno policy in question:
Deployment Manifest (Example from metallb-controller):
```yaml
...
      containers:
        - name: metallb-controller
          ...
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 128Mi
...
```

Kyverno Policy:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-requests-limits
  annotations:
    policies.kyverno.io/title: Require Limits and Requests
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      As application workloads share cluster resources, it is important to limit resources
      requested and consumed by each Pod. It is recommended to require resource requests and
      limits per Pod, especially for memory and CPU. If a Namespace level request or limit is specified,
      defaults will automatically be applied to each Pod based on the LimitRange configuration.
      This policy validates that all containers have something specified for memory and CPU
      requests and memory limits.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: validate-resources
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
        - nginx-proxy
    validate:
      message: "CPU and memory resource requests and limits are required."
      pattern:
        spec:
           containers:
              - name: "*"
                resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
                  requests:
                    memory: "?*"
                    cpu: "?*"
```

### Steps to reproduce

1. Apply the Kyverno policy require-requests-limits to your Kubernetes cluster.
```yaml
kubectl apply -f kyverno-policy.yaml
```
2. Deploy an application, for instance, metallb-controller, with the necessary resource requests and limits specified in its Deployment manifest.
```yaml
kubectl apply -f metallb-controller-deployment.yaml
```
3. Observe the validation error triggered by Kyverno on the Deployment and ReplicaSet resources.
```plaintext
kubectl describe deployment metallb-controller -n <namespace>
kubectl describe replicaset <replicaset-name> -n <namespace>
kubectl events --types=Warning
```

### Expected behavior

The require-requests-limits policy must check the requests and resource limits specified in Pod manifests and not fail on Deployment and ReplicaSet manifests

### Screenshots

<img width="1025" alt="image" src="https://github.com/kyverno/policies/assets/104908866/6dd519fc-5665-421e-a8ba-586b89b64f58">
<img width="733" alt="image" src="https://github.com/kyverno/policies/assets/104908866/c2298a5e-5ce2-4c55-b174-2fe3b97f1697">
<img width="722" alt="image" src="https://github.com/kyverno/policies/assets/104908866/0837732a-39c4-4704-8f7b-9877e56a42b8">
<img width="667" alt="image" src="https://github.com/kyverno/policies/assets/104908866/46e213c2-be6d-486f-a3bb-18060698c743">

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
