### ISSUE TITLE
[Bug] VerifyImages Autogen Rule cannot update Annotation on StatefulSet/Deployment

### ISSUE THREAD

**Issue by NicoGartmann** [kyverno/policies#796]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

EKS

### Description

We manage an application in our cluster via helm using terraform. The application consists of a statefulset and a deployment. The docker images are signed using cosign. 

After installing the kyverno helm-chart (chart version 3.0.0, app version v1.10.3)  and defining the ClusterPolicy below, we ran into an issue.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - testing
      verifyImages:
        - imageReferences:
            - "test-image*"
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                         pubKeyContent            
```
Our CICD-Pipeline generates new images for the deployment and statefulset and applies the changes using terraform and helm. The first run after having deployed the ClusterPolicy was successful. But subsequent runs fail with the following error:

```
resource Deployment/testing/test-client-depl was blocked due to the following policies 

check-image:
    autogen-check-image: kyverno.io/verify-images annotation cannot be changed
    && failed to replace object: admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource StatefulSet/testing/server-sts was blocked due to the following policies 
 check-image:
    autogen-check-image: kyverno.io/verify-images annotation cannot be changed
    : failed to replace object: admission webhook "mutate.kyverno.svc-fail" denied the request: 
```

### Steps to reproduce

1. Deploy an application using statefulset and deployment with helm and terraform
2. Deploy a ClusterPolicy as mentioned above
3. Deploy a newer version of your application with helm and terraform - this deployment should work fine
4. Deploy an even newer version of your application with helm and terraform - this deployment should fail with the error mentioned above

### Expected behavior

We expect that with newer deployments, the annotation can be updated, containing the newer versions of the images and the application can be deployed

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
