### ISSUE TITLE
Sample policy to validate for v1.22 deprecated APIs

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#80]
See: https://twitter.com/Marcus_Noble_/status/1417007780888825856

Kubernetes v1.22 removes a number of deprecated APIs. The policy would check for those apiVersions and kinds and block / report their usage.

**Comment by JimBugwadia** [comment]
Here is a sample:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-deprecated-apis
  annotations:
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/description: >-
      As the Kubernetes API evolves, APIs are periodically reorganized or upgraded. 
      When APIs evolve, the old APIs they replace are deprecated, and eventually removed. 
      See Kubernetes API removals to read more about Kubernetes' policy on removing APIs.
      See: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/ 
      for details.
spec:
  validationFailureAction: enforce
  rules:
  - name: validate-v1-22-removals
    match:
      resources:
        kinds:
        - admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration
        - admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration
        - apiextensions.k8s.io/v1beta1/CustomResourceDefinition
        - apiregistration.k8s.io/v1beta1/APIService
        - authentication.k8s.io/v1beta1/TokenReview
        - authorization.k8s.io/v1beta1/SubjectAccessReview
        - authorization.k8s.io/v1beta1/LocalSubjectAccessReview
        - authorization.k8s.io/v1beta1/SelfSubjectAccessReview 
        - certificates.k8s.io/v1beta1/CertificateSigningRequest
        - coordination.k8s.io/v1beta1/Lease
        - extensions/v1beta1/Ingress
        - networking.k8s.io/v1beta1/Ingress
    validate:
      message: "{{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated and will be removed in v1.22. See: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/"
      deny: {}
```

When used with this YAML:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /path1
            backend:
              serviceName: testsvc1
              servicePort: 4201
          - path: /path2
            backend:
              serviceName: testsvc2
              servicePort: 4202
```

It blocks creation as follows:

```sh
kubectl create -f C:\tmp\kyverno\resources\ingress.yaml
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error from server: error when creating "C:\\tmp\\kyverno\\resources\\ingress.yaml": admission webhook "validate.kyverno.svc" denied the request:

resource Ingress/default/ingress-fanout was blocked due to the following policies

check-deprecated-apis:
  validate-v1-22-removals: 'networking.k8s.io/v1beta1/Ingress is deprecated and will
    be removed in v1.22. See: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/'
```
