### ISSUE TITLE
[Sample] additional rule to validate PDB when workload exists in pdb-minavailable-check

### ISSUE THREAD

**Issue by erikgb** [kyverno/policies#801]
### Problem Statement

We are having issues with users creating invalid PDB vs. workload in our multi-tenant clusters, and while the PDB policies in this policy catalog help, we have seen examples of PDBs added/updated:

- without any matching pods 
- matching existing workloads where the PDB is "invalid" on creation

The first case might be a bit difficult to handle, but the second one could be caught by a second rule in the existing [pdb-minavailable-check](https://github.com/kyverno/policies/blob/main/other/m-q/pdb-minavailable/pdb-minavailable.yaml) policy. The current rule assumes that the PDB already exists when the workload is created/updated. We want to make the policy also cover the opposite order: 

1. Workload with X replicas exists.
2. A PDB matching the workload is created. The PDB specifies `minAvailable: X` and should be denied by the policy.

### Solution Description

I would suggest adding a second rule to policy selecting on kind PDB, with the same overall validation as the existing rule. The most tricky part is probably how to find the desired number of replicas from the workload of controlling pods matching the PDB. Maybe we can use `ownerReferences`?

For the following good and bad resources, I will assume a workload already exists in the cluster. E.g.

````yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
  namespace: pdb-minavailable-ns
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: busbyox
        image: busybox:1.35
````

### Example "Good" Resource

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ss-example-good
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: busybox
```

### Example "Bad" Resource

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ss-example-bad
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: busybox
```

### Other Comments

I would be happy to submit a PR to fix this, but I think I need some help on the policy logic - as I am new to Kyverno.

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1698916081905549

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
