### ISSUE TITLE
[Bug] Unable to see custom labels in kyverno cluster policy

### ISSUE THREAD

**Issue by jmk47912204** [kyverno/policies#810]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

GKE

### Description

Is it possible to set **customLabels** for individual cluster policy from **kyverno-policies** helm chart. Because based on this [issue](https://github.com/kyverno/kyverno/issues/6259), it should have been fixed in v3.0.0 but we are running kyverno policies chart version **v3.0.4** because I don't see any labels have been attached to individual cluster policy 

It would be great to have those label in cluster policy report metrics for better visibility to other teams.

```
# -- Additional labels.
customLabels:
  tags.meta/app-name: kyverno
  tags.meta/app-type: infra
```

```
k get cpol check-apis-versions -o yaml | k neat
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno-policies
    meta.helm.sh/release-namespace: kyverno
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/description: Kubernetes APIs are sometimes deprecated and
      removed after a few releases. As a best practice, older API versions should
      be replaced with newer versions. This policy validates for APIs that are deprecated
      or scheduled for removal.
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Kubernetes APIs
    policies.kyverno.io/title: Check API Versions
  labels:
    app.kubernetes.io/managed-by: Helm
  name: check-apis-versions
spec:
```

### Steps to reproduce

1. Set custom labels in kyverno-policies chart values.yaml file

```
# -- Additional labels.
customLabels:
  tags.meta/app-name: kyverno
  tags.meta/app-type: infra
```
2. Policy Definition:

```
{{- $name := "check-apis-versions" }}
{{- if eq (include "kyverno-policies.podSecurityOther" (merge (dict "name" $name) .)) "true" }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    {{- with .Values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
    {{- end }}
    {{- if .Values.podSecuritySeverity }}
    policies.kyverno.io/severity: {{ .Values.podSecuritySeverity | quote }}
    {{- end }}
    policies.kyverno.io/title: Check API Versions
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/subject: Kubernetes APIs
    policies.kyverno.io/description: >-
      Kubernetes APIs are sometimes deprecated and removed after a few releases.
      As a best practice, older API versions should be replaced with newer versions.
      This policy validates for APIs that are deprecated or scheduled for removal.
spec:
  {{- with index .Values "validationFailureActionByPolicy" $name }}
  validationFailureAction: {{ toYaml . }}
  {{- else }}
  validationFailureAction: {{ .Values.validationFailureAction }}
  {{- end }}
  {{- with concat (index .Values "validationFailureActionOverrides" "all") (default list (index .Values "validationFailureActionOverrides" $name)) }}
  validationFailureActionOverrides: {{ toYaml . | nindent 4 }}
  {{- end }}
  background: {{ .Values.background }}
  failurePolicy: {{ .Values.failurePolicy }}
  rules:
    - name: validate-v1-27-removals
      match:
        any:
          - resources:
              kinds:
                - storage.k8s.io/*/CSIStorageCapacity
      {{- with merge (index .Values "policyExclude" "check-apis-versions") (index .Values "policyExclude" $name) }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge (index .Values "policyPreconditions" "check-apis-versions") (index .Values "policyPreconditions" $name) }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      validate:
        message: >-
          ( request.object.apiVersion )/( request.object.kind ) is deprecated and will be removed in v1.27.
          See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        deny: {}
{{- end }}
```
3. Deploy this policy and check whether labels are present or not. 

```
k get cpol check-apis-versions -o yaml | k neat
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno-policies
    meta.helm.sh/release-namespace: kyverno
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/description: Kubernetes APIs are sometimes deprecated and
      removed after a few releases. As a best practice, older API versions should
      be replaced with newer versions. This policy validates for APIs that are deprecated
      or scheduled for removal.
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Kubernetes APIs
    policies.kyverno.io/title: Check API Versions
  labels:
    app.kubernetes.io/managed-by: Helm
  name: check-apis-versions
spec:
```

### Expected behavior

1. CustomLabels should present for all kyverno policies
2. Support to add labels on each cluster policy level to identify the policy owner/team for tracking purpose

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1701249257532149

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
