### ISSUE TITLE
[Question] Validate rule to allow only dry-run requests

### ISSUE THREAD

**Issue by Da-Juan** [kyverno/policies#811]
### Problem Statement

Hello,

Is there a way to inspect query parameters to filter requests?
I would like to create a validate rule to allow only dry-run requests and ad mentioned in [Kubernetes API doc](https://kubernetes.io/docs/reference/using-api/api-concepts/#make-a-dry-run-request) dry-run is triggered by setting the `dryRun` query parameter.

### Solution Description

I don't have a solution, I'd be glad if anyone has a lead :)

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
You can use the `request.dryRun` field for this purpose. Here's an example:

```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: demo-policy
spec:
  validationFailureAction: Enforce
  rules:
  - name: demo-rule
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: nginx
    validate:
      message: "Must use dry run to do this."
      deny:
        conditions:
          all:
          - key: "{{request.dryRun}}"
            operator: Equals
            value: false
```
