### ISSUE TITLE
[Sample] policies to audit and restrict long-lived tokens for service accounts

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#819]
### Problem Statement

Prior to v1.24, Kubernetes generated long lived service accounts by default. These pose a security risk.

### Solution Description

Sample policies to:
* audit for secrets with `type: kubernetes.io/service-account-token`
* audit for service accounts with any `secrets.name` configured
* enforce pod `automountServiceAccountToken: false`

### Other Comments

See:
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
- https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/
- https://eng.d2iq.com/blog/service-account-tokens-in-kubernetes-v1.24/

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1701451535229319

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Third request is already in the library [here](https://kyverno.io/policies/other/restrict-automount-sa-token/restrict-automount-sa-token/).

**Comment by JimBugwadia** [comment]
@swastik959 - here is a policy using CEL that addresses the checks listed:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-auto-mount-token
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: deny-auto-mount-token
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        cel:
          expressions:
            - message: "the default service account is not allowed"
              expression: >-
                object.spec.serviceAccountName != 'default'
            - message: "automountServiceAccountToken must be false" 
              expression: >-
                !has(object.spec.automountServiceAccountToken) || 
                object.spec.automountServiceAccountToken == false
            - message: "pod token expiration must be less than or equal to 1 hour"
              expression: >-
                !has(object.spec.volumes) || 
                  object.spec.volumes.all(v, !has(v.projected) || 
                    !has(v.projected.sources) ||
                      v.projected.sources.all(s, !has(s.serviceAccountToken) || 
                        !has(s.serviceAccountToken) || 
                        !has(s.serviceAccountToken.expirationSeconds) || 
                        s.serviceAccountToken.expirationSeconds <= 3600))
```

For the samples, it may be best to separate into 3 different policies.

We will need tests to validate all expressions work as expected.

**Comment by JimBugwadia** [comment]
This checks for ServiceAccounts that have a static token:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-service-accounts
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: deny-secrets
      match:
        any:
        - resources:
            kinds:
              - ServiceAccount
      validate:
        cel:
          expressions:
            - message: "long lived API tokens are not allowed"
              expression: "!has(object.secrets)"
```

**Comment by JimBugwadia** [comment]
This checks for Secrets which have a static token:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-secret-service-account-token
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-service-account-token
      match:
        any:
        - resources:
            kinds:
              - Secret
      validate:
        cel:
          expressions:
            - message: "long lived API tokens are not allowed"
              expression: >-
                object.type != "kubernetes.io/service-account-token"
            - message: "automounting of tokens is not allowed"
              expression: >-
                !has(object.automountServiceAccountToken)

```
