### ISSUE TITLE
Preconditions vs operations

### ISSUE THREAD

**Issue by RelativeSure** [kyverno/policies#854]
### Kyverno Version

1.10.x

### Kubernetes Version

1.25.x

### Kubernetes Platform

Other (specify in description)

### Description

Hi,
I don't know if I picked the correct issue template, please correct me if I did not.
I have been chatting with my coworker if we should use preconditions or operations when excluding DELETE operation.
Is there any difference if we use preconditions or operations for it?
Any ressource usage differences?
Does the policies act differently?
Any difference if it's mutations or validation policies?
We use Rancher 2.7.9 on-prem, if that helps.
I did this for mutations:
```
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
```
Validation:
```
      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: NotEquals
            value: DELETE
```

### Steps to reproduce

1. Difference between operations and preconditions

### Expected behavior

It could, maybe should, be easier way to read the difference on the website

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
