### ISSUE TITLE
Policies Without Category

### ISSUE THREAD

**Issue by ossie-git** [kyverno/policies#862]
Hi,

While going through the policies over at https://kyverno.io/policies/, I noticed that there are some policies that don't appear under any **Policy Category**. I also noticed that it says there are 306 policies whereas when I select all the categories under **Policy Category**, it shows only 295 policies. I think grouping the non-categorized policies somewhere (possibly under the **Other** category) would be useful.

One example of this is: https://kyverno.io/policies/other/block-cluster-admin-from-ns/block-cluster-admin-from-ns/

I think the problem is that the `category` is set to `other` (lowercase) whereas the others in the **Other** category are set to `Other`

```yaml
metadata:
  name: block-cluster-admin-from-ns
  annotations:
    policies.kyverno.io/title: Block a Cluster Admin/s from CREATE/UPDATE/DELETE any object in a Namespace
    policies.kyverno.io/category: other
```

Here is a list of all policies that have `category: other` instead of `category: Other`:

```
other/verify-manifest-integrity/verify-manifest-integrity.yaml
other/update-image-tag/update-image-tag.yaml
other/scale-deployment-zero/scale-deployment-zero.yaml
other/restart-deployment-on-secret-change/restart-deployment-on-secret-change.yaml
other/require-unique-uid-per-workload/require-unique-uid-per-workload.yaml
other/record-creation-details/record-creation-details.yaml
other/label-nodes-cri/label-nodes-cri.yaml
other/generate-networkpolicy-existing/generate-networkpolicy-existing.yaml
other/cordon-and-drain-node/cordon-and-drain-node.yaml
other/concatenate-configmaps/concatenate-configmaps.yaml
other/block-cluster-admin-from-ns/block-cluster-admin-from-ns.yaml
```

You'll notice that these add up to 11, which covers the difference (306 - 295)
