### ISSUE TITLE
[Bug] Cannot get request.object.metadata.deletionTimestamp

### ISSUE THREAD

**Issue by wyfeng001** [kyverno/policies#864]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

### Description

A ClusterPolicy with:
```
      preconditions:
        all:
        - key: "{{request.object.metadata.deletionTimestamp || `0` }}"
          operator: Equals
          value: null
```

I cannot apply this policy with the error:
`admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].validate.preconditions.all[0].: entered value of `key`, `value` or `operator` is missing or misspelled
`

Is there a way to match the Pod without the `request.object.metadata.deletionTimestamp`

### Steps to reproduce

Apply a policy with the cluster policy above

### Expected behavior

can apply the policy

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
