### ISSUE TITLE
[Sample] PSA Namespace Reporting

### ISSUE THREAD

**Issue by ossie-git** [kyverno/policies#868]
### Problem Statement

As mentioned in [this](https://kyverno.io/blog/2023/06/12/using-kyverno-with-pod-security-admission/) article, having non-compliant namespaces as **PolicyReports** makes tracking them easiser

### Solution Description

The sample policy was actually mentioned in [this](https://kyverno.io/blog/2023/06/12/using-kyverno-with-pod-security-admission/) article. I just tweaked it (the `minversion` and some of the other **annotations** probably need to be modified)

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-psa-namespace-reporting
  annotations:
    policies.kyverno.io/title: Add PSA Namespace Reporting
    policies.kyverno.io/category: Pod Security Admission, EKS Best Practices
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/description: >-
      Pod Security Admission (PSA) can be controlled via the assignment of labels
      at the Namespace level which define the Pod Security Standard (PSS) profile
      in use and the action to take. If not using a cluster-wide configuration
      via an AdmissionConfiguration file, Namespaces must be explicitly labeled.
      This policy generates a PolicyReport for each namespace that does not have
      a label explicitly assigned.
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: check-namespace-labels
    match:
      any:
      - resources:
          kinds:
            - Namespace
    validate:
      message: This Namespace is missing a PSA label.
      pattern:
        metadata:
          labels:
            pod-security.kubernetes.io/*: "?*"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
