### ISSUE TITLE
[Bug] Do i need to change the way i write this policy for 1.11.2 (not 1.12 sorry)

### ISSUE THREAD

**Issue by mjschmidt** [kyverno/policies#875]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

EKS

### Description

Hi when we updated from 1.11 to 1.12 this policy stopped working

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-label-on-other-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-label-on-non-code-server-pods
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" | to_string(@) }}"
        operator: In
        value: ["true", ""]
    validate:
      message: "The label 'ssh-enabled' is only allowed on pods with the 'alpine' image."
      pattern:
        spec:
          containers:
          - image: "alpine*"
```

### Steps to reproduce

1. Copy and past the policy and try to run it, we do also have an istio side car, however this wasn't stopping anything before.

You're welcome to use this one liner:
kubectl run testimage --image alpine:3.18.5 --labels="ssh-enabled=true"
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Pod/test/testimage was blocked due to the following policies 

prevent-label-on-other-images:
  check-label-on-non-code-server-pods: 'validation error: The label ''ssh-enabled''
    is only allowed on pods with the ''alpine''
    image. rule check-label-on-non-code-server-pods failed at path /spec/containers/0/image/'

### Expected behavior

i expect the wildcard to allow any version of alpine to run. if i did this wrong for 1.11.2 let me know

Updated here: typo'd 1.12

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-label-on-other-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-label-on-non-code-server-pods
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" || '' }}"
        operator: AnyIn
        value:
        - "true"
        - ""
    validate:
      message: "The label 'ssh-enabled' is only allowed on pods with the 'alpine' image."
      pattern:
        spec:
          containers:
          - image: "alpine*"
```

**Comment by mjschmidt** [comment]
did you try to deploy with the policy? I really appreciate the quick response but i see the same error with the policy edit to the preconditions you've provided:

``` bash
kubectl run testimage --image=alpine:3 --labels="ssh-enabled=true"
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Pod/test/testimage was blocked due to the following policies 

prevent-label-on-other-images:
  check-label-on-non-code-server-pods: 'validation error: The label ''ssh-enabled''
    is only allowed on pods with the ''alpine'' image. rule check-label-on-non-code-server-pods
    failed at path /spec/containers/1/image/'
```

**Comment by mjschmidt** [comment]
should i be trying a regex split in the pattern section? I am not sure the right way to do this, but it seems like a bug if the intention is for the wildcard to work

**Comment by chipzoller** [comment]
I tested this on 1.11. It should be no different for 1.12 which is still in development.

**Comment by mjschmidt** [comment]
I copied and pasted your yaml and tested just to make sure before answering
The first error is more concerning where if the label doesn't exist it won't let pods launch at all, so i had to turn this policy to audit for now:
``` bash
kubectl run testimage --image=alpine alpine
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Pod/test/testimage was blocked due to the following policies 

prevent-label-on-other-images:
  check-label-on-non-code-server-pods: 'failed to evaluate preconditions: failed to
    substitute variables in condition key: failed to resolve request.object.metadata.labels."ssh-enabled"
    at path : JMESPath query failed: Unknown key "ssh-enabled" in path'
```
and
``` bash
kubectl run testimage --image=alpine --labels="ssh-enabled=true"
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Pod/test/testimage was blocked due to the following policies 

prevent-label-on-other-images:
  check-label-on-non-code-server-pods: 'validation error: The label ssh-enabled is
    only allowed on pods with the alpine image. rule check-label-on-non-code-server-pods
    failed at path /spec/containers/1/image/'
```


In the second error perhaps containers/1/image means it is accounting for my sidecar (it didn't use to). are you running 1.11.2 or 1.11.1, i had to upgrade because the of the bug that caused all the update requests to never delete, degrading the cluster performance over time.

**Comment by chipzoller** [comment]
How exactly are you installing Kyverno and with what method to see these results? The policy I provided above was tested on 1.11.1 and with your kubectl run command.

**Comment by chipzoller** [comment]
I just check checked this policy on the latest state of development by installing the [experimental manifest](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html) and it works. Here is a better version:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-label-on-other-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-label-on-non-code-server-pods
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" || '' }}"
        operator: Equals
        value: "true"
    validate:
      message: "The label 'ssh-enabled' is only allowed on pods with the 'alpine' image."
      pattern:
        spec:
          containers:
          - image: "alpine*"
```

This policy can be simplified still (yet autogen will be implicitly disabled):

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-label-on-other-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-label-on-non-code-server-pods
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              ssh-enabled: "true"
    validate:
      message: "The label 'ssh-enabled' is only allowed on pods with the 'alpine' image."
      pattern:
        spec:
          containers:
          - image: "alpine*"
```

**Comment by mjschmidt** [comment]
Yeah i don't think the issue is in the precondition, i think the issue is manifesting in the pattern section. I tried the following policy and i was able to launch an istio container, which launched with an istio side car (two containers in the pod same image) but i was not able to launch an alpine container (so istio side car, and alpine container in the same pod). I also temporarily rolled my deployment back to 1.11.1 so we're on the same policy engine. How do I make the pattern matching or?

``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-label-on-other-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-label-on-non-code-server-pods
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" || '' }}"
        operator: AnyIn
        value:
        - "true"
        - ""
    validate:
      message: "The label 'ssh-enabled' is only allowed on pods with the 'alpine' or 'docker.io/istio/proxyv2' images."
      anyPattern:
        - spec:
            containers:
              - image: "alpine*"
        - spec:
            containers:
              - image: "docker.io/istio/proxyv2*"
```

**Comment by mjschmidt** [comment]
Since you don't have istio installed I assume, here is a deployment yaml you can copy and paste:
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-istio-deployment
  labels:
    app: alpine-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-istio
  template:
    metadata:
      labels:
        app: alpine-istio
        ssh-enabled: "true"
    spec:
      containers:
      - name: alpine-container
        image: alpine
        command: ["/bin/sh", "-c", "while true; do sleep 60; done"]
      - name: istio-proxy-container
        image: docker.io/istio/proxyv2:1.20.1
        # The following are example settings, customize these as needed.
        env:
          - name: ISTIO_META_WORKLOAD_NAME
            value: "alpine-istio-workload"
          - name: ISTIO_META_OWNER
            value: "kubernetes://api/apps/v1/namespaces/default/deployment/alpine-istio-deployment"
        securityContext:
          runAsUser: 1337
        # Additional configuration for the Istio proxy container goes here.
```

**Comment by chipzoller** [comment]
Try this instead:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-label-on-other-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: check-label-on-non-code-server-pods
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" || '' }}"
        operator: Equals
        value: "true"
    validate:
      message: "The label 'ssh-enabled' is only allowed on pods with the 'alpine' image."
      pattern:
        spec:
          ^(containers):
          - image: "alpine*"
```

**Comment by mjschmidt** [comment]
That works! i really appreciate the help i have no idea how i would have figured that out. But does that mean that someone could list the image as part of a set of images in the pod/replicaset/deployment/statefulset spec but then simply list and use their own image instead (basically use the alpine image as a dummy while they do whatever they want with their own container in the pod and ssh to that. We're trying to enforce that people can only ssh to our specific container in the pod image.

its seems like malicious compliance issues and concerns could still be in play, which is why we wanted to only allow one of two images (our container and the side car) as allowed to have that ssh-enabled label. Does this make sense? Any guidance for handling this?

for context here is the auth policy that we have:
``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-istio-auth-policy-for-ssh
spec:
  rules:
  - name: generate-istio-auth-policy
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            ssh-enabled: "true"
    generate:
      kind: AuthorizationPolicy
      apiVersion: security.istio.io/v1beta1
      name: allow-ssh
      namespace: "{{request.object.metadata.namespace}}"
      data:
        metadata:
          labels:
            ssh-enabled: "true"
        spec:
          selector:
            matchLabels:
              ssh-enabled: "true"
          action: ALLOW
          rules:
          - to:
            - operation:
                ports: ["22"]
```

**Comment by mjschmidt** [comment]
I could compliment these policies with the following?

``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: limit-containers-in-ssh-enabled-pods
spec:
  validationFailureAction: Enforce
  rules:
  - name: max-two-containers-for-ssh-enabled
    match:
      resources:
        kinds:
        - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" }}"
        operator: Equals
        value: "true"
    validate:
      message: "A pod with 'ssh-enabled' set to true may have no more than two containers."
      deny:
        conditions:
        - key: "{{ request.object.spec.containers | length }}"
          operator: GreaterThan
          value: 2
```

to ensure just in our specific case that people can't list more containers since in our system we're making a special exception we don't want to be subverted? but if there is a more straight forward way to do this in the original image checking policy it would be fine to collapse it all down into one policy. Might just be a limitation of kyverno though, which if fine we can use our brains and write more policy rules to cover ourselves.

**Comment by chipzoller** [comment]
>  But does that mean that someone could list the image as part of a set of images in the pod/replicaset/deployment/statefulset spec but then simply list and use their own image instead (basically use the alpine image as a dummy while they do whatever they want with their own container in the pod and ssh to that. We're trying to enforce that people can only ssh to our specific container in the pod image.

The above policy means, "if you see the label `ssh-enabled: true` on a Pod then that Pod must have at least one container with an image beginning with the string `alpine`." That's all it expresses. So if you want something different you'll have to define those intentions.

Also, I've noticed in your samples you keep omitting `any`/`all` blocks from `match`/`exclude` and `deny.conditions`.  You need to specify one or the other. To not do so is not only deprecated but has known issues. This works all the way back to about 1.6 or so.

**Comment by mjschmidt** [comment]
This policy appears to compress them both down appropriately and ensures that if ssh is to be allowed and an authpolicy supporting an ssh connection is enabled, it would require that our ssh container (in this case alpine as our example) and only our ssh container be listed in the pod spec:


The modular control is nice once you get the hang of it. Much appreciated!
``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-ssh-on-specific-container-with-sidecar
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: ssh-enabled-container-check-with-sidecar
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.\"ssh-enabled\" }}"
        operator: Equals
        value: "true"
    validate:
      message: "When 'ssh-enabled' is 'true', the pod must have exactly two containers, one of which must be 'alpine:*'."
      deny:
        conditions:
        - key: "{{ request.object.spec.containers | length }}"
          operator: NotEquals
          value: 2
        - key: "{{ request.object.spec.containers[0].image }}"
          operator: NotEquals
          value: "alpine*"
```
