### ISSUE TITLE
[Sample] rewrite image registry

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#882]
### Problem Statement

rewrite the image registry, to force all pulls throug a proxy cache e.g. with harbor

### Solution Description

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
spec:
  background: false
  rules:
    - name: replace-image-registry
      match:
        any:
        - resources:
            kinds:
            - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          context: 
          - name: imageData
            imageRegistry: 
              reference: "{{ element.image }}"
          preconditions:
            all:
            - key: "{{imageData.image}}"
              operator: Equals
              value: "docker.io/*"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "harbor2.zoller.com/dockerhub-proxy/{{imageData.repository}}:{{imageData.identifier}}"

```

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1704740196988469

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by siddhikhapare** [comment]
I would like to work on this

**Comment by jseiser** [comment]
We tried to use this, and it did not actually handle the bare image registry.  We ended up with this

```
    spec:
      background: false
      rules:
      - name: prepend-registry-containers
        match:
          any:
          - resources:
              kinds:
              - Pod
        preconditions:
          all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
            - CREATE
            - UPDATE
        mutate:
          foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                - name: "{{ element.name }}"           
                  image: "harbor.dev.trex.network/{{ images.containers.\"{{element.name}}\".registry}}/{{ images.containers.\"{{element.name}}\".path}}:{{images.containers.\"{{element.name}}\".tag}}"
      - name: prepend-registry-initcontainers
        match:
          any:
          - resources:
              kinds:
              - Pod
        preconditions:
          all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
            - CREATE
            - UPDATE
          - key: "{{ request.object.spec.initContainers[] || '' | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
        mutate:
          foreach:
          - list: "request.object.spec.initContainers"
            patchStrategicMerge:
              spec:
                initContainers:
                - name: "{{ element.name }}"           
                  image: "harbor.dev.trex.network/{{ images.initContainers.\"{{element.name}}\".registry}}/{{ images.initContainers.\"{{element.name}}\".path}}:{{images.initContainers.\"{{element.name}}\".tag}}"
```

**Comment by siddhikhapare** [comment]
@JimBugwadia I have also tested this policy -
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
  annotations:
    policies.kyverno.io/title: Replace Image Registry
    kyverno.io/kubernetes-version: "1.24"
spec:
  background: false
  rules:
    - name: replace-image-registry-pod-containers
      match:
        any:
          - resources:
            kinds:
              - Pod
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{ element.image }}"
            preconditions:
              any:
                - key: "{{imageData.image}}"
                  operator: Equals
                  value: "docker.io/*"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "harbor2.zoller.com/dockerhub-proxy/{{imageData.repository}}:{{imageData.identifier}}"
    - name: replace-image-registry-pod-initcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
            operator: GreaterThanOrEquals
            value: 1
      mutate:
        foreach:
          - list: "request.object.spec.initContainers"
            context:
              - name: imageData
                imageRegistry:
                  reference: "{{ element.image }}"
            preconditions:
              any:
                - key: "{{imageData.image}}"
                  operator: Equals
                  value: "docker.io/*"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "harbor2.zoller.com/dockerhub-proxy/{{imageData.repository}}:{{imageData.identifier}}"
```

I got this output - 
It should not fail for this patchedresource but it failed
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod1
spec:
  containers:
    - image: harbor2.zoller.com/dockerhub-proxy/nginx:latest
      name: docker-with-registry
```

![output](https://live.staticflickr.com/65535/53455163078_2d3bc9d086_b.jpg)
