### ISSUE TITLE
[Bug] restrict-clusterrole-nodesproxy is overprotective and should take ApiGroups into account

### ISSUE THREAD

**Issue by denisrohr** [kyverno/policies#895]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

Bare metal

### Description

If a ClusterRole gets created that uses the "\*" Resource in any ApiGroup, this policy prevents it, since theoretically the "\*" could include "nodes/proxy" . The "nodes/proxy" Resource however is only dangerous in the "" ApiGroup (the core kubelet api), see https://blog.aquasec.com/privilege-escalation-kubernetes-rbac
The policy doesn't take the ApiGroup into account, breaking a lot of helm charts from granting "\*" Resource access to their own ApiGroups. This for example prevents an istio installation.

A default istio installation tries to create the following clusterrole for example
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: istiod
  name: istiod-clusterrole-istio-system
rules:
- apiGroups:
  - config.istio.io
  - security.istio.io
  - networking.istio.io
  - authentication.istio.io
  - rbac.istio.io
  - telemetry.istio.io
  - extensions.istio.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
```

Since only "nodes/proxy" inside the "" ApiGroup grants you dangerous code execution rights, this policy should be adjusted to also check for the ApiGroups.

A proposed change to the policy, the change is in spec.rules.validate.deny.conditions:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-clusterrole-nodesproxy
  annotations:
    policies.kyverno.io/title: Restrict ClusterRole with Nodes Proxy
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ClusterRole, RBAC
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      A ClusterRole with nodes/proxy resource access allows a user to
      perform anything the kubelet API allows. It also allows users to bypass
      the API server and talk directly to the kubelet potentially circumventing
      audits and admission controllers. See https://blog.aquasec.com/privilege-escalation-kubernetes-rbac
      for more info. This policy prevents the creation
      of a ClusterRole if it contains the nodes/proxy resource. 
spec:
  validationFailureAction: Audit
  background: true
  admission: true
  rules:
    - name: clusterrole-nodesproxy
      match:
        any:
        - resources:
            kinds:
              - ClusterRole
      validate:
        message: "A ClusterRole containing the nodes/proxy resource is not allowed."
        deny:
          conditions:
            all:
            - key: nodes/proxy
              operator: AnyIn
              value: "{{ request.object.rules[].resources[] }}"
            - key: ""
              operator: AnyIn
              value: "{{ request.object.rules[].apiGroups[] }}"
```

### Steps to reproduce

1. Install kyverno (for example via helm)
2. Apply the /other/restrict-clusterrole-nodesproxy/restrict-clusterrole-nodesproxy.yaml policy, but change validationFailureAction to Enforce
3. Try to install istio (for example via helm https://istio.io/latest/docs/setup/install/helm/)
4. The installation gets prevented even though istio doesn't request "nodes/proxy" resources in the ApiGroup "" for the ClusterRole it creates

### Expected behavior

The Rule should only prevent the resource "nodes/proxy" in the "" ApiGroup (the core kubelet api), not in "config.istio.io" ApiGroup.

### Troubleshooting

- [x] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
