### ISSUE TITLE
rule 'require-namespace' from policy 'disallow-default-namespace' does not work as expected

### ISSUE THREAD

**Issue by shilpa-0** [kyverno/policies#90]
Hi,

Do we really need the rule require-namespace in the policy https://github.com/kyverno/policies/blob/main/best-practices/disallow_default_namespace/disallow_default_namespace.yaml?

I expected the below pod to fail the rule but that is not the case. 
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-no-namespace
  labels:
    app: myapp
spec: 
  containers:
  - name: nginx
    image: nginx
```

Is the rule indeed not working as expected or is my understanding wrong here? 

Regards,
Shilpa
