### ISSUE TITLE
[Bug] Sync secret doesn't seem to work

### ISSUE THREAD

**Issue by kohend** [kyverno/policies#912]
### Kyverno Version

1.6.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

Other (specify in description)

### Description

I'm trying to sync the cert-manager created tls certificate using kyverno, I may have made the wrong policy, but it seems consistent with the docs.
It doesn't sync or even behaves as if there's anything to sync.
Running on OCI (OKE)

### Steps to reproduce

1. Install cert-manager and kyverno on system namespace and istio on istio-system
2. create a cluster policy: 
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: copy-tls-secret
spec:
  rules:
  - name: copy-secret
    match:
      all:
      - resources:
          kinds:
          - Secret
          namespaces:
          - system
          names:
          - cert-manager-tls
    generate:
      apiVersion: v1
      kind: Secret
      name: cert-manager-tls
      namespace: istio-system
      synchronize: true
      clone:
        namespace: system
        name: cert-manager-tls
```

### Expected behavior

That when the secret is updated, it'll sync that secret

### Kyverno logs

```shell
I0222 16:46:49.304891       1 generate.go:97] background "msg"="start processing UR" "name"="ur-h6h9x" "policy"="copy-tls-secret" "resource"="v1/Secret/monitoring/prometheus-kube-prometheus-stack-prometheus-tls-assets-0" "resourceVersion"="392682470" "ur"="ur-h6h9x"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
