### ISSUE TITLE
[Bug] ingressClassName update not working

### ISSUE THREAD

**Issue by clcc2019** [kyverno/policies#917]
### Kyverno Version

1.8.x

### Kubernetes Version

1.24.x

### Kubernetes Platform

Other (specify in description)

### Description

update ingress ingressclassname not working
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: upgrade-ingress-class
  annotations:
    policies.kyverno.io/title: Add Ingress Class
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      update ingress ingressClassName 
spec:
  background: false
  rules:
  - name: update-ingress-class
    context:
    - name: className
      variable:
        value: "text"
    match:
      any:
      - resources:
          kinds:
          - Ingress
    mutate:
      patchesJson6902: |-
        - path: /spec/ingressClassName
          op: replace
          value: {{ className }}

```

### Steps to reproduce

  1. apply ClusterPolicy
  2. apply ingress yaml

### Expected behavior

update all ingress ingressclassname

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
On Kyverno 1.11.4...

1. Apply ClusterPolicy as shown above.
2. Apply this Ingress resource (`temp1.yaml`):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  ingressClassName: foo
  rules:
  - host: kuard
    http:
      paths:
      - backend:
          service: 
            name: kuard
            port: 
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - kuard
```
3. See that the value of `ingressClassName` has been changed from `foo` to `text`:
```sh
$ k create -f temp.yaml 
clusterpolicy.kyverno.io/upgrade-ingress-class created

$ k create -f temp1.yaml 
ingress.networking.k8s.io/kuard created

$ k get ing kuard -o yaml | yq .spec.ingressClassName
text
```

Policy works, not a bug. Closed.
