### ISSUE TITLE
Require imagePullPolicy Always

### ISSUE THREAD

**Issue by Kellen275** [kyverno/policies#938]
The following yaml fails the [Require imagePullPolicy Always](https://kyverno.io/policies/other/imagepullpolicy-always/imagepullpolicy-always/) policy.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: busybox:1.0.0
      imagePullPolicy: IfNotPresent
```

My understanding is that this policy should only apply to specs that either use a `latest` tag, or no tag. Am I missing something simple here?
