### ISSUE TITLE
[Need help] prevent-naked-pod custom to bypass node-shell(nsenter) pod in use node-shell command

### ISSUE THREAD

**Issue by younsl** [kyverno/policies#941]
### Kyverno Version

1.11

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

Need help for prevent-naked-pods policy

How can I bypass only `nsenter-*` created by node-shell command in prevent-naked-pod?

In order to bypass only the `nsenter-xxx` pods, an exception was made as a precondition in the prevent-naked-pods policy, but execution of the node-shell command continues to fail.

```bash
$ kubectl node-shell ip-xx-xxx-xxx-xx.ap-northeast-2.compute.internal
spawning "nsenter-i69zpg" on "ip-xx-xxx-xxx-xx.ap-northeast-2.compute.internal"
Error from server: admission webhook "validate.kyverno.svc-ignore" denied the request:

resource Pod/default/nsenter-i69zpg was blocked due to the following policies

prevent-bare-pods:
  bare-pods: preconditions not met
Error from server (NotFound): pods "nsenter-i69zpg" not found
```

### Steps to reproduce

1. Create a EKS cluster v1.29
2. Install kyverno v1.11.4 using official helm chart
3. Apply modified `clusterPolicy` [prevent-bare-pods](https://kyverno.io/policies/other/prevent-bare-pods/prevent-bare-pods/)

```yaml
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-bare-pods
  annotations:
    policies.kyverno.io/title: Prevent Bare Pods
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Other, EKS Best Practices
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Pods not created by workload controllers such as Deployments
      have no self-healing or scaling abilities and are unsuitable for production.
      This policy prevents such "bare" Pods from being created unless they originate
      from a higher-level workload controller of some sort.      
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: bare-pods
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: NotEquals
        value: DELETE
      # Bypass all nsenter pods created by `kubectl node-shell` command.
      - key: "{{request.object.metadata.name}}"
        operator: NotEquals
        value: "nsenter-*"
    validate:
      message: "Bare Pods are not allowed. They must be created by Pod controllers."
      deny:
        conditions:
          any:
          - key: ownerReferences
            operator: AnyNotIn
            value: "{{request.object.metadata.keys(@)}}"
```

**References**: [preconditions](https://kyverno.io/docs/writing-policies/preconditions/#wildcard-matches)

5. Run `kubectl get node` to retrieve testing target node
6. Install node-shell plugin in kubectl

```bash
$ kubectl krew list
PLUGIN      VERSION
...
node-shell  v1.10.1
...
```

7. `kubectl node-shell <YOUR_NODE_NAME>`
8. You will receive deny log

```bash
$ kubectl node-shell ip-xx-xxx-xxx-xx.ap-northeast-2.compute.internal
spawning "nsenter-i69zpg" on "ip-xx-xxx-xxx-xx.ap-northeast-2.compute.internal"
Error from server: admission webhook "validate.kyverno.svc-ignore" denied the request:

resource Pod/default/nsenter-i69zpg was blocked due to the following policies

prevent-bare-pods:
  bare-pods: preconditions not met
Error from server (NotFound): pods "nsenter-i69zpg" not found
```

### Expected behavior

Bypassed `prevent-bare-pods` clusterPolicy and then create `nsenter` pod successfully.

### Screenshots

-

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
