### ISSUE TITLE
drop-cap-net-raw policy does not work as expected

### ISSUE THREAD

**Issue by Danny-Wei** [kyverno/policies#96]
**Software version numbers**

Kubernetes: v1.20.8
Kyverno version: v1.4.2-rc3

**Describe the bug**
The resource which has multiple drop capabilities can not pass the drop-cap-net-raw policy.

**To Reproduce**

1. Apply drop-cap-net-raw policy

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-cap-net-raw
  annotations:
    policies.kyverno.io/title: Drop CAP_NET_RAW
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access. The
      CAP_NET_RAW capability, enabled by default, allows processes in a container to
      forge packets and bind to any interface potentially leading to MitM attacks.
      This policy ensures that all containers explicitly drop the CAP_NET_RAW
      ability.
spec:
  validationFailureAction: enforce
  rules:
  - name: drop-cap-net-raw
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "The capability CAP_NET_RAW must be explicitly dropped."
      pattern:
        spec:
          containers:
          - securityContext:
              capabilities:
                drop: ["NET_RAW"]
          =(initContainers):
          - securityContext:
              capabilities:
                drop: ["NET_RAW"]
```

2. Apply the following resource

```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: debian:9
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        drop:
        - NET_RAW
        - SETUID
```

**Expected behavior**
Resource Pod/default/test created successfully.

**Actual behavior**
Resource Pod/default/test was blocked due to the drop-cap-net-raw policy.

**Comment by chipzoller** [comment]
Confirmed, thanks for raising. @JimBugwadia or @realshuting I thought we were supporting basically an `In` expression for list values like `securityContext.capabilities.drop[]`.

**Comment by realshuting** [comment]
Yes, it is supported https://kyverno.io/docs/writing-policies/preconditions/#operators.

**Comment by realshuting** [comment]
I don't think so. `pattern` in the validate rules only accepts "overlay-styled" definition. You can also build a Deny rule with `In` for this use case.

**Comment by chipzoller** [comment]
So for any logic where one needs to check and see if any one value X is in a list of strings Y it has to be as a condition (either preconditions or deny.conditions)?

**Comment by chipzoller** [comment]
@Danny-Wei This sample should work:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-cap-net-raw
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: drop-cap-net-raw
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: The capability CAP_NET_RAW must be explicitly dropped. All caps are {{ request.object.spec.containers[].securityContext.capabilities.drop[] }}
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.containers[].securityContext.capabilities.drop[] | to_string(@) | contains(@, 'FOO') }}"
            operator: Equals
            value: true
```
Setting `validationFailureAction: audit` does work. The only thing about the above approach here is that these JMESPath expressions are not automatically translated for higher-level pod controllers via Kyverno's auto-gen rules. So you'll have to duplicate the rule, change the `kind`, and modify the variable to suit the schema of that resource kind.

**Comment by Danny-Wei** [comment]
It works. The policy I use is:


```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-net-raw-cap
  annotations:
    policies.kyverno.io/category: Baseline
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access. The
      CAP_NET_RAW capability, enabled by default, allows processes in a container to
      forge packets and bind to any interface potentially leading to MitM attacks.
      This policy ensures that all containers explicitly drop the CAP_NET_RAW ability.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: drop-net-raw-cap
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "The capability NET_RAW must be explicitly dropped."
        deny:
          conditions:
            any:
            - key: "{{ request.object.spec.containers[].securityContext.capabilities.drop | to_string(@) | contains(@, 'NET_RAW') }}"
              operator: Equals
              value: false
```

However, I think we shouldn't use `to_string(@) | contains(@, 'NET_RAW')`. Because this can be bypassed with 'XXXNET_RAWYYY'.

I tried `request.object.spec.containers[].securityContext.capabilities.drop | to_string(@) | to_array(@) | contains(@, 'NET_RAW')` and `request.object.spec.containers[].securityContext.capabilities.drop | to_array(@) | contains(@, 'NET_RAW')` but did not succeed.

**Comment by chipzoller** [comment]
Yes, you're right, you've picked up on something I did in my testing. However, two things:

1. Even if someone could specify a capability that contains that as a substring, it wouldn't do anything. So the underlying kernel wouldn't recognize `XXXNET_RAWYYY` or anything similar. The capability would have to be precise.
2. It should just be possible to do full string match which is what the `contains` function does, however I'm noticing the behavior of this in Kyverno is not consistent with the behavior in the `jp` tool which contains the upstream JMESPath logic. We are investigating.

**Comment by Danny-Wei** [comment]
Thanks for your reply. I was thinking about this scenario:
1. A cluster has a drop-cap-net-raw policy to validate resource creation.
2. Someone can create a Pod that drops `XXXNET_RAWYYY` capability explicitly to bypass the policy.
3. The Pod will be created with NET_RAW capability.

**Comment by chipzoller** [comment]
How are you figuring a Pod spec which defines a capability named `XXXNET_RAWYYY` will result in it finally receiving a capability named `NET_RAW`?

**Comment by Danny-Wei** [comment]
I mean, If we create a Pod that drops 'XXXNET_RAWYYY' capability to pass the policy, then Kubernetes simply ignores 'XXXNET_RAWYYY' and creates the pod with NET_RAW capability.

**Comment by chipzoller** [comment]
Right, I see what you mean. The `NET_RAW` capability will be implicitly granted by virtue of it not having been dropped. So this is definitely a problem where a full string match in the drop array is required and substrings won't work. We'll continue to investigate.

**Comment by chipzoller** [comment]
You can use the query `"spec.containers[].securityContext.capabilities.drop[] | [?@ == 'NET_RAW'] | length(@)"` to check for exact string match rather than using the `contains` function. This might be better in such cases.

**Comment by chipzoller** [comment]
@Danny-Wei although I still have a question out to the chief maintainer of this JMESPath capability, with some help from the JMESPath community I was able to build a query which does definitely work in ensuring that all containers, whether they be initContainers or containers, explicitly specify `NET_RAW` in their drop[] arrays.

Here's the Kyverno policy which *should* (yet doesn't currently) work.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-cap-net-raw
  annotations:
    policies.kyverno.io/title: Drop CAP_NET_RAW
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access. The
      CAP_NET_RAW capability, enabled by default, allows processes in a container to
      forge packets and bind to any interface potentially leading to MitM attacks.
      This policy ensures that all containers explicitly drop the CAP_NET_RAW
      ability.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: drop-cap-net-raw
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: The capability NET_RAW must be explicitly dropped.
      deny:
        conditions:
          any:
          - key: "spec.[containers, initContainers][].securityContext.capabilities.drop.contains(@, 'NET_RAW') | !contains(@, `false`)"
            operator: NotEquals
            value: true
```

We know this JMESPath query works because it has been verified on the jmespath.org (https://jmespath.org/) site's live query. Here's what you can use to verify yourself.

Paste in the JSON Pod spec:

```json
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "name": "test"
  },
  "spec": {
    "initContainers": [
      {
        "name": "jimmy",
        "image": "defdasdabian:923",
        "command": [
          "/bin/sh",
          "-c",
          "sleep infinity"
        ],
        "securityContext": {
          "capabilities": {
            "drop": [
              "NET_RAW",
              "SETUID"
            ]
          }
        }
      }
    ],
    "containers": [
      {
        "name": "test",
        "image": "defdasdabian:923",
        "command": [
          "/bin/sh",
          "-c",
          "sleep infinity"
        ],
        "securityContext": {
          "capabilities": {
            "drop": [
              "SETUID",
              "CAP_FOO_BAR",
              "NET_RAW"
            ]
          }
        }
      },
      {
        "name": "asdf",
        "image": "defdasdabian:923",
        "command": [
          "/bin/sh",
          "-c",
          "sleep infinity"
        ],
        "securityContext": {
          "capabilities": {
            "drop": [
              "NET_RAW",
              "SOME_THING"
            ]
          }
        }
      }
    ]
  }
}
```

In the query box on top, paste in the full query:

```
spec.[containers, initContainers][].securityContext.capabilities.drop.contains(@, 'NET_RAW') | !contains(@, `false`)
```

The result should return `true`.

Go to any one of the drop[] arrays and change one of the `NET_RAW` entries to something else, perhaps `NET_ASDF` and see the return value is now `false`. You should be able to do this for any of the other `NET_RAW` entries as well and until every init/container has this it should continue to report `false`.

**Comment by Danny-Wei** [comment]
@chipzoller Cool, I did a test, it should be working.

I have another question. If we use the `deny.conditions` policy that you mentioned above, can we use `alidationFailureAction: enforce` and `background: true` at the same time? Because we want to run in audit mode for a period of time, and continuously monitor how many resources do not meet the policy through background scanning before enabling enforce mode.

**Comment by chipzoller** [comment]
Policies which use variables from AdmissionReview can't be used in background mode because Kyverno doesn't have access to the payload since the resource already exists.

**Comment by chipzoller** [comment]
@kacejot when you can, see [this reply](https://github.com/kyverno/policies/issues/96#issuecomment-902678290).

**Comment by chipzoller** [comment]
Update: With Kyverno 1.4.3, these `contains()` policies now work as intended and a slight modification to the one [above ](https://github.com/kyverno/policies/issues/96#issuecomment-902678290) works.

`cpol.yaml`

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-cap-net-raw
  annotations:
    policies.kyverno.io/title: Drop CAP_NET_RAW
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access. The
      CAP_NET_RAW capability, enabled by default, allows processes in a container to
      forge packets and bind to any interface potentially leading to MitM attacks.
      This policy ensures that all containers explicitly drop the CAP_NET_RAW
      ability.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: drop-cap-net-raw
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: The capability NET_RAW must be explicitly dropped.
      deny:
        conditions:
        # Get all the entries in each initContainers and containers drop[] array and ensures that every instance contains NET_RAW. If not, deny the request.
        # backticks around false statement (in the key) implies a JSON object and so the value must not be in quotes or is interpreted as a string.
        - key: "{{request.object.spec.[containers, initContainers][].securityContext.capabilities.drop.contains(@, 'NET_RAW') | !contains(@, `false`)}}"
          operator: Equals
          value: false
```

Test with `pod.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  initContainers:
  - name: jimmy
    image: defdasdabian:923
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        drop:
        - NET_RAW
        - SETUID
  containers:
  - name: test
    image: defdasdabian:923
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        drop:
        - SETUID
        - CAP_FOO_BAR
        - NET_RAW
  - name: asdf
    image: defdasdabian:923
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        drop:
        - NET_RAW
        - SOME_THING
```

This should pass as-is. But changing any of the `NET_RAW` entries even slightly (for example, changing one to `XXXNET_RAWYYY`) will cause the Pod to fail.

Using this JMESPath query will be useful many other places in writing policies for Kyverno because it is a condensed yet effective way of checking if a value is found in every array of a given init/container.

Closing issue.
