### ISSUE TITLE
[Bug] Improve policy other/add-node-affinity/add-node-affinity.yaml 

### ISSUE THREAD

**Issue by imjoseangel** [kyverno/policies#965]
### Kyverno Version

1.11

### Kubernetes Version

1.28

### Kubernetes Platform

Minikube

### Description

`patchesJson6902` is not a readable approach for policies. I recommend using `patchStrategicMerge`

### Steps to reproduce

```yaml
      patchesJson6902: |-
        - path: "/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/-1/matchExpressions/-1"
          op: add
          value:
            key: zone_weight
            operator: Lt
            values:
            - "400"
```

### Expected behavior

```yaml
      patchStrategicMerge:
        spec:
          template:
            spec:
              # Add the `affinity`if not already specified.
              +(affinity):
                +(nodeAffinity):
                  +(requiredDuringSchedulingIgnoredDuringExecution):
                    nodeSelectorTerms:
                      - matchExpressions:
                        - key: zone_weight
                          operator: Lt
                          values:
                          - "400"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
