### ISSUE TITLE
[Bug] Unable to deploy via helm on a Istio service mess enabled cluster. 

### ISSUE THREAD

**Issue by mananmongia** [kyverno/policies#980]
### Kyverno Version

1.10

### Kubernetes Version

1.28

### Kubernetes Platform

AKS

### Description

When we deploy helm via image on a verifyimage policy enabled cluster, the Istio injected namespace is not allowing us to update the same deployment in the same namespace. We face the following error:
'''
Error: UPGRADE FAILED: failed to replace object: admission webhook "mutate.kyverno.svc-fail" denied the request: 
resource Deployment/default/release-name-chart-name was blocked due to the following policies 
verify-image:
  autogen-verify-image: kyverno.io/verify-images annotation cannot be changed
''' 

### Steps to reproduce

1. 1. Install Istio with Istioctl via the following given URL (using demo configuration): https://istio.io/latest/docs/setup/getting-started/
2. Deploy Kyverno with HA as given in the official documentation using helm: https://kyverno.io/docs/installation/methods/
```
helm install kyverno kyverno/kyverno --version 3.0.4 -n kyverno --create-namespace \
--set admissionController.replicas=3 \
--set backgroundController.replicas=2 \
--set cleanupController.replicas=2 \
--set reportsController.replicas=2
```
3. Deploy the secret and configure Kyverno to access the private repository, as given in the link: https://kyverno.io/docs/writing-policies/verify-images/sigstore/#authentication .
4. Inject istio to the default namespace `kubectl label namespace default istio-injection=enabled --overwrite`
5. Create a key pair from `cosign generate-key-pair`
6. Create a private Docker repository and push as well as sign the below images with the command `cosign sign -key cosign.key repository/image:tag --tlog-upload=false`
    * nginx:latest
    * nginx:alpine
7. Push another image, but don't sign for it at the end to verify the image policy later.
    * nginx:perl
8. Apply the below policy.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image
  annotations:
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/category: Software Supply Chain Security, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.7.0
    policies.kyverno.io/description: >-
      Using the Cosign project, OCI images may be signed to ensure supply chain
      security is maintained. Those signatures can be verified before pulling into
      a cluster. This policy checks the signature of an image repo called
      ghcr.io/kyverno/test-verify-image to ensure it has been signed by verifying
      its signature against the provided public key. This policy serves as an illustration for
      how to configure a similar rule and will require replacing with your image(s) and keys.      
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      exclude:
        any:
        - resources:
            namespaces:
            - namespace-to-exclude-in-image-policy
      verifyImages:
      - imageReferences:
        - "*"
        mutateDigest: true
        attestors:
        - entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                generated public key
                -----END PUBLIC KEY-----

```
9. Create a fresh helm chart, example name; chart-name.
10. Delete all in the test folder with the newly created chart.
11. Delete all files in templates except deployment and update deployment.yaml as below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test_alpine.fullname" . }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: Always
```
12. Update values.yaml as below
```
replicaCount: 3
image:
  repository: ""
  tag: ""
```

13. Deploy the helm chart with the command post-update with any repositry/image:tag as in point 5: `helm upgrade --install release-name . --set image.tag="some-tag-of-signed-image" --set image.repository="private-repo/private-image"`

14. Try switching between images (point 5 has pushed images to private repositories) with the command in line 13.

This will show an error, as below:
```
Error: UPGRADE FAILED: failed to replace object: admission webhook "mutate.kyverno.svc-fail" denied the request: 
resource Deployment/default/release-name-chart-name was blocked due to the following policies 
verify-image:
  autogen-verify-image: kyverno.io/verify-images annotation cannot be changed
```

### Expected behavior

Helm should have been deployed normally.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
